services:
  website:
    restart: unless-stopped
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    volumes:
      - ./website:/app
    working_dir: /app
    ports:
      - 3000:3000

  control-sdk:
    restart: unless-stopped
    build:
      context: ./control
      dockerfile: Dockerfile.sdk.dev
    volumes:
      - ./control:/app
      - $HOME/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    working_dir: /app
    env_file:
      - control/.sdk.env

  control:
    restart: unless-stopped
    build:
      context: ./control
      dockerfile: Dockerfile.dev
    volumes:
      - ./control:/app
    working_dir: /app
    ports:
      - 1323:1323
    depends_on:
      postgres:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    env_file:
      - control/.env

  backstage-builder:
    restart: unless-stopped
    image: golang:1.26.5-trixie
    volumes:
      - ./backstage:/app
    working_dir: /app
    entrypoint: sh -c 'echo "Building dproxy and dpipe" && cd /app/dpipe && go build -o dpipe ./cmd/dpipe/ && cd /app/dproxy && go build -o dproxy ./cmd/dproxy/ && echo "Building complete" && sleep inf'

  clickhouse:
    image: clickhouse/clickhouse-server:26.7.3.19
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    ports:
      - 8123:8123
      - 9010:9000
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse/
    env_file:
      - .clickhouse.env

  rustfs:
    image: rustfs/rustfs:1.0.0-beta.10
    security_opt:
      - "no-new-privileges:true"
    env_file:
      - .rustfs.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./rustfs-data:/data
      - ./rustfs-logs:/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgweb:
    image: sosedoff/pgweb:0.17.0
    restart: unless-stopped
    env_file:
      - .pgweb.env
    ports:
      - 8082:8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s

  postgres:
    image: postgres:18.4-alpine3.24
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    env_file:
      - .postgres.env
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 10s
      timeout: 5s
      retries: 5
