// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgents = `-- name: CountAgents :one
SELECT count(*) FROM agents
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id FROM agents
WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
	)
	return i, err
}

const getAgentByMachineID = `-- name: GetAgentByMachineID :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id FROM agents WHERE machine_id = $1
`

func (q *Queries) GetAgentByMachineID(ctx context.Context, machineID string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByMachineID, machineID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
	)
	return i, err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id FROM agents
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByTokenHash, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT agents.id, agents.machine_id, agents.hostname, agents.token_hash, agents.status, agents.os, agents.os_version, agents.arch, agents.agent_version, agents.last_seen_at, agents.last_ip, agents.enrolled_key_id, agents.revoked, agents.created_at, agents.updated_at, agents.cpu_count, agents.cpu_percent, agents.load1, agents.load5, agents.load15, agents.mem_total_bytes, agents.mem_used_bytes, agents.disk_total_bytes, agents.disk_used_bytes, agents.uptime_seconds, agents.metrics_at, agents.domain_id, d.tld AS domain_tld
FROM agents
LEFT JOIN domains d ON d.id = agents.domain_id
ORDER BY agents.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32
	Offset int32
}

type ListAgentsRow struct {
	Agent     Agent
	DomainTLD pgtype.Text
}

// The domain is joined in rather than resolved per row by the caller: the admin
// table shows the TLD, not the id, and one join beats a lookup per agent.
func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.Agent.ID,
			&i.Agent.MachineID,
			&i.Agent.Hostname,
			&i.Agent.TokenHash,
			&i.Agent.Status,
			&i.Agent.OS,
			&i.Agent.OSVersion,
			&i.Agent.Arch,
			&i.Agent.AgentVersion,
			&i.Agent.LastSeenAt,
			&i.Agent.LastIP,
			&i.Agent.EnrolledKeyID,
			&i.Agent.Revoked,
			&i.Agent.CreatedAt,
			&i.Agent.UpdatedAt,
			&i.Agent.CPUCount,
			&i.Agent.CPUPercent,
			&i.Agent.Load1,
			&i.Agent.Load5,
			&i.Agent.Load15,
			&i.Agent.MemTotalBytes,
			&i.Agent.MemUsedBytes,
			&i.Agent.DiskTotalBytes,
			&i.Agent.DiskUsedBytes,
			&i.Agent.UptimeSeconds,
			&i.Agent.MetricsAt,
			&i.Agent.DomainID,
			&i.DomainTLD,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableHosts = `-- name: ListAvailableHosts :many
SELECT id, hostname FROM agents
WHERE revoked = false
ORDER BY (
    SELECT count(*) FROM vms
    WHERE vms.agent_id = agents.id AND vms.status IN ('pending', 'running')
) ASC, last_seen_at DESC NULLS LAST
`

type ListAvailableHostsRow struct {
	ID       pgtype.UUID
	Hostname string
}

// ListAvailableHosts is the host list a self-service caller picks from, least
// busy first so the default choice spreads load instead of piling onto whichever
// agent happens to sort first.
//
// Deliberately NOT filtered on status: that column is a cached copy of
// connectivity and goes stale -- startup sets every agent 'offline', and a
// reconnect that has not written back yet would hide a host that is genuinely
// there. The hub is the authority, and the caller filters on it. Matching what
// the admin screen does, which reads connectivity only from the hub.
func (q *Queries) ListAvailableHosts(ctx context.Context) ([]ListAvailableHostsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableHostsRow
	for rows.Next() {
		var i ListAvailableHostsRow
		if err := rows.Scan(&i.ID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgent = `-- name: RevokeAgent :exec
UPDATE agents
SET revoked = true, status = 'offline', updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgent, id)
	return err
}

const setAgentOffline = `-- name: SetAgentOffline :exec
UPDATE agents
SET status = 'offline', last_seen_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetAgentOffline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setAgentOffline, id)
	return err
}

const setAgentOnline = `-- name: SetAgentOnline :exec
UPDATE agents
SET status = 'online', last_seen_at = now(), last_ip = $2, updated_at = now()
WHERE id = $1
`

type SetAgentOnlineParams struct {
	ID     pgtype.UUID
	LastIP string
}

func (q *Queries) SetAgentOnline(ctx context.Context, arg SetAgentOnlineParams) error {
	_, err := q.db.Exec(ctx, setAgentOnline, arg.ID, arg.LastIP)
	return err
}

const setAllAgentsOffline = `-- name: SetAllAgentsOffline :exec
UPDATE agents
SET status = 'offline', updated_at = now()
WHERE status <> 'offline'
`

// SetAllAgentsOffline runs at startup: the hub is in-memory, so any 'online'
// row left behind by a previous process is stale.
func (q *Queries) SetAllAgentsOffline(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setAllAgentsOffline)
	return err
}

const touchAgentLastSeen = `-- name: TouchAgentLastSeen :exec
UPDATE agents
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchAgentLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAgentLastSeen, id)
	return err
}

const updateAgentFacts = `-- name: UpdateAgentFacts :exec
UPDATE agents
SET hostname = $2, os = $3, os_version = $4, arch = $5, agent_version = $6, updated_at = now()
WHERE id = $1
`

type UpdateAgentFactsParams struct {
	ID           pgtype.UUID
	Hostname     string
	OS           string
	OSVersion    string
	Arch         string
	AgentVersion string
}

func (q *Queries) UpdateAgentFacts(ctx context.Context, arg UpdateAgentFactsParams) error {
	_, err := q.db.Exec(ctx, updateAgentFacts,
		arg.ID,
		arg.Hostname,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.AgentVersion,
	)
	return err
}

const updateAgentMetrics = `-- name: UpdateAgentMetrics :exec
UPDATE agents
SET cpu_count        = $2,
    cpu_percent      = $3,
    load1            = $4,
    load5            = $5,
    load15           = $6,
    mem_total_bytes  = $7,
    mem_used_bytes   = $8,
    disk_total_bytes = $9,
    disk_used_bytes  = $10,
    uptime_seconds   = $11,
    metrics_at       = now(),
    last_seen_at     = now()
WHERE id = $1
`

type UpdateAgentMetricsParams struct {
	ID             pgtype.UUID
	CPUCount       int32
	CPUPercent     float64
	Load1          float64
	Load5          float64
	Load15         float64
	MemTotalBytes  int64
	MemUsedBytes   int64
	DiskTotalBytes int64
	DiskUsedBytes  int64
	UptimeSeconds  int64
}

// UpdateAgentMetrics overwrites the host snapshot in place. last_seen_at moves
// too: a metrics frame is proof the agent is alive, and it arrives often enough
// that the throttled touch in the read loop rarely has anything left to do.
func (q *Queries) UpdateAgentMetrics(ctx context.Context, arg UpdateAgentMetricsParams) error {
	_, err := q.db.Exec(ctx, updateAgentMetrics,
		arg.ID,
		arg.CPUCount,
		arg.CPUPercent,
		arg.Load1,
		arg.Load5,
		arg.Load15,
		arg.MemTotalBytes,
		arg.MemUsedBytes,
		arg.DiskTotalBytes,
		arg.DiskUsedBytes,
		arg.UptimeSeconds,
	)
	return err
}

const upsertAgentByMachineID = `-- name: UpsertAgentByMachineID :one
INSERT INTO agents (machine_id, hostname, token_hash, os, os_version, arch, agent_version, enrolled_key_id, domain_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (machine_id) DO UPDATE
SET hostname        = EXCLUDED.hostname,
    token_hash      = EXCLUDED.token_hash,
    os              = EXCLUDED.os,
    os_version      = EXCLUDED.os_version,
    arch            = EXCLUDED.arch,
    agent_version   = EXCLUDED.agent_version,
    enrolled_key_id = EXCLUDED.enrolled_key_id,
    -- COALESCE, not EXCLUDED: a domain already on the row was either assigned
    -- deliberately or picked at first enrollment, and a re-enroll is not a
    -- statement about which domain the machine belongs to.
    domain_id       = COALESCE(agents.domain_id, EXCLUDED.domain_id),
    revoked         = false,
    updated_at      = now()
RETURNING id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id
`

type UpsertAgentByMachineIDParams struct {
	MachineID     string
	Hostname      string
	TokenHash     string
	OS            string
	OSVersion     string
	Arch          string
	AgentVersion  string
	EnrolledKeyID pgtype.UUID
	DomainID      pgtype.UUID
}

// UpsertAgentByMachineID re-enrolls an existing machine in place rather than
// creating a duplicate row: the token is rotated and the facts refreshed. A
// previously revoked agent is restored, because holding a valid enrollment key
// is the authorization to enroll.
func (q *Queries) UpsertAgentByMachineID(ctx context.Context, arg UpsertAgentByMachineIDParams) (Agent, error) {
	row := q.db.QueryRow(ctx, upsertAgentByMachineID,
		arg.MachineID,
		arg.Hostname,
		arg.TokenHash,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.AgentVersion,
		arg.EnrolledKeyID,
		arg.DomainID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
	)
	return i, err
}
