// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgents = `-- name: CountAgents :one
SELECT count(*) FROM agents
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at FROM agents
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByTokenHash, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at FROM agents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Hostname,
			&i.TokenHash,
			&i.Status,
			&i.OS,
			&i.OSVersion,
			&i.Arch,
			&i.AgentVersion,
			&i.LastSeenAt,
			&i.LastIP,
			&i.EnrolledKeyID,
			&i.Revoked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgent = `-- name: RevokeAgent :exec
UPDATE agents
SET revoked = true, status = 'offline', updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgent, id)
	return err
}

const setAgentOffline = `-- name: SetAgentOffline :exec
UPDATE agents
SET status = 'offline', last_seen_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetAgentOffline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setAgentOffline, id)
	return err
}

const setAgentOnline = `-- name: SetAgentOnline :exec
UPDATE agents
SET status = 'online', last_seen_at = now(), last_ip = $2, updated_at = now()
WHERE id = $1
`

type SetAgentOnlineParams struct {
	ID     pgtype.UUID
	LastIP string
}

func (q *Queries) SetAgentOnline(ctx context.Context, arg SetAgentOnlineParams) error {
	_, err := q.db.Exec(ctx, setAgentOnline, arg.ID, arg.LastIP)
	return err
}

const setAllAgentsOffline = `-- name: SetAllAgentsOffline :exec
UPDATE agents
SET status = 'offline', updated_at = now()
WHERE status <> 'offline'
`

// SetAllAgentsOffline runs at startup: the hub is in-memory, so any 'online'
// row left behind by a previous process is stale.
func (q *Queries) SetAllAgentsOffline(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setAllAgentsOffline)
	return err
}

const touchAgentLastSeen = `-- name: TouchAgentLastSeen :exec
UPDATE agents
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchAgentLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAgentLastSeen, id)
	return err
}

const updateAgentFacts = `-- name: UpdateAgentFacts :exec
UPDATE agents
SET hostname = $2, os = $3, os_version = $4, arch = $5, agent_version = $6, updated_at = now()
WHERE id = $1
`

type UpdateAgentFactsParams struct {
	ID           pgtype.UUID
	Hostname     string
	OS           string
	OSVersion    string
	Arch         string
	AgentVersion string
}

func (q *Queries) UpdateAgentFacts(ctx context.Context, arg UpdateAgentFactsParams) error {
	_, err := q.db.Exec(ctx, updateAgentFacts,
		arg.ID,
		arg.Hostname,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.AgentVersion,
	)
	return err
}

const upsertAgentByMachineID = `-- name: UpsertAgentByMachineID :one
INSERT INTO agents (machine_id, hostname, token_hash, os, os_version, arch, agent_version, enrolled_key_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (machine_id) DO UPDATE
SET hostname        = EXCLUDED.hostname,
    token_hash      = EXCLUDED.token_hash,
    os              = EXCLUDED.os,
    os_version      = EXCLUDED.os_version,
    arch            = EXCLUDED.arch,
    agent_version   = EXCLUDED.agent_version,
    enrolled_key_id = EXCLUDED.enrolled_key_id,
    revoked         = false,
    updated_at      = now()
RETURNING id, machine_id, hostname, token_hash, status, os, os_version, arch, agent_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at
`

type UpsertAgentByMachineIDParams struct {
	MachineID     string
	Hostname      string
	TokenHash     string
	OS            string
	OSVersion     string
	Arch          string
	AgentVersion  string
	EnrolledKeyID pgtype.UUID
}

// UpsertAgentByMachineID re-enrolls an existing machine in place rather than
// creating a duplicate row: the token is rotated and the facts refreshed. A
// previously revoked agent is restored, because holding a valid enrollment key
// is the authorization to enroll.
func (q *Queries) UpsertAgentByMachineID(ctx context.Context, arg UpsertAgentByMachineIDParams) (Agent, error) {
	row := q.db.QueryRow(ctx, upsertAgentByMachineID,
		arg.MachineID,
		arg.Hostname,
		arg.TokenHash,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.AgentVersion,
		arg.EnrolledKeyID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.AgentVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
