// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_enrollment_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnrollmentKey = `-- name: ConsumeEnrollmentKey :one
UPDATE client_enrollment_keys
SET uses = uses + 1
WHERE key_hash = $1
  AND revoked = false
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR uses < max_uses)
RETURNING id, key_hash, key_prefix, label, max_uses, uses, expires_at, revoked, created_by, created_at
`

// ConsumeEnrollmentKey claims one use of a key. Validity (not revoked, not
// expired, uses remaining) is checked in the same statement that increments the
// counter, so two clients racing on a single-use key cannot both win. Zero rows
// means unknown/revoked/expired/exhausted -- the caller must not distinguish.
func (q *Queries) ConsumeEnrollmentKey(ctx context.Context, keyHash string) (ClientEnrollmentKey, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentKey, keyHash)
	var i ClientEnrollmentKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countEnrollmentKeys = `-- name: CountEnrollmentKeys :one
SELECT count(*) FROM client_enrollment_keys
`

func (q *Queries) CountEnrollmentKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollmentKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollmentKey = `-- name: CreateEnrollmentKey :one
INSERT INTO client_enrollment_keys (key_hash, key_prefix, label, max_uses, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, key_hash, key_prefix, label, max_uses, uses, expires_at, revoked, created_by, created_at
`

type CreateEnrollmentKeyParams struct {
	KeyHash   string
	KeyPrefix string
	Label     string
	MaxUses   pgtype.Int4
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateEnrollmentKey(ctx context.Context, arg CreateEnrollmentKeyParams) (ClientEnrollmentKey, error) {
	row := q.db.QueryRow(ctx, createEnrollmentKey,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Label,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ClientEnrollmentKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnrollmentKey = `-- name: DeleteEnrollmentKey :exec
DELETE FROM client_enrollment_keys
WHERE id = $1
`

func (q *Queries) DeleteEnrollmentKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollmentKey, id)
	return err
}

const listEnrollmentKeys = `-- name: ListEnrollmentKeys :many
SELECT id, key_hash, key_prefix, label, max_uses, uses, expires_at, revoked, created_by, created_at FROM client_enrollment_keys
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEnrollmentKeysParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEnrollmentKeys(ctx context.Context, arg ListEnrollmentKeysParams) ([]ClientEnrollmentKey, error) {
	rows, err := q.db.Query(ctx, listEnrollmentKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientEnrollmentKey
	for rows.Next() {
		var i ClientEnrollmentKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Label,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEnrollmentKey = `-- name: RevokeEnrollmentKey :exec
UPDATE client_enrollment_keys
SET revoked = true
WHERE id = $1
`

func (q *Queries) RevokeEnrollmentKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeEnrollmentKey, id)
	return err
}
