// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClients = `-- name: CountClients :one
SELECT count(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}

const getClientByMachineID = `-- name: GetClientByMachineID :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version FROM clients WHERE machine_id = $1
`

func (q *Queries) GetClientByMachineID(ctx context.Context, machineID string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByMachineID, machineID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}

const getClientByTokenHash = `-- name: GetClientByTokenHash :one
SELECT id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version FROM clients
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetClientByTokenHash(ctx context.Context, tokenHash string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByTokenHash, tokenHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}

const listAvailableHosts = `-- name: ListAvailableHosts :many
SELECT id, hostname FROM clients
WHERE revoked = false
ORDER BY (
    SELECT count(*) FROM vms
    WHERE vms.client_id = clients.id AND vms.status IN ('pending', 'running')
) ASC, last_seen_at DESC NULLS LAST
`

type ListAvailableHostsRow struct {
	ID       pgtype.UUID
	Hostname string
}

func (q *Queries) ListAvailableHosts(ctx context.Context) ([]ListAvailableHostsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableHostsRow
	for rows.Next() {
		var i ListAvailableHostsRow
		if err := rows.Scan(&i.ID, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT clients.id, clients.machine_id, clients.hostname, clients.token_hash, clients.status, clients.os, clients.os_version, clients.arch, clients.client_version, clients.last_seen_at, clients.last_ip, clients.enrolled_key_id, clients.revoked, clients.created_at, clients.updated_at, clients.cpu_count, clients.cpu_percent, clients.load1, clients.load5, clients.load15, clients.mem_total_bytes, clients.mem_used_bytes, clients.disk_total_bytes, clients.disk_used_bytes, clients.uptime_seconds, clients.metrics_at, clients.domain_id, clients.dclient_version, clients.dclient_download_url, clients.dpipe_version, clients.dpipe_download_url, clients.proxy_version, clients.proxy_download_url, clients.dpipe_installed_version, clients.proxy_installed_version, d.tld AS domain_tld
FROM clients
LEFT JOIN domains d ON d.id = clients.domain_id
ORDER BY clients.created_at DESC
LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32
	Offset int32
}

type ListClientsRow struct {
	Client    Client
	DomainTLD pgtype.Text
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.Client.ID,
			&i.Client.MachineID,
			&i.Client.Hostname,
			&i.Client.TokenHash,
			&i.Client.Status,
			&i.Client.OS,
			&i.Client.OSVersion,
			&i.Client.Arch,
			&i.Client.ClientVersion,
			&i.Client.LastSeenAt,
			&i.Client.LastIP,
			&i.Client.EnrolledKeyID,
			&i.Client.Revoked,
			&i.Client.CreatedAt,
			&i.Client.UpdatedAt,
			&i.Client.CPUCount,
			&i.Client.CPUPercent,
			&i.Client.Load1,
			&i.Client.Load5,
			&i.Client.Load15,
			&i.Client.MemTotalBytes,
			&i.Client.MemUsedBytes,
			&i.Client.DiskTotalBytes,
			&i.Client.DiskUsedBytes,
			&i.Client.UptimeSeconds,
			&i.Client.MetricsAt,
			&i.Client.DomainID,
			&i.Client.DclientVersion,
			&i.Client.DclientDownloadURL,
			&i.Client.DpipeVersion,
			&i.Client.DpipeDownloadURL,
			&i.Client.ProxyVersion,
			&i.Client.ProxyDownloadURL,
			&i.Client.DpipeInstalledVersion,
			&i.Client.ProxyInstalledVersion,
			&i.DomainTLD,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeClient = `-- name: RevokeClient :exec
UPDATE clients
SET revoked = true, status = 'offline', updated_at = now()
WHERE id = $1
`

func (q *Queries) RevokeClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeClient, id)
	return err
}

const setAllClientsOffline = `-- name: SetAllClientsOffline :exec
UPDATE clients
SET status = 'offline', updated_at = now()
WHERE status <> 'offline'
`

func (q *Queries) SetAllClientsOffline(ctx context.Context) error {
	_, err := q.db.Exec(ctx, setAllClientsOffline)
	return err
}

const setClientDomain = `-- name: SetClientDomain :one
UPDATE clients
SET domain_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version
`

type SetClientDomainParams struct {
	ID       pgtype.UUID
	DomainID pgtype.UUID
}

func (q *Queries) SetClientDomain(ctx context.Context, arg SetClientDomainParams) (Client, error) {
	row := q.db.QueryRow(ctx, setClientDomain, arg.ID, arg.DomainID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}

const setClientOffline = `-- name: SetClientOffline :exec
UPDATE clients
SET status = 'offline', last_seen_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetClientOffline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setClientOffline, id)
	return err
}

const setClientOnline = `-- name: SetClientOnline :exec
UPDATE clients
SET status = 'online', last_seen_at = now(), last_ip = $2, updated_at = now()
WHERE id = $1
`

type SetClientOnlineParams struct {
	ID     pgtype.UUID
	LastIP string
}

func (q *Queries) SetClientOnline(ctx context.Context, arg SetClientOnlineParams) error {
	_, err := q.db.Exec(ctx, setClientOnline, arg.ID, arg.LastIP)
	return err
}

const touchClientLastSeen = `-- name: TouchClientLastSeen :exec
UPDATE clients
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchClientLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchClientLastSeen, id)
	return err
}

const updateClientFacts = `-- name: UpdateClientFacts :exec
UPDATE clients
SET hostname = $2, os = $3, os_version = $4, arch = $5, client_version = $6, updated_at = now()
WHERE id = $1
`

type UpdateClientFactsParams struct {
	ID            pgtype.UUID
	Hostname      string
	OS            string
	OSVersion     string
	Arch          string
	ClientVersion string
}

func (q *Queries) UpdateClientFacts(ctx context.Context, arg UpdateClientFactsParams) error {
	_, err := q.db.Exec(ctx, updateClientFacts,
		arg.ID,
		arg.Hostname,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.ClientVersion,
	)
	return err
}

const updateClientInstalledVersions = `-- name: UpdateClientInstalledVersions :exec
UPDATE clients
SET dpipe_installed_version = $2,
    proxy_installed_version = $3,
    updated_at              = now()
WHERE id = $1
`

type UpdateClientInstalledVersionsParams struct {
	ID                    pgtype.UUID
	DpipeInstalledVersion string
	ProxyInstalledVersion string
}

func (q *Queries) UpdateClientInstalledVersions(ctx context.Context, arg UpdateClientInstalledVersionsParams) error {
	_, err := q.db.Exec(ctx, updateClientInstalledVersions, arg.ID, arg.DpipeInstalledVersion, arg.ProxyInstalledVersion)
	return err
}

const updateClientMetrics = `-- name: UpdateClientMetrics :exec
UPDATE clients
SET cpu_count        = $2,
    cpu_percent      = $3,
    load1            = $4,
    load5            = $5,
    load15           = $6,
    mem_total_bytes  = $7,
    mem_used_bytes   = $8,
    disk_total_bytes = $9,
    disk_used_bytes  = $10,
    uptime_seconds   = $11,
    metrics_at       = now(),
    last_seen_at     = now()
WHERE id = $1
`

type UpdateClientMetricsParams struct {
	ID             pgtype.UUID
	CPUCount       int32
	CPUPercent     float64
	Load1          float64
	Load5          float64
	Load15         float64
	MemTotalBytes  int64
	MemUsedBytes   int64
	DiskTotalBytes int64
	DiskUsedBytes  int64
	UptimeSeconds  int64
}

func (q *Queries) UpdateClientMetrics(ctx context.Context, arg UpdateClientMetricsParams) error {
	_, err := q.db.Exec(ctx, updateClientMetrics,
		arg.ID,
		arg.CPUCount,
		arg.CPUPercent,
		arg.Load1,
		arg.Load5,
		arg.Load15,
		arg.MemTotalBytes,
		arg.MemUsedBytes,
		arg.DiskTotalBytes,
		arg.DiskUsedBytes,
		arg.UptimeSeconds,
	)
	return err
}

const updateClientServiceVersions = `-- name: UpdateClientServiceVersions :one
UPDATE clients
SET dclient_version      = $2,
    dclient_download_url = $3,
    dpipe_version        = $4,
    dpipe_download_url   = $5,
    proxy_version        = $6,
    proxy_download_url   = $7,
    updated_at           = now()
WHERE id = $1
RETURNING id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version
`

type UpdateClientServiceVersionsParams struct {
	ID                 pgtype.UUID
	DclientVersion     string
	DclientDownloadURL string
	DpipeVersion       string
	DpipeDownloadURL   string
	ProxyVersion       string
	ProxyDownloadURL   string
}

func (q *Queries) UpdateClientServiceVersions(ctx context.Context, arg UpdateClientServiceVersionsParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientServiceVersions,
		arg.ID,
		arg.DclientVersion,
		arg.DclientDownloadURL,
		arg.DpipeVersion,
		arg.DpipeDownloadURL,
		arg.ProxyVersion,
		arg.ProxyDownloadURL,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}

const upsertClientByMachineID = `-- name: UpsertClientByMachineID :one
INSERT INTO clients (machine_id, hostname, token_hash, os, os_version, arch, client_version, enrolled_key_id, domain_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (machine_id) DO UPDATE
SET hostname        = EXCLUDED.hostname,
    token_hash      = EXCLUDED.token_hash,
    os              = EXCLUDED.os,
    os_version      = EXCLUDED.os_version,
    arch            = EXCLUDED.arch,
    client_version   = EXCLUDED.client_version,
    enrolled_key_id = EXCLUDED.enrolled_key_id,
    domain_id       = COALESCE(clients.domain_id, EXCLUDED.domain_id),
    revoked         = false,
    updated_at      = now()
RETURNING id, machine_id, hostname, token_hash, status, os, os_version, arch, client_version, last_seen_at, last_ip, enrolled_key_id, revoked, created_at, updated_at, cpu_count, cpu_percent, load1, load5, load15, mem_total_bytes, mem_used_bytes, disk_total_bytes, disk_used_bytes, uptime_seconds, metrics_at, domain_id, dclient_version, dclient_download_url, dpipe_version, dpipe_download_url, proxy_version, proxy_download_url, dpipe_installed_version, proxy_installed_version
`

type UpsertClientByMachineIDParams struct {
	MachineID     string
	Hostname      string
	TokenHash     string
	OS            string
	OSVersion     string
	Arch          string
	ClientVersion string
	EnrolledKeyID pgtype.UUID
	DomainID      pgtype.UUID
}

func (q *Queries) UpsertClientByMachineID(ctx context.Context, arg UpsertClientByMachineIDParams) (Client, error) {
	row := q.db.QueryRow(ctx, upsertClientByMachineID,
		arg.MachineID,
		arg.Hostname,
		arg.TokenHash,
		arg.OS,
		arg.OSVersion,
		arg.Arch,
		arg.ClientVersion,
		arg.EnrolledKeyID,
		arg.DomainID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Hostname,
		&i.TokenHash,
		&i.Status,
		&i.OS,
		&i.OSVersion,
		&i.Arch,
		&i.ClientVersion,
		&i.LastSeenAt,
		&i.LastIP,
		&i.EnrolledKeyID,
		&i.Revoked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CPUCount,
		&i.CPUPercent,
		&i.Load1,
		&i.Load5,
		&i.Load15,
		&i.MemTotalBytes,
		&i.MemUsedBytes,
		&i.DiskTotalBytes,
		&i.DiskUsedBytes,
		&i.UptimeSeconds,
		&i.MetricsAt,
		&i.DomainID,
		&i.DclientVersion,
		&i.DclientDownloadURL,
		&i.DpipeVersion,
		&i.DpipeDownloadURL,
		&i.ProxyVersion,
		&i.ProxyDownloadURL,
		&i.DpipeInstalledVersion,
		&i.ProxyInstalledVersion,
	)
	return i, err
}
