// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_domain_certs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCustomDomainCert = `-- name: DeleteCustomDomainCert :exec
DELETE FROM custom_domain_certs
WHERE id = $1
`

func (q *Queries) DeleteCustomDomainCert(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomDomainCert, id)
	return err
}

const getCustomDomainCert = `-- name: GetCustomDomainCert :one
SELECT id, domain, owner_id, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, created_at, updated_at FROM custom_domain_certs
WHERE domain = $1
`

func (q *Queries) GetCustomDomainCert(ctx context.Context, domain string) (CustomDomainCert, error) {
	row := q.db.QueryRow(ctx, getCustomDomainCert, domain)
	var i CustomDomainCert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.OwnerID,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainCertByID = `-- name: GetCustomDomainCertByID :one
SELECT id, domain, owner_id, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, created_at, updated_at FROM custom_domain_certs
WHERE id = $1
`

func (q *Queries) GetCustomDomainCertByID(ctx context.Context, id pgtype.UUID) (CustomDomainCert, error) {
	row := q.db.QueryRow(ctx, getCustomDomainCertByID, id)
	var i CustomDomainCert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.OwnerID,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomDomainCerts = `-- name: ListCustomDomainCerts :many
SELECT c.id, c.domain, c.owner_id, c.cert_object_key, c.key_object_key, c.cert_fingerprint, c.cert_not_after, c.cert_issued_at, c.created_at, c.updated_at,
       COALESCE(u.username, '')::text      AS owner_username,
       COALESCE(u.email, '')::text         AS owner_email,
       COALESCE(v.name, '')::text          AS vm_name,
       COALESCE(cd.status, '')::text       AS domain_status
FROM custom_domain_certs c
LEFT JOIN users u ON u.id = c.owner_id
LEFT JOIN vm_custom_domains cd ON cd.domain = c.domain
LEFT JOIN vms v ON v.id = cd.vm_id
ORDER BY c.domain
`

type ListCustomDomainCertsRow struct {
	ID              pgtype.UUID
	Domain          string
	OwnerID         pgtype.UUID
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
	CertIssuedAt    pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	OwnerUsername   string
	OwnerEmail      string
	VMName          string
	DomainStatus    string
}

func (q *Queries) ListCustomDomainCerts(ctx context.Context) ([]ListCustomDomainCertsRow, error) {
	rows, err := q.db.Query(ctx, listCustomDomainCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomDomainCertsRow
	for rows.Next() {
		var i ListCustomDomainCertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.OwnerID,
			&i.CertObjectKey,
			&i.KeyObjectKey,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.CertIssuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerEmail,
			&i.VMName,
			&i.DomainStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReclaimableCustomDomainCerts = `-- name: ListReclaimableCustomDomainCerts :many
SELECT id, domain, owner_id, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, created_at, updated_at FROM custom_domain_certs
WHERE cert_not_after < now()
  AND NOT EXISTS (
      SELECT 1 FROM vm_custom_domains cd WHERE cd.domain = custom_domain_certs.domain
  )
`

// Reclaimable means expired with no vm bound to the domain any longer. One that
// is still bound is left alone: the renewal sweep owns it.
func (q *Queries) ListReclaimableCustomDomainCerts(ctx context.Context) ([]CustomDomainCert, error) {
	rows, err := q.db.Query(ctx, listReclaimableCustomDomainCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomDomainCert
	for rows.Next() {
		var i CustomDomainCert
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.OwnerID,
			&i.CertObjectKey,
			&i.KeyObjectKey,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.CertIssuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomDomainCert = `-- name: UpsertCustomDomainCert :one
INSERT INTO custom_domain_certs
    (domain, owner_id, cert_object_key, key_object_key, cert_fingerprint, cert_not_after)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (domain) DO UPDATE
SET owner_id         = EXCLUDED.owner_id,
    cert_object_key  = EXCLUDED.cert_object_key,
    key_object_key   = EXCLUDED.key_object_key,
    cert_fingerprint = EXCLUDED.cert_fingerprint,
    cert_not_after   = EXCLUDED.cert_not_after,
    cert_issued_at   = now(),
    updated_at       = now()
RETURNING id, domain, owner_id, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, created_at, updated_at
`

type UpsertCustomDomainCertParams struct {
	Domain          string
	OwnerID         pgtype.UUID
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
}

func (q *Queries) UpsertCustomDomainCert(ctx context.Context, arg UpsertCustomDomainCertParams) (CustomDomainCert, error) {
	row := q.db.QueryRow(ctx, upsertCustomDomainCert,
		arg.Domain,
		arg.OwnerID,
		arg.CertObjectKey,
		arg.KeyObjectKey,
		arg.CertFingerprint,
		arg.CertNotAfter,
	)
	var i CustomDomainCert
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.OwnerID,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
