// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDomains = `-- name: CountDomains :one
SELECT count(*) FROM domains
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (tld)
VALUES ($1)
RETURNING id, tld
`

func (q *Queries) CreateDomain(ctx context.Context, tld string) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, tld)
	var i Domain
	err := row.Scan(&i.ID, &i.TLD)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomain, id)
	return err
}

const getSoleDomain = `-- name: GetSoleDomain :one
SELECT id, tld FROM domains
WHERE (SELECT count(*) FROM domains) = 1
`

// GetSoleDomain returns the single configured domain, and no rows when there is
// none or more than one. Enrollment uses it to pick a domain for a new client
// without having to guess: with exactly one there is nothing to choose, and with
// several the choice is the operator's, so the client is left unassigned.
func (q *Queries) GetSoleDomain(ctx context.Context) (Domain, error) {
	row := q.db.QueryRow(ctx, getSoleDomain)
	var i Domain
	err := row.Scan(&i.ID, &i.TLD)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, tld FROM domains
ORDER BY tld
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(&i.ID, &i.TLD); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
