// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDomainCert = `-- name: ClearDomainCert :one
UPDATE domains
SET cert_object_key  = '',
    key_object_key   = '',
    cert_fingerprint = '',
    cert_not_after   = NULL,
    cert_issued_at   = NULL,
    cert_error       = '',
    tls_enabled      = false,
    updated_at       = now()
WHERE id = $1
RETURNING id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at
`

func (q *Queries) ClearDomainCert(ctx context.Context, id pgtype.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, clearDomainCert, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDomains = `-- name: CountDomains :one
SELECT count(*) FROM domains
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (tld)
VALUES ($1)
RETURNING id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at
`

func (q *Queries) CreateDomain(ctx context.Context, tld string) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, tld)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomain, id)
	return err
}

const getClientDomain = `-- name: GetClientDomain :one
SELECT d.id, d.tld, d.tls_enabled, d.cert_mode, d.acme_directory, d.acme_email, d.acme_credentials, d.acme_account_key, d.cert_object_key, d.key_object_key, d.cert_fingerprint, d.cert_not_after, d.cert_error, d.cert_issued_at, d.updated_at FROM domains d
JOIN clients c ON c.domain_id = d.id
WHERE c.id = $1
`

func (q *Queries) GetClientDomain(ctx context.Context, id pgtype.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getClientDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at FROM domains
WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id pgtype.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSoleDomain = `-- name: GetSoleDomain :one
SELECT id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at FROM domains
WHERE (SELECT count(*) FROM domains) = 1
`

func (q *Queries) GetSoleDomain(ctx context.Context) (Domain, error) {
	row := q.db.QueryRow(ctx, getSoleDomain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientIDsByDomain = `-- name: ListClientIDsByDomain :many
SELECT id FROM clients
WHERE domain_id = $1 AND NOT revoked
`

func (q *Queries) ListClientIDsByDomain(ctx context.Context, domainID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listClientIDsByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at FROM domains
ORDER BY tld
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.TLD,
			&i.TlsEnabled,
			&i.CertMode,
			&i.AcmeDirectory,
			&i.AcmeEmail,
			&i.AcmeCredentials,
			&i.AcmeAccountKey,
			&i.CertObjectKey,
			&i.KeyObjectKey,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.CertError,
			&i.CertIssuedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsDueForRenewal = `-- name: ListDomainsDueForRenewal :many
SELECT id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at FROM domains
WHERE tls_enabled
  AND cert_mode = 'acme_cloudflare'
  AND acme_credentials <> ''
  AND (cert_not_after IS NULL OR cert_not_after < now() + make_interval(secs => $1::float))
ORDER BY cert_not_after NULLS FIRST
`

func (q *Queries) ListDomainsDueForRenewal(ctx context.Context, withinSeconds float64) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsDueForRenewal, withinSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.TLD,
			&i.TlsEnabled,
			&i.CertMode,
			&i.AcmeDirectory,
			&i.AcmeEmail,
			&i.AcmeCredentials,
			&i.AcmeAccountKey,
			&i.CertObjectKey,
			&i.KeyObjectKey,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.CertError,
			&i.CertIssuedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainAccountKey = `-- name: SetDomainAccountKey :exec
UPDATE domains
SET acme_account_key = $2,
    updated_at       = now()
WHERE id = $1
`

type SetDomainAccountKeyParams struct {
	ID             pgtype.UUID
	AcmeAccountKey string
}

func (q *Queries) SetDomainAccountKey(ctx context.Context, arg SetDomainAccountKeyParams) error {
	_, err := q.db.Exec(ctx, setDomainAccountKey, arg.ID, arg.AcmeAccountKey)
	return err
}

const setDomainCertError = `-- name: SetDomainCertError :exec
UPDATE domains
SET cert_error = $2,
    updated_at = now()
WHERE id = $1
`

type SetDomainCertErrorParams struct {
	ID        pgtype.UUID
	CertError string
}

func (q *Queries) SetDomainCertError(ctx context.Context, arg SetDomainCertErrorParams) error {
	_, err := q.db.Exec(ctx, setDomainCertError, arg.ID, arg.CertError)
	return err
}

const updateDomainCert = `-- name: UpdateDomainCert :one
UPDATE domains
SET cert_object_key  = $2,
    key_object_key   = $3,
    cert_fingerprint = $4,
    cert_not_after   = $5,
    cert_issued_at   = now(),
    cert_error       = '',
    updated_at       = now()
WHERE id = $1
RETURNING id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at
`

type UpdateDomainCertParams struct {
	ID              pgtype.UUID
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
}

func (q *Queries) UpdateDomainCert(ctx context.Context, arg UpdateDomainCertParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainCert,
		arg.ID,
		arg.CertObjectKey,
		arg.KeyObjectKey,
		arg.CertFingerprint,
		arg.CertNotAfter,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainTLS = `-- name: UpdateDomainTLS :one
UPDATE domains
SET tls_enabled      = $2,
    cert_mode        = $3,
    acme_directory   = $4,
    acme_email       = $5,
    acme_credentials = COALESCE(NULLIF($6::text, ''), acme_credentials),
    updated_at       = now()
WHERE id = $1
RETURNING id, tld, tls_enabled, cert_mode, acme_directory, acme_email, acme_credentials, acme_account_key, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_error, cert_issued_at, updated_at
`

type UpdateDomainTLSParams struct {
	ID              pgtype.UUID
	TlsEnabled      bool
	CertMode        string
	AcmeDirectory   string
	AcmeEmail       string
	AcmeCredentials string
}

func (q *Queries) UpdateDomainTLS(ctx context.Context, arg UpdateDomainTLSParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainTLS,
		arg.ID,
		arg.TlsEnabled,
		arg.CertMode,
		arg.AcmeDirectory,
		arg.AcmeEmail,
		arg.AcmeCredentials,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.TLD,
		&i.TlsEnabled,
		&i.CertMode,
		&i.AcmeDirectory,
		&i.AcmeEmail,
		&i.AcmeCredentials,
		&i.AcmeAccountKey,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertError,
		&i.CertIssuedAt,
		&i.UpdatedAt,
	)
	return i, err
}
