// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachIntegrationToVM = `-- name: AttachIntegrationToVM :exec
INSERT INTO vm_integrations (vm_id, integration_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachIntegrationToVMParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
}

func (q *Queries) AttachIntegrationToVM(ctx context.Context, arg AttachIntegrationToVMParams) error {
	_, err := q.db.Exec(ctx, attachIntegrationToVM, arg.VMID, arg.IntegrationID)
	return err
}

const countVMIntegrationRepos = `-- name: CountVMIntegrationRepos :one
SELECT count(*) FROM vm_integration_repos
WHERE vm_id = $1 AND integration_id = $2
`

type CountVMIntegrationReposParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
}

func (q *Queries) CountVMIntegrationRepos(ctx context.Context, arg CountVMIntegrationReposParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVMIntegrationRepos, arg.VMID, arg.IntegrationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGitHubInstallState = `-- name: CreateGitHubInstallState :exec
INSERT INTO github_install_states (state_hash, owner_id, integration_id)
VALUES ($1, $2, $3)
`

type CreateGitHubInstallStateParams struct {
	StateHash     string
	OwnerID       pgtype.UUID
	IntegrationID pgtype.UUID
}

func (q *Queries) CreateGitHubInstallState(ctx context.Context, arg CreateGitHubInstallStateParams) error {
	_, err := q.db.Exec(ctx, createGitHubInstallState, arg.StateHash, arg.OwnerID, arg.IntegrationID)
	return err
}

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (owner_id, name, kind, readonly)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, kind, installation_pk, all_repos, readonly, created_at, updated_at
`

type CreateIntegrationParams struct {
	OwnerID  pgtype.UUID
	Name     string
	Kind     string
	Readonly bool
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.OwnerID,
		arg.Name,
		arg.Kind,
		arg.Readonly,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.InstallationPk,
		&i.AllRepos,
		&i.Readonly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredGitHubInstallStates = `-- name: DeleteExpiredGitHubInstallStates :exec
DELETE FROM github_install_states
WHERE created_at < now() - make_interval(secs => $1::float)
`

func (q *Queries) DeleteExpiredGitHubInstallStates(ctx context.Context, withinSeconds float64) error {
	_, err := q.db.Exec(ctx, deleteExpiredGitHubInstallStates, withinSeconds)
	return err
}

const deleteGitHubApp = `-- name: DeleteGitHubApp :exec
DELETE FROM github_apps
WHERE id = $1
`

func (q *Queries) DeleteGitHubApp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitHubApp, id)
	return err
}

const deleteIntegrationForOwner = `-- name: DeleteIntegrationForOwner :exec
DELETE FROM integrations
WHERE id = $1 AND owner_id = $2
`

type DeleteIntegrationForOwnerParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteIntegrationForOwner(ctx context.Context, arg DeleteIntegrationForOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationForOwner, arg.ID, arg.OwnerID)
	return err
}

const deleteIntegrationRepos = `-- name: DeleteIntegrationRepos :exec
DELETE FROM integration_repos
WHERE integration_id = $1
`

func (q *Queries) DeleteIntegrationRepos(ctx context.Context, integrationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegrationRepos, integrationID)
	return err
}

const deleteOtherGitHubApps = `-- name: DeleteOtherGitHubApps :exec
DELETE FROM github_apps
WHERE id <> $1
`

// One app per control plane. Replacing it leaves the old row unreachable, and
// its installations along with it, so they go too.
func (q *Queries) DeleteOtherGitHubApps(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOtherGitHubApps, id)
	return err
}

const deleteVMIntegrationRepos = `-- name: DeleteVMIntegrationRepos :exec
DELETE FROM vm_integration_repos
WHERE vm_id = $1 AND integration_id = $2
`

type DeleteVMIntegrationReposParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
}

func (q *Queries) DeleteVMIntegrationRepos(ctx context.Context, arg DeleteVMIntegrationReposParams) error {
	_, err := q.db.Exec(ctx, deleteVMIntegrationRepos, arg.VMID, arg.IntegrationID)
	return err
}

const detachIntegrationFromVM = `-- name: DetachIntegrationFromVM :exec
DELETE FROM vm_integrations
WHERE vm_id = $1 AND integration_id = $2
`

type DetachIntegrationFromVMParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
}

func (q *Queries) DetachIntegrationFromVM(ctx context.Context, arg DetachIntegrationFromVMParams) error {
	_, err := q.db.Exec(ctx, detachIntegrationFromVM, arg.VMID, arg.IntegrationID)
	return err
}

const findIntegrationRepo = `-- name: FindIntegrationRepo :one
SELECT repo_owner, repo_name FROM integration_repos
WHERE integration_id = $1
  AND lower(repo_owner) = lower($2::text)
  AND lower(repo_name) = lower($3::text)
`

type FindIntegrationRepoParams struct {
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

type FindIntegrationRepoRow struct {
	RepoOwner string
	RepoName  string
}

// Case-insensitive, because github is: codingcoffee/x and codingCoffee/x are
// the same repository. Returns the stored spelling so the minted token names
// the repository the way github does.
func (q *Queries) FindIntegrationRepo(ctx context.Context, arg FindIntegrationRepoParams) (FindIntegrationRepoRow, error) {
	row := q.db.QueryRow(ctx, findIntegrationRepo, arg.IntegrationID, arg.RepoOwner, arg.RepoName)
	var i FindIntegrationRepoRow
	err := row.Scan(&i.RepoOwner, &i.RepoName)
	return i, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
SELECT id, app_id, slug, name, private_key, created_at, updated_at FROM github_apps
ORDER BY updated_at DESC
LIMIT 1
`

// Most recently saved wins: correcting a mistyped app id inserts a new row
// rather than updating the old one, and the correction has to be the one used.
func (q *Queries) GetGitHubApp(ctx context.Context) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubApp)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT id, app_pk, installation_id, account_login, account_type, repository_selection, installed_by, suspended, last_error, created_at, updated_at FROM github_installations
WHERE id = $1
`

func (q *Queries) GetGitHubInstallation(ctx context.Context, id pgtype.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, id)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.AppPk,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.InstalledBy,
		&i.Suspended,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByNameForOwner = `-- name: GetIntegrationByNameForOwner :one
SELECT id, owner_id, name, kind, installation_pk, all_repos, readonly, created_at, updated_at FROM integrations
WHERE owner_id = $1 AND name = $2
`

type GetIntegrationByNameForOwnerParams struct {
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) GetIntegrationByNameForOwner(ctx context.Context, arg GetIntegrationByNameForOwnerParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByNameForOwner, arg.OwnerID, arg.Name)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.InstallationPk,
		&i.AllRepos,
		&i.Readonly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationForOwner = `-- name: GetIntegrationForOwner :one
SELECT i.id, i.owner_id, i.name, i.kind, i.installation_pk, i.all_repos, i.readonly, i.created_at, i.updated_at,
       gi.account_login,
       gi.suspended,
       gi.repository_selection,
       gi.installation_id
FROM integrations i
LEFT JOIN github_installations gi ON gi.id = i.installation_pk
WHERE i.id = $1 AND i.owner_id = $2
`

type GetIntegrationForOwnerParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

type GetIntegrationForOwnerRow struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Name                string
	Kind                string
	InstallationPk      pgtype.UUID
	AllRepos            bool
	Readonly            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	AccountLogin        pgtype.Text
	Suspended           pgtype.Bool
	RepositorySelection pgtype.Text
	InstallationID      pgtype.Int8
}

func (q *Queries) GetIntegrationForOwner(ctx context.Context, arg GetIntegrationForOwnerParams) (GetIntegrationForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationForOwner, arg.ID, arg.OwnerID)
	var i GetIntegrationForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.InstallationPk,
		&i.AllRepos,
		&i.Readonly,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountLogin,
		&i.Suspended,
		&i.RepositorySelection,
		&i.InstallationID,
	)
	return i, err
}

const insertIntegrationRepo = `-- name: InsertIntegrationRepo :exec
INSERT INTO integration_repos (integration_id, repo_owner, repo_name)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertIntegrationRepoParams struct {
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

func (q *Queries) InsertIntegrationRepo(ctx context.Context, arg InsertIntegrationRepoParams) error {
	_, err := q.db.Exec(ctx, insertIntegrationRepo, arg.IntegrationID, arg.RepoOwner, arg.RepoName)
	return err
}

const insertVMIntegrationRepo = `-- name: InsertVMIntegrationRepo :exec
INSERT INTO vm_integration_repos (vm_id, integration_id, repo_owner, repo_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertVMIntegrationRepoParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

func (q *Queries) InsertVMIntegrationRepo(ctx context.Context, arg InsertVMIntegrationRepoParams) error {
	_, err := q.db.Exec(ctx, insertVMIntegrationRepo,
		arg.VMID,
		arg.IntegrationID,
		arg.RepoOwner,
		arg.RepoName,
	)
	return err
}

const listClientIDsWithIntegrations = `-- name: ListClientIDsWithIntegrations :many
SELECT DISTINCT v.client_id
FROM vm_integrations vi
JOIN vms v ON v.id = vi.vm_id
WHERE vi.integration_id = $1
`

func (q *Queries) ListClientIDsWithIntegrations(ctx context.Context, integrationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listClientIDsWithIntegrations, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var client_id pgtype.UUID
		if err := rows.Scan(&client_id); err != nil {
			return nil, err
		}
		items = append(items, client_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubInstallationsByOwner = `-- name: ListGitHubInstallationsByOwner :many
SELECT gi.id, gi.app_pk, gi.installation_id, gi.account_login, gi.account_type, gi.repository_selection, gi.installed_by, gi.suspended, gi.last_error, gi.created_at, gi.updated_at FROM github_installations gi
WHERE gi.installed_by = $1
ORDER BY gi.account_login
`

func (q *Queries) ListGitHubInstallationsByOwner(ctx context.Context, installedBy pgtype.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallationsByOwner, installedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.AppPk,
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.RepositorySelection,
			&i.InstalledBy,
			&i.Suspended,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationGrantsForVM = `-- name: ListIntegrationGrantsForVM :many
SELECT i.id            AS integration_id,
       i.name          AS integration_name,
       i.all_repos,
       i.readonly,
       gi.id           AS installation_pk,
       gi.installation_id,
       gi.account_login,
       gi.suspended,
       ga.app_id,
       ga.private_key,
       v.id            AS vm_pk,
       v.name          AS vm_name
FROM vms v
JOIN vm_integrations vi ON vi.vm_id = v.id
JOIN integrations i ON i.id = vi.integration_id AND i.kind = $1
JOIN github_installations gi ON gi.id = i.installation_pk
JOIN github_apps ga ON ga.id = gi.app_pk
WHERE v.client_id = $2
  AND v.ip = $3
ORDER BY i.name
`

type ListIntegrationGrantsForVMParams struct {
	Kind     string
	ClientID pgtype.UUID
	VMIP     string
}

type ListIntegrationGrantsForVMRow struct {
	IntegrationID   pgtype.UUID
	IntegrationName string
	AllRepos        bool
	Readonly        bool
	InstallationPk  pgtype.UUID
	InstallationID  int64
	AccountLogin    string
	Suspended       bool
	AppID           int64
	PrivateKey      string
	VmPk            pgtype.UUID
	VMName          string
}

// The broker's authorization query. v.client_id = $1 is the load-bearing
// predicate: the client id comes from the calling host's own authenticated
// token, never from the request, so a host cannot mint a token for a vm that
// lives somewhere else.
func (q *Queries) ListIntegrationGrantsForVM(ctx context.Context, arg ListIntegrationGrantsForVMParams) ([]ListIntegrationGrantsForVMRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationGrantsForVM, arg.Kind, arg.ClientID, arg.VMIP)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationGrantsForVMRow
	for rows.Next() {
		var i ListIntegrationGrantsForVMRow
		if err := rows.Scan(
			&i.IntegrationID,
			&i.IntegrationName,
			&i.AllRepos,
			&i.Readonly,
			&i.InstallationPk,
			&i.InstallationID,
			&i.AccountLogin,
			&i.Suspended,
			&i.AppID,
			&i.PrivateKey,
			&i.VmPk,
			&i.VMName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationRepos = `-- name: ListIntegrationRepos :many
SELECT repo_owner, repo_name FROM integration_repos
WHERE integration_id = $1
ORDER BY repo_owner, repo_name
`

type ListIntegrationReposRow struct {
	RepoOwner string
	RepoName  string
}

func (q *Queries) ListIntegrationRepos(ctx context.Context, integrationID pgtype.UUID) ([]ListIntegrationReposRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationRepos, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationReposRow
	for rows.Next() {
		var i ListIntegrationReposRow
		if err := rows.Scan(&i.RepoOwner, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationReposForVM = `-- name: ListIntegrationReposForVM :many
SELECT DISTINCT r.repo_owner, r.repo_name
FROM vm_integrations vi
JOIN integration_repos r ON r.integration_id = vi.integration_id
WHERE vi.vm_id = $1
ORDER BY r.repo_owner, r.repo_name
`

type ListIntegrationReposForVMRow struct {
	RepoOwner string
	RepoName  string
}

func (q *Queries) ListIntegrationReposForVM(ctx context.Context, vmID pgtype.UUID) ([]ListIntegrationReposForVMRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationReposForVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationReposForVMRow
	for rows.Next() {
		var i ListIntegrationReposForVMRow
		if err := rows.Scan(&i.RepoOwner, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationVMs = `-- name: ListIntegrationVMs :many
SELECT v.id, v.name, v.ip, v.client_id
FROM vm_integrations vi
JOIN vms v ON v.id = vi.vm_id
WHERE vi.integration_id = $1
ORDER BY v.name
`

type ListIntegrationVMsRow struct {
	ID       pgtype.UUID
	Name     string
	IP       string
	ClientID pgtype.UUID
}

func (q *Queries) ListIntegrationVMs(ctx context.Context, integrationID pgtype.UUID) ([]ListIntegrationVMsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationVMs, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationVMsRow
	for rows.Next() {
		var i ListIntegrationVMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IP,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByOwner = `-- name: ListIntegrationsByOwner :many
SELECT i.id, i.owner_id, i.name, i.kind, i.installation_pk, i.all_repos, i.readonly, i.created_at, i.updated_at,
       gi.account_login,
       gi.suspended,
       gi.repository_selection,
       (SELECT count(*) FROM integration_repos r WHERE r.integration_id = i.id) AS repo_count,
       (SELECT count(*) FROM vm_integrations v WHERE v.integration_id = i.id)   AS vm_count
FROM integrations i
LEFT JOIN github_installations gi ON gi.id = i.installation_pk
WHERE i.owner_id = $1
ORDER BY i.name
`

type ListIntegrationsByOwnerRow struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Name                string
	Kind                string
	InstallationPk      pgtype.UUID
	AllRepos            bool
	Readonly            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	AccountLogin        pgtype.Text
	Suspended           pgtype.Bool
	RepositorySelection pgtype.Text
	RepoCount           int64
	VmCount             int64
}

func (q *Queries) ListIntegrationsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListIntegrationsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationsByOwnerRow
	for rows.Next() {
		var i ListIntegrationsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Kind,
			&i.InstallationPk,
			&i.AllRepos,
			&i.Readonly,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountLogin,
			&i.Suspended,
			&i.RepositorySelection,
			&i.RepoCount,
			&i.VmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMIntegrationRepos = `-- name: ListVMIntegrationRepos :many
SELECT repo_owner, repo_name FROM vm_integration_repos
WHERE vm_id = $1 AND integration_id = $2
ORDER BY repo_owner, repo_name
`

type ListVMIntegrationReposParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
}

type ListVMIntegrationReposRow struct {
	RepoOwner string
	RepoName  string
}

func (q *Queries) ListVMIntegrationRepos(ctx context.Context, arg ListVMIntegrationReposParams) ([]ListVMIntegrationReposRow, error) {
	rows, err := q.db.Query(ctx, listVMIntegrationRepos, arg.VMID, arg.IntegrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVMIntegrationReposRow
	for rows.Next() {
		var i ListVMIntegrationReposRow
		if err := rows.Scan(&i.RepoOwner, &i.RepoName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMIntegrationsForOwner = `-- name: ListVMIntegrationsForOwner :many
SELECT i.id, i.name, i.readonly, i.all_repos
FROM vm_integrations vi
JOIN integrations i ON i.id = vi.integration_id
WHERE vi.vm_id = $1 AND i.owner_id = $2
ORDER BY i.name
`

type ListVMIntegrationsForOwnerParams struct {
	VMID    pgtype.UUID
	OwnerID pgtype.UUID
}

type ListVMIntegrationsForOwnerRow struct {
	ID       pgtype.UUID
	Name     string
	Readonly bool
	AllRepos bool
}

func (q *Queries) ListVMIntegrationsForOwner(ctx context.Context, arg ListVMIntegrationsForOwnerParams) ([]ListVMIntegrationsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listVMIntegrationsForOwner, arg.VMID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVMIntegrationsForOwnerRow
	for rows.Next() {
		var i ListVMIntegrationsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Readonly,
			&i.AllRepos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstallationSuspended = `-- name: SetInstallationSuspended :exec
UPDATE github_installations
SET suspended  = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1
`

type SetInstallationSuspendedParams struct {
	ID        pgtype.UUID
	Suspended bool
	LastError string
}

func (q *Queries) SetInstallationSuspended(ctx context.Context, arg SetInstallationSuspendedParams) error {
	_, err := q.db.Exec(ctx, setInstallationSuspended, arg.ID, arg.Suspended, arg.LastError)
	return err
}

const setIntegrationInstallation = `-- name: SetIntegrationInstallation :exec
UPDATE integrations
SET installation_pk = $2,
    updated_at      = now()
WHERE id = $1
`

type SetIntegrationInstallationParams struct {
	ID             pgtype.UUID
	InstallationPk pgtype.UUID
}

func (q *Queries) SetIntegrationInstallation(ctx context.Context, arg SetIntegrationInstallationParams) error {
	_, err := q.db.Exec(ctx, setIntegrationInstallation, arg.ID, arg.InstallationPk)
	return err
}

const takeGitHubInstallState = `-- name: TakeGitHubInstallState :one
DELETE FROM github_install_states
WHERE state_hash = $1
  AND created_at > now() - make_interval(secs => $2::float)
RETURNING owner_id, integration_id
`

type TakeGitHubInstallStateParams struct {
	StateHash     string
	WithinSeconds float64
}

type TakeGitHubInstallStateRow struct {
	OwnerID       pgtype.UUID
	IntegrationID pgtype.UUID
}

// Single use, and expired rows are never returned: a state is only good for the
// redirect it was minted for.
func (q *Queries) TakeGitHubInstallState(ctx context.Context, arg TakeGitHubInstallStateParams) (TakeGitHubInstallStateRow, error) {
	row := q.db.QueryRow(ctx, takeGitHubInstallState, arg.StateHash, arg.WithinSeconds)
	var i TakeGitHubInstallStateRow
	err := row.Scan(&i.OwnerID, &i.IntegrationID)
	return i, err
}

const updateIntegrationFlags = `-- name: UpdateIntegrationFlags :one
UPDATE integrations
SET all_repos  = $2,
    readonly   = $3,
    updated_at = now()
WHERE id = $1 AND owner_id = $4
RETURNING id, owner_id, name, kind, installation_pk, all_repos, readonly, created_at, updated_at
`

type UpdateIntegrationFlagsParams struct {
	ID       pgtype.UUID
	AllRepos bool
	Readonly bool
	OwnerID  pgtype.UUID
}

func (q *Queries) UpdateIntegrationFlags(ctx context.Context, arg UpdateIntegrationFlagsParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationFlags,
		arg.ID,
		arg.AllRepos,
		arg.Readonly,
		arg.OwnerID,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.InstallationPk,
		&i.AllRepos,
		&i.Readonly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubApp = `-- name: UpsertGitHubApp :one
INSERT INTO github_apps (app_id, slug, name, private_key)
VALUES ($1, $2, $3, $4)
ON CONFLICT (app_id) DO UPDATE
SET slug        = EXCLUDED.slug,
    name        = EXCLUDED.name,
    private_key = COALESCE(NULLIF(EXCLUDED.private_key, ''), github_apps.private_key),
    updated_at  = now()
RETURNING id, app_id, slug, name, private_key, created_at, updated_at
`

type UpsertGitHubAppParams struct {
	AppID      int64
	Slug       string
	Name       string
	PrivateKey string
}

func (q *Queries) UpsertGitHubApp(ctx context.Context, arg UpsertGitHubAppParams) (GithubApp, error) {
	row := q.db.QueryRow(ctx, upsertGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.Name,
		arg.PrivateKey,
	)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubInstallation = `-- name: UpsertGitHubInstallation :one
INSERT INTO github_installations (
    app_pk, installation_id, account_login, account_type, repository_selection, installed_by
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (app_pk, installation_id) DO UPDATE
SET account_login        = EXCLUDED.account_login,
    account_type         = EXCLUDED.account_type,
    repository_selection = EXCLUDED.repository_selection,
    suspended            = false,
    last_error           = '',
    updated_at           = now()
RETURNING id, app_pk, installation_id, account_login, account_type, repository_selection, installed_by, suspended, last_error, created_at, updated_at
`

type UpsertGitHubInstallationParams struct {
	AppPk               pgtype.UUID
	InstallationID      int64
	AccountLogin        string
	AccountType         string
	RepositorySelection string
	InstalledBy         pgtype.UUID
}

func (q *Queries) UpsertGitHubInstallation(ctx context.Context, arg UpsertGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGitHubInstallation,
		arg.AppPk,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
		arg.InstalledBy,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.AppPk,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.InstalledBy,
		&i.Suspended,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const vMIntegrationAllowsRepo = `-- name: VMIntegrationAllowsRepo :one
SELECT (
    NOT EXISTS (
        SELECT 1 FROM vm_integration_repos scope
        WHERE scope.vm_id = $1
          AND scope.integration_id = $2
    )
    OR EXISTS (
        SELECT 1 FROM vm_integration_repos hit
        WHERE hit.vm_id = $1
          AND hit.integration_id = $2
          AND lower(hit.repo_owner) = lower($3::text)
          AND lower(hit.repo_name) = lower($4::text)
    )
)::boolean
`

type VMIntegrationAllowsRepoParams struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

// An attachment with no scoping rows inherits the integration's whole list;
// one with them is limited to exactly those.
func (q *Queries) VMIntegrationAllowsRepo(ctx context.Context, arg VMIntegrationAllowsRepoParams) (bool, error) {
	row := q.db.QueryRow(ctx, vMIntegrationAllowsRepo,
		arg.VMID,
		arg.IntegrationID,
		arg.RepoOwner,
		arg.RepoName,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
