// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kernels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countKernels = `-- name: CountKernels :one
SELECT count(*) FROM kernels
WHERE soft_deleted_at IS NULL
`

func (q *Queries) CountKernels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKernels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWithdrawnKernels = `-- name: CountWithdrawnKernels :one
SELECT count(*) FROM kernels
WHERE soft_deleted_at IS NOT NULL
`

func (q *Queries) CountWithdrawnKernels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawnKernels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKernel = `-- name: CreateKernel :one
INSERT INTO kernels (name, description, object_key, file_name, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

type CreateKernelParams struct {
	Name        string
	Description string
	ObjectKey   string
	FileName    string
	SizeBytes   int64
}

func (q *Queries) CreateKernel(ctx context.Context, arg CreateKernelParams) (Kernel, error) {
	row := q.db.QueryRow(ctx, createKernel,
		arg.Name,
		arg.Description,
		arg.ObjectKey,
		arg.FileName,
		arg.SizeBytes,
	)
	var i Kernel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const getKernel = `-- name: GetKernel :one
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at FROM kernels
WHERE id = $1
`

func (q *Queries) GetKernel(ctx context.Context, id pgtype.UUID) (Kernel, error) {
	row := q.db.QueryRow(ctx, getKernel, id)
	var i Kernel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const listKernelObjects = `-- name: ListKernelObjects :many
SELECT id, name, object_key, file_name, soft_deleted_at FROM kernels
ORDER BY created_at DESC
`

type ListKernelObjectsRow struct {
	ID            pgtype.UUID
	Name          string
	ObjectKey     string
	FileName      string
	SoftDeletedAt pgtype.Timestamptz
}

// Every kernel that has bytes in the bucket, withdrawn ones included, for
// naming what a host is holding in its image cache.
func (q *Queries) ListKernelObjects(ctx context.Context) ([]ListKernelObjectsRow, error) {
	rows, err := q.db.Query(ctx, listKernelObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKernelObjectsRow
	for rows.Next() {
		var i ListKernelObjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ObjectKey,
			&i.FileName,
			&i.SoftDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKernels = `-- name: ListKernels :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at FROM kernels
WHERE soft_deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListKernelsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListKernels(ctx context.Context, arg ListKernelsParams) ([]Kernel, error) {
	rows, err := q.db.Query(ctx, listKernels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kernel
	for rows.Next() {
		var i Kernel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnKernels = `-- name: ListWithdrawnKernels :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at FROM kernels
WHERE soft_deleted_at IS NOT NULL
ORDER BY soft_deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListWithdrawnKernelsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListWithdrawnKernels(ctx context.Context, arg ListWithdrawnKernelsParams) ([]Kernel, error) {
	rows, err := q.db.Query(ctx, listWithdrawnKernels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kernel
	for rows.Next() {
		var i Kernel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeKernel = `-- name: PurgeKernel :one
DELETE FROM kernels
WHERE id = $1 AND soft_deleted_at IS NOT NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

// Only a withdrawn kernel can go: the row is dropped for good so its name frees
// up, and the caller deletes the object it returns from the bucket.
func (q *Queries) PurgeKernel(ctx context.Context, id pgtype.UUID) (Kernel, error) {
	row := q.db.QueryRow(ctx, purgeKernel, id)
	var i Kernel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const softDeleteKernel = `-- name: SoftDeleteKernel :one
UPDATE kernels
SET soft_deleted_at = now()
WHERE id = $1 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

func (q *Queries) SoftDeleteKernel(ctx context.Context, id pgtype.UUID) (Kernel, error) {
	row := q.db.QueryRow(ctx, softDeleteKernel, id)
	var i Kernel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const updateKernelDescription = `-- name: UpdateKernelDescription :one
UPDATE kernels
SET description = $2
WHERE id = $1 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

type UpdateKernelDescriptionParams struct {
	ID          pgtype.UUID
	Description string
}

func (q *Queries) UpdateKernelDescription(ctx context.Context, arg UpdateKernelDescriptionParams) (Kernel, error) {
	row := q.db.QueryRow(ctx, updateKernelDescription, arg.ID, arg.Description)
	var i Kernel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}
