// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGlobalLLMKey = `-- name: DeleteGlobalLLMKey :execrows
DELETE FROM llm_keys WHERE owner_id IS NULL AND provider = $1
`

func (q *Queries) DeleteGlobalLLMKey(ctx context.Context, provider string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGlobalLLMKey, provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserLLMKey = `-- name: DeleteUserLLMKey :execrows
DELETE FROM llm_keys WHERE owner_id = $1 AND provider = $2
`

type DeleteUserLLMKeyParams struct {
	OwnerID  pgtype.UUID
	Provider string
}

func (q *Queries) DeleteUserLLMKey(ctx context.Context, arg DeleteUserLLMKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserLLMKey, arg.OwnerID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGlobalLLMKey = `-- name: GetGlobalLLMKey :one
SELECT id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by FROM llm_keys WHERE owner_id IS NULL AND provider = $1
`

func (q *Queries) GetGlobalLLMKey(ctx context.Context, provider string) (LlmKey, error) {
	row := q.db.QueryRow(ctx, getGlobalLLMKey, provider)
	var i LlmKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Plan,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserLLMKey = `-- name: GetUserLLMKey :one
SELECT id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by FROM llm_keys WHERE owner_id = $1 AND provider = $2
`

type GetUserLLMKeyParams struct {
	OwnerID  pgtype.UUID
	Provider string
}

func (q *Queries) GetUserLLMKey(ctx context.Context, arg GetUserLLMKeyParams) (LlmKey, error) {
	row := q.db.QueryRow(ctx, getUserLLMKey, arg.OwnerID, arg.Provider)
	var i LlmKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Plan,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listGlobalLLMKeys = `-- name: ListGlobalLLMKeys :many
SELECT id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by FROM llm_keys WHERE owner_id IS NULL ORDER BY provider
`

func (q *Queries) ListGlobalLLMKeys(ctx context.Context) ([]LlmKey, error) {
	rows, err := q.db.Query(ctx, listGlobalLLMKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmKey
	for rows.Next() {
		var i LlmKey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Provider,
			&i.Plan,
			&i.ApiKeyEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMKeysForVM = `-- name: ListLLMKeysForVM :many
SELECT k.id, k.provider, k.plan, k.api_key_enc, k.updated_at,
       (k.owner_id IS NULL)::boolean AS is_global,
       v.id AS vm_pk,
       v.name AS vm_name,
       v.created_by AS vm_owner
FROM vms v
JOIN llm_keys k ON k.owner_id = v.created_by OR k.owner_id IS NULL
WHERE v.client_id = $1
  AND v.ip = $2
ORDER BY is_global, k.provider
`

type ListLLMKeysForVMParams struct {
	ClientID pgtype.UUID
	VMIP     string
}

type ListLLMKeysForVMRow struct {
	ID        pgtype.UUID
	Provider  string
	Plan      string
	ApiKeyEnc []byte
	UpdatedAt pgtype.Timestamptz
	IsGlobal  bool
	VmPk      pgtype.UUID
	VMName    string
	VMOwner   pgtype.UUID
}

// The broker's lookup for llm. As with ListIntegrationGrantsForVM, client_id
// comes from the calling host's own token, so a host only ever names its own
// vms. The owner's keys sort before the global ones.
func (q *Queries) ListLLMKeysForVM(ctx context.Context, arg ListLLMKeysForVMParams) ([]ListLLMKeysForVMRow, error) {
	rows, err := q.db.Query(ctx, listLLMKeysForVM, arg.ClientID, arg.VMIP)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLLMKeysForVMRow
	for rows.Next() {
		var i ListLLMKeysForVMRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Plan,
			&i.ApiKeyEnc,
			&i.UpdatedAt,
			&i.IsGlobal,
			&i.VmPk,
			&i.VMName,
			&i.VMOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMPrices = `-- name: ListLLMPrices :many
SELECT model, input_per_token, output_per_token, cache_read_per_token, cache_write_per_token, updated_at FROM llm_prices
`

func (q *Queries) ListLLMPrices(ctx context.Context) ([]LlmPrice, error) {
	rows, err := q.db.Query(ctx, listLLMPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrice
	for rows.Next() {
		var i LlmPrice
		if err := rows.Scan(
			&i.Model,
			&i.InputPerToken,
			&i.OutputPerToken,
			&i.CacheReadPerToken,
			&i.CacheWritePerToken,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLLMKeys = `-- name: ListUserLLMKeys :many
SELECT id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by FROM llm_keys WHERE owner_id = $1 ORDER BY provider
`

func (q *Queries) ListUserLLMKeys(ctx context.Context, ownerID pgtype.UUID) ([]LlmKey, error) {
	rows, err := q.db.Query(ctx, listUserLLMKeys, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmKey
	for rows.Next() {
		var i LlmKey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Provider,
			&i.Plan,
			&i.ApiKeyEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsernamesByIDs = `-- name: ListUsernamesByIDs :many
SELECT id, username FROM users WHERE id = ANY($1::uuid[])
`

type ListUsernamesByIDsRow struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) ListUsernamesByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListUsernamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUsernamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsernamesByIDsRow
	for rows.Next() {
		var i ListUsernamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalLLMKey = `-- name: UpsertGlobalLLMKey :one
INSERT INTO llm_keys (owner_id, provider, plan, api_key_enc, updated_by)
VALUES (NULL, $1, $2, $3, $4)
ON CONFLICT (provider) WHERE owner_id IS NULL DO UPDATE
SET plan = EXCLUDED.plan, api_key_enc = EXCLUDED.api_key_enc, updated_at = now(), updated_by = EXCLUDED.updated_by
RETURNING id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by
`

type UpsertGlobalLLMKeyParams struct {
	Provider  string
	Plan      string
	ApiKeyEnc []byte
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpsertGlobalLLMKey(ctx context.Context, arg UpsertGlobalLLMKeyParams) (LlmKey, error) {
	row := q.db.QueryRow(ctx, upsertGlobalLLMKey,
		arg.Provider,
		arg.Plan,
		arg.ApiKeyEnc,
		arg.UpdatedBy,
	)
	var i LlmKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Plan,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertLLMPrices = `-- name: UpsertLLMPrices :exec
INSERT INTO llm_prices (model, input_per_token, output_per_token, cache_read_per_token, cache_write_per_token, updated_at)
SELECT unnest($1::text[]),
       unnest($2::float8[]),
       unnest($3::float8[]),
       unnest($4::float8[]),
       unnest($5::float8[]),
       now()
ON CONFLICT (model) DO UPDATE
SET input_per_token = EXCLUDED.input_per_token,
    output_per_token = EXCLUDED.output_per_token,
    cache_read_per_token = EXCLUDED.cache_read_per_token,
    cache_write_per_token = EXCLUDED.cache_write_per_token,
    updated_at = EXCLUDED.updated_at
`

type UpsertLLMPricesParams struct {
	Models      []string
	Inputs      []float64
	Outputs     []float64
	CacheReads  []float64
	CacheWrites []float64
}

func (q *Queries) UpsertLLMPrices(ctx context.Context, arg UpsertLLMPricesParams) error {
	_, err := q.db.Exec(ctx, upsertLLMPrices,
		arg.Models,
		arg.Inputs,
		arg.Outputs,
		arg.CacheReads,
		arg.CacheWrites,
	)
	return err
}

const upsertUserLLMKey = `-- name: UpsertUserLLMKey :one
INSERT INTO llm_keys (owner_id, provider, plan, api_key_enc, updated_by)
VALUES ($1, $2, $3, $4, $1)
ON CONFLICT (owner_id, provider) WHERE owner_id IS NOT NULL DO UPDATE
SET plan = EXCLUDED.plan, api_key_enc = EXCLUDED.api_key_enc, updated_at = now(), updated_by = EXCLUDED.updated_by
RETURNING id, owner_id, provider, plan, api_key_enc, created_at, updated_at, updated_by
`

type UpsertUserLLMKeyParams struct {
	OwnerID   pgtype.UUID
	Provider  string
	Plan      string
	ApiKeyEnc []byte
}

func (q *Queries) UpsertUserLLMKey(ctx context.Context, arg UpsertUserLLMKeyParams) (LlmKey, error) {
	row := q.db.QueryRow(ctx, upsertUserLLMKey,
		arg.OwnerID,
		arg.Provider,
		arg.Plan,
		arg.ApiKeyEnc,
	)
	var i LlmKey
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Plan,
		&i.ApiKeyEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
