// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                       pgtype.UUID
	MachineID                string
	Hostname                 string
	TokenHash                string
	Status                   string
	OS                       string
	OSVersion                string
	Arch                     string
	ClientVersion            string
	LastSeenAt               pgtype.Timestamptz
	LastIP                   string
	EnrolledKeyID            pgtype.UUID
	Revoked                  bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	CPUCount                 int32
	CPUPercent               float64
	Load1                    float64
	Load5                    float64
	Load15                   float64
	MemTotalBytes            int64
	MemUsedBytes             int64
	DiskTotalBytes           int64
	DiskUsedBytes            int64
	UptimeSeconds            int64
	MetricsAt                pgtype.Timestamptz
	DomainID                 pgtype.UUID
	DclientVersion           string
	DclientDownloadURL       string
	DpipeVersion             string
	DpipeDownloadURL         string
	ProxyVersion             string
	ProxyDownloadURL         string
	DpipeInstalledVersion    string
	ProxyInstalledVersion    string
	DinitVersion             string
	DinitDownloadURL         string
	DinitInstalledVersion    string
	IntproxyVersion          string
	IntproxyDownloadURL      string
	IntproxyInstalledVersion string
}

type ClientEnrollmentKey struct {
	ID        pgtype.UUID
	KeyHash   string
	KeyPrefix string
	Label     string
	MaxUses   pgtype.Int4
	Uses      int32
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ControlMetum struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

type CustomDomainCert struct {
	ID              pgtype.UUID
	Domain          string
	OwnerID         pgtype.UUID
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
	CertIssuedAt    pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Domain struct {
	ID              pgtype.UUID
	TLD             string
	TlsEnabled      bool
	CertMode        string
	AcmeDirectory   string
	AcmeEmail       string
	AcmeCredentials string
	AcmeAccountKey  string
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
	CertError       string
	CertIssuedAt    pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type GithubApp struct {
	ID         pgtype.UUID
	AppID      int64
	Slug       string
	Name       string
	PrivateKey string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type GithubInstallState struct {
	StateHash     string
	OwnerID       pgtype.UUID
	IntegrationID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type GithubInstallation struct {
	ID                  pgtype.UUID
	AppPk               pgtype.UUID
	InstallationID      int64
	AccountLogin        string
	AccountType         string
	RepositorySelection string
	InstalledBy         pgtype.UUID
	Suspended           bool
	LastError           string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Integration struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	Name           string
	Kind           string
	InstallationPk pgtype.UUID
	AllRepos       bool
	Readonly       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IntegrationRepo struct {
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

type Kernel struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	ObjectKey     string
	FileName      string
	SizeBytes     int64
	CreatedAt     pgtype.Timestamptz
	SoftDeletedAt pgtype.Timestamptz
}

type OidcIdentity struct {
	ProviderID pgtype.UUID
	Subject    string
	UserID     pgtype.UUID
	Email      string
	CreatedAt  pgtype.Timestamptz
	LastLogin  pgtype.Timestamptz
}

type OidcProvider struct {
	ID           pgtype.UUID
	Slug         string
	DisplayName  string
	Issuer       string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Osimage struct {
	ID                 pgtype.UUID
	Name               string
	Description        string
	ObjectKey          string
	FileName           string
	SizeBytes          int64
	CreatedAt          pgtype.Timestamptz
	SoftDeletedAt      pgtype.Timestamptz
	Source             string
	OCIRef             string
	OCIDigest          string
	Status             string
	StatusDetail       string
	ConfigUser         string
	ConfigEntrypoint   []string
	ConfigCmd          []string
	ConfigEnv          []string
	ConfigExposedPorts []int32
	DefaultPort        pgtype.Int4
	CreatedBy          pgtype.UUID
}

type PersonalAccessToken struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	TokenHash   string
	TokenPrefix string
	Label       string
	ExpiresAt   pgtype.Timestamptz
	Revoked     bool
	LastUsedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	UserAgent string
	IP        string
	CreatedAt pgtype.Timestamptz
}

type ScheduledTask struct {
	ID          pgtype.UUID
	Kind        string
	SubjectKind string
	SubjectID   pgtype.UUID
	Payload     []byte
	Status      string
	RunAt       pgtype.Timestamptz
	Attempts    int32
	MaxAttempts int32
	Detail      string
	Reason      string
	CreatedBy   pgtype.UUID
	LockedBy    string
	LockedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type Setting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.UUID
}

type User struct {
	ID             pgtype.UUID
	Username       string
	Email          string
	PasswordHash   string
	FirstName      string
	LastName       string
	UserType       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	VCPULimit      int32
	MemoryLimitMiB int32
	DiskLimitMiB   int32
	PublicKey      string
}

type Vm struct {
	ID          pgtype.UUID
	ClientID    pgtype.UUID
	VMID        string
	Name        string
	Status      string
	Boot        string
	CPUs        int32
	MemoryMiB   int32
	IP          string
	Spec        []byte
	LastError   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	ReportedAt  pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	DiskMiB     int32
	DefaultPort int32
	PublicPorts []int32
	RdpNonce    string
	DefaultUser string
}

type VmCustomDomain struct {
	ID              pgtype.UUID
	VMID            pgtype.UUID
	Domain          string
	Status          string
	LastError       string
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
	CertIssuedAt    pgtype.Timestamptz
	OrderedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type VmIntegration struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type VmIntegrationRepo struct {
	VMID          pgtype.UUID
	IntegrationID pgtype.UUID
	RepoOwner     string
	RepoName      string
}

type VmNetworkTarget struct {
	ID          pgtype.UUID
	VMID        pgtype.UUID
	Kind        string
	Destination string
	Transport   string
	Ports       string
	Note        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
