// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOIDCProviderSecret = `-- name: ClearOIDCProviderSecret :one
UPDATE oidc_providers
SET client_secret = '',
    updated_at    = now()
WHERE id = $1
RETURNING id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at
`

func (q *Queries) ClearOIDCProviderSecret(ctx context.Context, id pgtype.UUID) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, clearOIDCProviderSecret, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFederatedUser = `-- name: CreateFederatedUser :one
INSERT INTO users (username, email, first_name, last_name, user_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, first_name, last_name, user_type, created_at, updated_at, vcpu_limit, memory_limit_mib, disk_limit_mib, public_key
`

type CreateFederatedUserParams struct {
	Username  string
	Email     string
	FirstName string
	LastName  string
	UserType  string
}

func (q *Queries) CreateFederatedUser(ctx context.Context, arg CreateFederatedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createFederatedUser,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VCPULimit,
		&i.MemoryLimitMiB,
		&i.DiskLimitMiB,
		&i.PublicKey,
	)
	return i, err
}

const createOIDCProvider = `-- name: CreateOIDCProvider :one
INSERT INTO oidc_providers (slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at
`

type CreateOIDCProviderParams struct {
	Slug         string
	DisplayName  string
	Issuer       string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
}

func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, createOIDCProvider,
		arg.Slug,
		arg.DisplayName,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowSignup,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers
WHERE id = $1
`

func (q *Queries) DeleteOIDCProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCProvider, id)
	return err
}

const getOIDCIdentity = `-- name: GetOIDCIdentity :one
SELECT provider_id, subject, user_id, email, created_at, last_login FROM oidc_identities
WHERE provider_id = $1 AND subject = $2
`

type GetOIDCIdentityParams struct {
	ProviderID pgtype.UUID
	Subject    string
}

func (q *Queries) GetOIDCIdentity(ctx context.Context, arg GetOIDCIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRow(ctx, getOIDCIdentity, arg.ProviderID, arg.Subject)
	var i OidcIdentity
	err := row.Scan(
		&i.ProviderID,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getOIDCProvider = `-- name: GetOIDCProvider :one
SELECT id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at FROM oidc_providers
WHERE id = $1
`

func (q *Queries) GetOIDCProvider(ctx context.Context, id pgtype.UUID) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProvider, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCProviderBySlug = `-- name: GetOIDCProviderBySlug :one
SELECT id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at FROM oidc_providers
WHERE slug = $1
`

func (q *Queries) GetOIDCProviderBySlug(ctx context.Context, slug string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProviderBySlug, slug)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, first_name, last_name, user_type, created_at, updated_at, vcpu_limit, memory_limit_mib, disk_limit_mib, public_key FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VCPULimit,
		&i.MemoryLimitMiB,
		&i.DiskLimitMiB,
		&i.PublicKey,
	)
	return i, err
}

const linkOIDCIdentity = `-- name: LinkOIDCIdentity :one
INSERT INTO oidc_identities (provider_id, subject, user_id, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, subject) DO UPDATE
SET email      = EXCLUDED.email,
    last_login = now()
RETURNING provider_id, subject, user_id, email, created_at, last_login
`

type LinkOIDCIdentityParams struct {
	ProviderID pgtype.UUID
	Subject    string
	UserID     pgtype.UUID
	Email      string
}

func (q *Queries) LinkOIDCIdentity(ctx context.Context, arg LinkOIDCIdentityParams) (OidcIdentity, error) {
	row := q.db.QueryRow(ctx, linkOIDCIdentity,
		arg.ProviderID,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	var i OidcIdentity
	err := row.Scan(
		&i.ProviderID,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const listEnabledOIDCProviders = `-- name: ListEnabledOIDCProviders :many
SELECT id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at FROM oidc_providers
WHERE enabled
ORDER BY display_name ASC
`

func (q *Queries) ListEnabledOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcProvider
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.AllowSignup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCIdentitiesForUser = `-- name: ListOIDCIdentitiesForUser :many
SELECT i.provider_id, i.subject, i.user_id, i.email, i.created_at, i.last_login, p.slug, p.display_name
FROM oidc_identities i
JOIN oidc_providers p ON p.id = i.provider_id
WHERE i.user_id = $1
ORDER BY p.display_name ASC
`

type ListOIDCIdentitiesForUserRow struct {
	ProviderID  pgtype.UUID
	Subject     string
	UserID      pgtype.UUID
	Email       string
	CreatedAt   pgtype.Timestamptz
	LastLogin   pgtype.Timestamptz
	Slug        string
	DisplayName string
}

func (q *Queries) ListOIDCIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]ListOIDCIdentitiesForUserRow, error) {
	rows, err := q.db.Query(ctx, listOIDCIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOIDCIdentitiesForUserRow
	for rows.Next() {
		var i ListOIDCIdentitiesForUserRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.Subject,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
			&i.LastLogin,
			&i.Slug,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at FROM oidc_providers
ORDER BY display_name ASC
`

func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcProvider
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Issuer,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.AllowSignup,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOIDCIdentity = `-- name: TouchOIDCIdentity :exec
UPDATE oidc_identities
SET last_login = now(),
    email      = $3
WHERE provider_id = $1 AND subject = $2
`

type TouchOIDCIdentityParams struct {
	ProviderID pgtype.UUID
	Subject    string
	Email      string
}

func (q *Queries) TouchOIDCIdentity(ctx context.Context, arg TouchOIDCIdentityParams) error {
	_, err := q.db.Exec(ctx, touchOIDCIdentity, arg.ProviderID, arg.Subject, arg.Email)
	return err
}

const updateOIDCProvider = `-- name: UpdateOIDCProvider :one
UPDATE oidc_providers
SET display_name  = $1,
    issuer        = $2,
    client_id     = $3,
    client_secret = CASE WHEN $4::text = '' THEN client_secret ELSE $4::text END,
    scopes        = $5,
    enabled       = $6,
    allow_signup  = $7,
    updated_at    = now()
WHERE id = $8
RETURNING id, slug, display_name, issuer, client_id, client_secret, scopes, enabled, allow_signup, created_at, updated_at
`

type UpdateOIDCProviderParams struct {
	DisplayName  string
	Issuer       string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateOIDCProvider(ctx context.Context, arg UpdateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, updateOIDCProvider,
		arg.DisplayName,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowSignup,
		arg.ID,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
