// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: osimages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBuildingOSImagesByOwner = `-- name: CountBuildingOSImagesByOwner :one
SELECT count(*) FROM osimages
WHERE soft_deleted_at IS NULL AND created_by = $1
  AND status IN ('pending', 'building')
`

func (q *Queries) CountBuildingOSImagesByOwner(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuildingOSImagesByOwner, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveOSImagesByOwner = `-- name: CountLiveOSImagesByOwner :one
SELECT count(*) FROM osimages
WHERE soft_deleted_at IS NULL AND created_by = $1
`

func (q *Queries) CountLiveOSImagesByOwner(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveOSImagesByOwner, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOSImages = `-- name: CountOSImages :one
SELECT count(*) FROM osimages
WHERE soft_deleted_at IS NULL
`

func (q *Queries) CountOSImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOSImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWithdrawnOSImages = `-- name: CountWithdrawnOSImages :one
SELECT count(*) FROM osimages
WHERE soft_deleted_at IS NOT NULL
`

func (q *Queries) CountWithdrawnOSImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWithdrawnOSImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOCIOSImage = `-- name: CreateOCIOSImage :one
INSERT INTO osimages (name, description, oci_ref, created_by, source, status)
VALUES ($1, $2, $3, $4, 'oci', 'pending')
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type CreateOCIOSImageParams struct {
	Name        string
	Description string
	OCIRef      string
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateOCIOSImage(ctx context.Context, arg CreateOCIOSImageParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, createOCIOSImage,
		arg.Name,
		arg.Description,
		arg.OCIRef,
		arg.CreatedBy,
	)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const createOSImage = `-- name: CreateOSImage :one
INSERT INTO osimages (name, description, object_key, file_name, size_bytes, source, status)
VALUES ($1, $2, $3, $4, $5, 'upload', 'ready')
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type CreateOSImageParams struct {
	Name        string
	Description string
	ObjectKey   string
	FileName    string
	SizeBytes   int64
}

func (q *Queries) CreateOSImage(ctx context.Context, arg CreateOSImageParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, createOSImage,
		arg.Name,
		arg.Description,
		arg.ObjectKey,
		arg.FileName,
		arg.SizeBytes,
	)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const failOSImageBuild = `-- name: FailOSImageBuild :exec
UPDATE osimages
SET status = 'failed', status_detail = $1
WHERE id = $2 AND soft_deleted_at IS NULL AND status <> 'ready'
`

type FailOSImageBuildParams struct {
	StatusDetail string
	ID           pgtype.UUID
}

func (q *Queries) FailOSImageBuild(ctx context.Context, arg FailOSImageBuildParams) error {
	_, err := q.db.Exec(ctx, failOSImageBuild, arg.StatusDetail, arg.ID)
	return err
}

const finishOSImageBuild = `-- name: FinishOSImageBuild :one
UPDATE osimages
SET status = 'ready',
    status_detail = '',
    object_key = $1,
    file_name = $2,
    size_bytes = $3,
    oci_digest = $4,
    config_user = $5,
    config_entrypoint = $6::text[],
    config_cmd = $7::text[],
    config_env = $8::text[],
    config_exposed_ports = $9::integer[],
    default_port = COALESCE(default_port, $10::integer)
WHERE id = $11 AND soft_deleted_at IS NULL AND status <> 'ready'
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type FinishOSImageBuildParams struct {
	ObjectKey          string
	FileName           string
	SizeBytes          int64
	OCIDigest          string
	ConfigUser         string
	ConfigEntrypoint   []string
	ConfigCmd          []string
	ConfigEnv          []string
	ConfigExposedPorts []int32
	DefaultPort        pgtype.Int4
	ID                 pgtype.UUID
}

func (q *Queries) FinishOSImageBuild(ctx context.Context, arg FinishOSImageBuildParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, finishOSImageBuild,
		arg.ObjectKey,
		arg.FileName,
		arg.SizeBytes,
		arg.OCIDigest,
		arg.ConfigUser,
		arg.ConfigEntrypoint,
		arg.ConfigCmd,
		arg.ConfigEnv,
		arg.ConfigExposedPorts,
		arg.DefaultPort,
		arg.ID,
	)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const getOSImage = `-- name: GetOSImage :one
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by FROM osimages
WHERE id = $1
`

func (q *Queries) GetOSImage(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, getOSImage, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const listOSImages = `-- name: ListOSImages :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by FROM osimages
WHERE soft_deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOSImagesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOSImages(ctx context.Context, arg ListOSImagesParams) ([]Osimage, error) {
	rows, err := q.db.Query(ctx, listOSImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Osimage
	for rows.Next() {
		var i Osimage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
			&i.Source,
			&i.OCIRef,
			&i.OCIDigest,
			&i.Status,
			&i.StatusDetail,
			&i.ConfigUser,
			&i.ConfigEntrypoint,
			&i.ConfigCmd,
			&i.ConfigEnv,
			&i.ConfigExposedPorts,
			&i.DefaultPort,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOSImagesByOwner = `-- name: ListOSImagesByOwner :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by FROM osimages
WHERE soft_deleted_at IS NULL AND created_by = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOSImagesByOwnerParams struct {
	CreatedBy pgtype.UUID
	Limit     int32
}

func (q *Queries) ListOSImagesByOwner(ctx context.Context, arg ListOSImagesByOwnerParams) ([]Osimage, error) {
	rows, err := q.db.Query(ctx, listOSImagesByOwner, arg.CreatedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Osimage
	for rows.Next() {
		var i Osimage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
			&i.Source,
			&i.OCIRef,
			&i.OCIDigest,
			&i.Status,
			&i.StatusDetail,
			&i.ConfigUser,
			&i.ConfigEntrypoint,
			&i.ConfigCmd,
			&i.ConfigEnv,
			&i.ConfigExposedPorts,
			&i.DefaultPort,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyOSImages = `-- name: ListReadyOSImages :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by FROM osimages
WHERE soft_deleted_at IS NULL AND status = 'ready'
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListReadyOSImages(ctx context.Context, limit int32) ([]Osimage, error) {
	rows, err := q.db.Query(ctx, listReadyOSImages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Osimage
	for rows.Next() {
		var i Osimage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
			&i.Source,
			&i.OCIRef,
			&i.OCIDigest,
			&i.Status,
			&i.StatusDetail,
			&i.ConfigUser,
			&i.ConfigEntrypoint,
			&i.ConfigCmd,
			&i.ConfigEnv,
			&i.ConfigExposedPorts,
			&i.DefaultPort,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawnOSImages = `-- name: ListWithdrawnOSImages :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by FROM osimages
WHERE soft_deleted_at IS NOT NULL
ORDER BY soft_deleted_at DESC
LIMIT $1 OFFSET $2
`

type ListWithdrawnOSImagesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListWithdrawnOSImages(ctx context.Context, arg ListWithdrawnOSImagesParams) ([]Osimage, error) {
	rows, err := q.db.Query(ctx, listWithdrawnOSImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Osimage
	for rows.Next() {
		var i Osimage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
			&i.Source,
			&i.OCIRef,
			&i.OCIDigest,
			&i.Status,
			&i.StatusDetail,
			&i.ConfigUser,
			&i.ConfigEntrypoint,
			&i.ConfigCmd,
			&i.ConfigEnv,
			&i.ConfigExposedPorts,
			&i.DefaultPort,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOSImageBuilding = `-- name: MarkOSImageBuilding :one
UPDATE osimages
SET status = 'building', status_detail = ''
WHERE id = $1 AND soft_deleted_at IS NULL AND status IN ('pending', 'building', 'failed')
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

func (q *Queries) MarkOSImageBuilding(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, markOSImageBuilding, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const purgeOSImage = `-- name: PurgeOSImage :one
DELETE FROM osimages
WHERE id = $1 AND soft_deleted_at IS NOT NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

// Only a withdrawn image can go: the row is dropped for good so its name frees
// up, and the caller deletes the object it returns from the bucket.
func (q *Queries) PurgeOSImage(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, purgeOSImage, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const softDeleteOSImage = `-- name: SoftDeleteOSImage :one
UPDATE osimages
SET soft_deleted_at = now()
WHERE id = $1 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

func (q *Queries) SoftDeleteOSImage(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, softDeleteOSImage, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const softDeleteOSImageForOwner = `-- name: SoftDeleteOSImageForOwner :one
UPDATE osimages
SET soft_deleted_at = now()
WHERE id = $1 AND created_by = $2 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type SoftDeleteOSImageForOwnerParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) SoftDeleteOSImageForOwner(ctx context.Context, arg SoftDeleteOSImageForOwnerParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, softDeleteOSImageForOwner, arg.ID, arg.CreatedBy)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const updateOSImage = `-- name: UpdateOSImage :one
UPDATE osimages
SET description = $1,
    default_port = COALESCE($2::integer, default_port)
WHERE id = $3 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type UpdateOSImageParams struct {
	Description string
	DefaultPort pgtype.Int4
	ID          pgtype.UUID
}

func (q *Queries) UpdateOSImage(ctx context.Context, arg UpdateOSImageParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, updateOSImage, arg.Description, arg.DefaultPort, arg.ID)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}

const updateOSImageConfig = `-- name: UpdateOSImageConfig :one
UPDATE osimages
SET config_user = $1,
    config_entrypoint = $2::text[],
    config_cmd = $3::text[],
    config_env = $4::text[],
    config_exposed_ports = $5::integer[]
WHERE id = $6 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at, source, oci_ref, oci_digest, status, status_detail, config_user, config_entrypoint, config_cmd, config_env, config_exposed_ports, default_port, created_by
`

type UpdateOSImageConfigParams struct {
	ConfigUser         string
	ConfigEntrypoint   []string
	ConfigCmd          []string
	ConfigEnv          []string
	ConfigExposedPorts []int32
	ID                 pgtype.UUID
}

func (q *Queries) UpdateOSImageConfig(ctx context.Context, arg UpdateOSImageConfigParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, updateOSImageConfig,
		arg.ConfigUser,
		arg.ConfigEntrypoint,
		arg.ConfigCmd,
		arg.ConfigEnv,
		arg.ConfigExposedPorts,
		arg.ID,
	)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
		&i.Source,
		&i.OCIRef,
		&i.OCIDigest,
		&i.Status,
		&i.StatusDetail,
		&i.ConfigUser,
		&i.ConfigEntrypoint,
		&i.ConfigCmd,
		&i.ConfigEnv,
		&i.ConfigExposedPorts,
		&i.DefaultPort,
		&i.CreatedBy,
	)
	return i, err
}
