// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: osimages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOSImages = `-- name: CountOSImages :one
SELECT count(*) FROM osimages
WHERE soft_deleted_at IS NULL
`

func (q *Queries) CountOSImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOSImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOSImage = `-- name: CreateOSImage :one
INSERT INTO osimages (name, description, object_key, file_name, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

type CreateOSImageParams struct {
	Name        string
	Description string
	ObjectKey   string
	FileName    string
	SizeBytes   int64
}

func (q *Queries) CreateOSImage(ctx context.Context, arg CreateOSImageParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, createOSImage,
		arg.Name,
		arg.Description,
		arg.ObjectKey,
		arg.FileName,
		arg.SizeBytes,
	)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const getOSImage = `-- name: GetOSImage :one
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at FROM osimages
WHERE id = $1
`

// Withdrawn rows included: a link to one that was withdrawn should still open
// its page and say so, rather than claim it never existed.
func (q *Queries) GetOSImage(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, getOSImage, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const listOSImages = `-- name: ListOSImages :many
SELECT id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at FROM osimages
WHERE soft_deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOSImagesParams struct {
	Limit  int32
	Offset int32
}

// Withdrawn images are left out: the list is what an operator may still pick.
func (q *Queries) ListOSImages(ctx context.Context, arg ListOSImagesParams) ([]Osimage, error) {
	rows, err := q.db.Query(ctx, listOSImages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Osimage
	for rows.Next() {
		var i Osimage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ObjectKey,
			&i.FileName,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.SoftDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOSImage = `-- name: SoftDeleteOSImage :one
UPDATE osimages
SET soft_deleted_at = now()
WHERE id = $1 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

// No-op on an already-withdrawn row, which returns no rows and lets the caller
// tell "withdrawn now" apart from "was already gone".
func (q *Queries) SoftDeleteOSImage(ctx context.Context, id pgtype.UUID) (Osimage, error) {
	row := q.db.QueryRow(ctx, softDeleteOSImage, id)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}

const updateOSImageDescription = `-- name: UpdateOSImageDescription :one
UPDATE osimages
SET description = $2
WHERE id = $1 AND soft_deleted_at IS NULL
RETURNING id, name, description, object_key, file_name, size_bytes, created_at, soft_deleted_at
`

type UpdateOSImageDescriptionParams struct {
	ID          pgtype.UUID
	Description string
}

// The one editable field. Withdrawn rows are excluded, which returns no rows
// and is what tells the caller it is closed rather than missing.
func (q *Queries) UpdateOSImageDescription(ctx context.Context, arg UpdateOSImageDescriptionParams) (Osimage, error) {
	row := q.db.QueryRow(ctx, updateOSImageDescription, arg.ID, arg.Description)
	var i Osimage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ObjectKey,
		&i.FileName,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.SoftDeletedAt,
	)
	return i, err
}
