// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_access_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticatePersonalAccessToken = `-- name: AuthenticatePersonalAccessToken :one
UPDATE personal_access_tokens
SET last_used_at = now()
WHERE token_hash = $1
  AND revoked = false
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, user_id, token_hash, token_prefix, label, expires_at, revoked, last_used_at, created_at
`

// AuthenticatePersonalAccessToken is the whole auth check for a token, done as
// the same statement that stamps last_used_at: validity and the stamp in one
// round trip, so authenticating costs one query rather than a read plus a
// write. Zero rows means unknown, revoked or expired -- the caller must not
// distinguish, since telling them which would confirm the token exists.
func (q *Queries) AuthenticatePersonalAccessToken(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, authenticatePersonalAccessToken, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Label,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_tokens (user_id, token_hash, token_prefix, label, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, token_prefix, label, expires_at, revoked, last_used_at, created_at
`

type CreatePersonalAccessTokenParams struct {
	UserID      pgtype.UUID
	TokenHash   string
	TokenPrefix string
	Label       string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken,
		arg.UserID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Label,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Label,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePersonalAccessToken = `-- name: DeletePersonalAccessToken :execrows
DELETE FROM personal_access_tokens
WHERE id = $1 AND user_id = $2
`

type DeletePersonalAccessTokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeletePersonalAccessToken(ctx context.Context, arg DeletePersonalAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePersonalAccessToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPersonalAccessTokensByUser = `-- name: ListPersonalAccessTokensByUser :many
SELECT id, user_id, token_hash, token_prefix, label, expires_at, revoked, last_used_at, created_at FROM personal_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPersonalAccessTokensByUser(ctx context.Context, userID pgtype.UUID) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPersonalAccessTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Label,
			&i.ExpiresAt,
			&i.Revoked,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePersonalAccessToken = `-- name: RevokePersonalAccessToken :execrows
UPDATE personal_access_tokens
SET revoked = true
WHERE id = $1 AND user_id = $2
`

type RevokePersonalAccessTokenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokePersonalAccessToken(ctx context.Context, arg RevokePersonalAccessTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePersonalAccessToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
