// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLiveScheduledTasksForSubject = `-- name: CancelLiveScheduledTasksForSubject :exec
UPDATE scheduled_tasks
SET status      = 'cancelled',
    detail      = $1,
    locked_by   = '',
    locked_at   = NULL,
    finished_at = now(),
    updated_at  = now()
WHERE subject_kind = $2
  AND subject_id = $3
  AND status IN ('pending', 'running')
`

type CancelLiveScheduledTasksForSubjectParams struct {
	Detail      string
	SubjectKind string
	SubjectID   pgtype.UUID
}

func (q *Queries) CancelLiveScheduledTasksForSubject(ctx context.Context, arg CancelLiveScheduledTasksForSubjectParams) error {
	_, err := q.db.Exec(ctx, cancelLiveScheduledTasksForSubject, arg.Detail, arg.SubjectKind, arg.SubjectID)
	return err
}

const cancelScheduledTask = `-- name: CancelScheduledTask :one
UPDATE scheduled_tasks
SET status      = 'cancelled',
    detail      = $1,
    finished_at = now(),
    updated_at  = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at
`

type CancelScheduledTaskParams struct {
	Detail string
	ID     pgtype.UUID
}

func (q *Queries) CancelScheduledTask(ctx context.Context, arg CancelScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, cancelScheduledTask, arg.Detail, arg.ID)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Detail,
		&i.Reason,
		&i.CreatedBy,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const claimDueScheduledTasks = `-- name: ClaimDueScheduledTasks :many
UPDATE scheduled_tasks
SET status    = 'running',
    attempts  = attempts + 1,
    locked_by = $1,
    locked_at = now(),
    updated_at = now()
WHERE id IN (
    SELECT id FROM scheduled_tasks
    WHERE status = 'pending' AND run_at <= now()
    ORDER BY run_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at
`

type ClaimDueScheduledTasksParams struct {
	LockedBy string
	MaxTasks int32
}

func (q *Queries) ClaimDueScheduledTasks(ctx context.Context, arg ClaimDueScheduledTasksParams) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, claimDueScheduledTasks, arg.LockedBy, arg.MaxTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Detail,
			&i.Reason,
			&i.CreatedBy,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOverdueScheduledTasks = `-- name: CountOverdueScheduledTasks :one
SELECT count(*) FROM scheduled_tasks
WHERE status = 'pending'
  AND run_at < now() - make_interval(secs => $1::double precision)
`

func (q *Queries) CountOverdueScheduledTasks(ctx context.Context, graceSeconds float64) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueScheduledTasks, graceSeconds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduledTasks = `-- name: CountScheduledTasks :one
SELECT count(*) FROM scheduled_tasks
WHERE (cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text = '' OR kind = $2::text)
`

type CountScheduledTasksParams struct {
	Statuses []string
	Kind     string
}

func (q *Queries) CountScheduledTasks(ctx context.Context, arg CountScheduledTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduledTasks, arg.Statuses, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduledTask = `-- name: CreateScheduledTask :one
INSERT INTO scheduled_tasks (
    kind, subject_kind, subject_id, payload, reason, created_by, max_attempts, run_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    now() + make_interval(secs => $8::double precision)
)
RETURNING id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at
`

type CreateScheduledTaskParams struct {
	Kind         string
	SubjectKind  string
	SubjectID    pgtype.UUID
	Payload      []byte
	Reason       string
	CreatedBy    pgtype.UUID
	MaxAttempts  int32
	DelaySeconds float64
}

func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, createScheduledTask,
		arg.Kind,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Payload,
		arg.Reason,
		arg.CreatedBy,
		arg.MaxAttempts,
		arg.DelaySeconds,
	)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Detail,
		&i.Reason,
		&i.CreatedBy,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createSingletonScheduledTask = `-- name: CreateSingletonScheduledTask :exec
INSERT INTO scheduled_tasks (kind, reason, run_at)
SELECT $1, $2,
       now() + make_interval(secs => $3::double precision)
WHERE NOT EXISTS (
    SELECT 1 FROM scheduled_tasks
    WHERE kind = $1 AND status IN ('pending', 'running')
)
`

type CreateSingletonScheduledTaskParams struct {
	Kind         string
	Reason       string
	DelaySeconds float64
}

func (q *Queries) CreateSingletonScheduledTask(ctx context.Context, arg CreateSingletonScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, createSingletonScheduledTask, arg.Kind, arg.Reason, arg.DelaySeconds)
	return err
}

const deleteSettledScheduledTasksBefore = `-- name: DeleteSettledScheduledTasksBefore :execrows
DELETE FROM scheduled_tasks
WHERE status IN ('done', 'failed', 'cancelled')
  AND finished_at < now() - make_interval(secs => $1::double precision)
`

func (q *Queries) DeleteSettledScheduledTasksBefore(ctx context.Context, ageSeconds float64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSettledScheduledTasksBefore, ageSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishScheduledTask = `-- name: FinishScheduledTask :exec
UPDATE scheduled_tasks
SET status      = $1,
    detail      = $2,
    locked_by   = '',
    locked_at   = NULL,
    finished_at = now(),
    updated_at  = now()
WHERE id = $3
`

type FinishScheduledTaskParams struct {
	Status string
	Detail string
	ID     pgtype.UUID
}

func (q *Queries) FinishScheduledTask(ctx context.Context, arg FinishScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, finishScheduledTask, arg.Status, arg.Detail, arg.ID)
	return err
}

const getScheduledTask = `-- name: GetScheduledTask :one
SELECT id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at FROM scheduled_tasks WHERE id = $1
`

func (q *Queries) GetScheduledTask(ctx context.Context, id pgtype.UUID) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, getScheduledTask, id)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Detail,
		&i.Reason,
		&i.CreatedBy,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listLiveScheduledTasksForSubjects = `-- name: ListLiveScheduledTasksForSubjects :many
SELECT id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at FROM scheduled_tasks
WHERE subject_kind = $1
  AND subject_id = ANY($2::uuid[])
  AND status IN ('pending', 'running')
ORDER BY run_at
`

type ListLiveScheduledTasksForSubjectsParams struct {
	SubjectKind string
	Subjects    []pgtype.UUID
}

func (q *Queries) ListLiveScheduledTasksForSubjects(ctx context.Context, arg ListLiveScheduledTasksForSubjectsParams) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listLiveScheduledTasksForSubjects, arg.SubjectKind, arg.Subjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Detail,
			&i.Reason,
			&i.CreatedBy,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasks = `-- name: ListScheduledTasks :many
SELECT id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at FROM scheduled_tasks
WHERE (cardinality($1::text[]) = 0 OR status = ANY($1::text[]))
  AND ($2::text = '' OR kind = $2::text)
ORDER BY (status IN ('pending', 'running')) DESC,
         CASE WHEN status IN ('pending', 'running') THEN run_at END ASC,
         updated_at DESC
LIMIT $4 OFFSET $3
`

type ListScheduledTasksParams struct {
	Statuses []string
	Kind     string
	Off      int32
	Lim      int32
}

func (q *Queries) ListScheduledTasks(ctx context.Context, arg ListScheduledTasksParams) ([]ScheduledTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasks,
		arg.Statuses,
		arg.Kind,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTask
	for rows.Next() {
		var i ScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Payload,
			&i.Status,
			&i.RunAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.Detail,
			&i.Reason,
			&i.CreatedBy,
			&i.LockedBy,
			&i.LockedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleScheduledTasks = `-- name: ReclaimStaleScheduledTasks :execrows
UPDATE scheduled_tasks
SET status     = 'pending',
    detail     = 'the control server restarted while this task was running, so it was queued again',
    locked_by  = '',
    locked_at  = NULL,
    updated_at = now()
WHERE status = 'running'
  AND locked_at < now() - make_interval(secs => CASE
        WHEN kind = ANY($1::text[])
        THEN $2::double precision
        ELSE $3::double precision
      END)
`

type ReclaimStaleScheduledTasksParams struct {
	LongKinds        []string
	LongLeaseSeconds float64
	LeaseSeconds     float64
}

func (q *Queries) ReclaimStaleScheduledTasks(ctx context.Context, arg ReclaimStaleScheduledTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimStaleScheduledTasks, arg.LongKinds, arg.LongLeaseSeconds, arg.LeaseSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryScheduledTask = `-- name: RetryScheduledTask :exec
UPDATE scheduled_tasks
SET status     = 'pending',
    detail     = $1,
    run_at     = now() + make_interval(secs => $2::double precision),
    locked_by  = '',
    locked_at  = NULL,
    updated_at = now()
WHERE id = $3
`

type RetryScheduledTaskParams struct {
	Detail       string
	DelaySeconds float64
	ID           pgtype.UUID
}

func (q *Queries) RetryScheduledTask(ctx context.Context, arg RetryScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, retryScheduledTask, arg.Detail, arg.DelaySeconds, arg.ID)
	return err
}

const runScheduledTaskNow = `-- name: RunScheduledTaskNow :one
UPDATE scheduled_tasks
SET status     = 'pending',
    run_at     = now(),
    attempts   = 0,
    detail     = $1,
    locked_by  = '',
    locked_at  = NULL,
    finished_at = NULL,
    updated_at = now()
WHERE id = $2 AND status IN ('pending', 'failed')
RETURNING id, kind, subject_kind, subject_id, payload, status, run_at, attempts, max_attempts, detail, reason, created_by, locked_by, locked_at, created_at, updated_at, finished_at
`

type RunScheduledTaskNowParams struct {
	Detail string
	ID     pgtype.UUID
}

func (q *Queries) RunScheduledTaskNow(ctx context.Context, arg RunScheduledTaskNowParams) (ScheduledTask, error) {
	row := q.db.QueryRow(ctx, runScheduledTaskNow, arg.Detail, arg.ID)
	var i ScheduledTask
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.Detail,
		&i.Reason,
		&i.CreatedBy,
		&i.LockedBy,
		&i.LockedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
