// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vm_custom_domains.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomDomain = `-- name: CreateCustomDomain :one
INSERT INTO vm_custom_domains (vm_id, domain)
VALUES ($1, $2)
RETURNING id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at
`

type CreateCustomDomainParams struct {
	VMID   pgtype.UUID
	Domain string
}

func (q *Queries) CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (VmCustomDomain, error) {
	row := q.db.QueryRow(ctx, createCustomDomain, arg.VMID, arg.Domain)
	var i VmCustomDomain
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const customDomainIsServed = `-- name: CustomDomainIsServed :one
SELECT EXISTS (
    SELECT 1 FROM vm_custom_domains
    WHERE domain = $1 AND status = 'active'
)::boolean
`

func (q *Queries) CustomDomainIsServed(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, customDomainIsServed, domain)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteCustomDomain = `-- name: DeleteCustomDomain :exec
DELETE FROM vm_custom_domains
WHERE id = $1
`

func (q *Queries) DeleteCustomDomain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomDomain, id)
	return err
}

const getCustomDomain = `-- name: GetCustomDomain :one
SELECT id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at FROM vm_custom_domains
WHERE id = $1
`

func (q *Queries) GetCustomDomain(ctx context.Context, id pgtype.UUID) (VmCustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomain, id)
	var i VmCustomDomain
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainByVM = `-- name: GetCustomDomainByVM :one
SELECT id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at FROM vm_custom_domains
WHERE vm_id = $1
`

func (q *Queries) GetCustomDomainByVM(ctx context.Context, vmID pgtype.UUID) (VmCustomDomain, error) {
	row := q.db.QueryRow(ctx, getCustomDomainByVM, vmID)
	var i VmCustomDomain
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomDomainForIssue = `-- name: GetCustomDomainForIssue :one
SELECT cd.id, cd.vm_id, cd.domain, cd.status, cd.last_error, cd.cert_object_key, cd.key_object_key, cd.cert_fingerprint, cd.cert_not_after, cd.cert_issued_at, cd.ordered_at, cd.created_at, cd.updated_at,
       v.name       AS vm_name,
       v.client_id  AS client_id,
       v.status     AS vm_status,
       COALESCE(d.tld, '')::text            AS domain_tld,
       COALESCE(d.acme_email, '')::text     AS acme_email,
       COALESCE(d.acme_directory, '')::text AS acme_directory
FROM vm_custom_domains cd
JOIN vms v ON v.id = cd.vm_id
JOIN clients c ON c.id = v.client_id
LEFT JOIN domains d ON d.id = c.domain_id
WHERE cd.id = $1
`

type GetCustomDomainForIssueRow struct {
	ID              pgtype.UUID
	VMID            pgtype.UUID
	Domain          string
	Status          string
	LastError       string
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
	CertIssuedAt    pgtype.Timestamptz
	OrderedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	VMName          string
	ClientID        pgtype.UUID
	VmStatus        string
	DomainTLD       string
	AcmeEmail       string
	AcmeDirectory   string
}

func (q *Queries) GetCustomDomainForIssue(ctx context.Context, id pgtype.UUID) (GetCustomDomainForIssueRow, error) {
	row := q.db.QueryRow(ctx, getCustomDomainForIssue, id)
	var i GetCustomDomainForIssueRow
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VMName,
		&i.ClientID,
		&i.VmStatus,
		&i.DomainTLD,
		&i.AcmeEmail,
		&i.AcmeDirectory,
	)
	return i, err
}

const getVMForOwnerByCustomDomain = `-- name: GetVMForOwnerByCustomDomain :one
SELECT v.id
FROM vms v
JOIN vm_custom_domains cd ON cd.vm_id = v.id
WHERE cd.domain = $1
  AND cd.status = 'active'
  AND v.status <> 'gone'
  AND ($2::boolean OR v.created_by = $3)
`

type GetVMForOwnerByCustomDomainParams struct {
	Domain  string
	IsAdmin bool
	OwnerID pgtype.UUID
}

func (q *Queries) GetVMForOwnerByCustomDomain(ctx context.Context, arg GetVMForOwnerByCustomDomainParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVMForOwnerByCustomDomain, arg.Domain, arg.IsAdmin, arg.OwnerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCustomDomainCertsByClient = `-- name: ListCustomDomainCertsByClient :many
SELECT cd.domain, cd.cert_object_key, cd.key_object_key
FROM vm_custom_domains cd
JOIN vms v ON v.id = cd.vm_id
WHERE v.client_id = $1
  AND cd.status = 'active'
  AND cd.cert_object_key <> ''
  AND cd.key_object_key <> ''
ORDER BY cd.domain
`

type ListCustomDomainCertsByClientRow struct {
	Domain        string
	CertObjectKey string
	KeyObjectKey  string
}

func (q *Queries) ListCustomDomainCertsByClient(ctx context.Context, clientID pgtype.UUID) ([]ListCustomDomainCertsByClientRow, error) {
	rows, err := q.db.Query(ctx, listCustomDomainCertsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomDomainCertsByClientRow
	for rows.Next() {
		var i ListCustomDomainCertsByClientRow
		if err := rows.Scan(&i.Domain, &i.CertObjectKey, &i.KeyObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomDomainRoutesByClient = `-- name: ListCustomDomainRoutesByClient :many
SELECT cd.domain, v.name AS vm_name, v.ip AS vm_ip,
       v.default_port, v.public_ports,
       COALESCE(NULLIF(v.default_user, ''), v.spec->'image'->>'user', '')::text AS session_user
FROM vm_custom_domains cd
JOIN vms v ON v.id = cd.vm_id
WHERE v.client_id = $1
  AND cd.status = 'active'
  AND v.ip <> ''
  AND v.status <> 'gone'
ORDER BY cd.domain
`

type ListCustomDomainRoutesByClientRow struct {
	Domain      string
	VMName      string
	VMIP        string
	DefaultPort int32
	PublicPorts []int32
	SessionUser string
}

func (q *Queries) ListCustomDomainRoutesByClient(ctx context.Context, clientID pgtype.UUID) ([]ListCustomDomainRoutesByClientRow, error) {
	rows, err := q.db.Query(ctx, listCustomDomainRoutesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomDomainRoutesByClientRow
	for rows.Next() {
		var i ListCustomDomainRoutesByClientRow
		if err := rows.Scan(
			&i.Domain,
			&i.VMName,
			&i.VMIP,
			&i.DefaultPort,
			&i.PublicPorts,
			&i.SessionUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomDomainsDueForRenewal = `-- name: ListCustomDomainsDueForRenewal :many
SELECT id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at FROM vm_custom_domains
WHERE status = 'active'
  AND (cert_not_after IS NULL OR cert_not_after < now() + make_interval(secs => $1::float))
ORDER BY cert_not_after NULLS FIRST
`

func (q *Queries) ListCustomDomainsDueForRenewal(ctx context.Context, withinSeconds float64) ([]VmCustomDomain, error) {
	rows, err := q.db.Query(ctx, listCustomDomainsDueForRenewal, withinSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VmCustomDomain
	for rows.Next() {
		var i VmCustomDomain
		if err := rows.Scan(
			&i.ID,
			&i.VMID,
			&i.Domain,
			&i.Status,
			&i.LastError,
			&i.CertObjectKey,
			&i.KeyObjectKey,
			&i.CertFingerprint,
			&i.CertNotAfter,
			&i.CertIssuedAt,
			&i.OrderedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomDomainOrdered = `-- name: MarkCustomDomainOrdered :exec
UPDATE vm_custom_domains
SET ordered_at = now()
WHERE id = $1
`

func (q *Queries) MarkCustomDomainOrdered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCustomDomainOrdered, id)
	return err
}

const setCustomDomainStatus = `-- name: SetCustomDomainStatus :one
UPDATE vm_custom_domains
SET status     = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at
`

type SetCustomDomainStatusParams struct {
	ID        pgtype.UUID
	Status    string
	LastError string
}

func (q *Queries) SetCustomDomainStatus(ctx context.Context, arg SetCustomDomainStatusParams) (VmCustomDomain, error) {
	row := q.db.QueryRow(ctx, setCustomDomainStatus, arg.ID, arg.Status, arg.LastError)
	var i VmCustomDomain
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomDomainCert = `-- name: UpdateCustomDomainCert :one
UPDATE vm_custom_domains
SET status           = 'active',
    last_error       = '',
    cert_object_key  = $2,
    key_object_key   = $3,
    cert_fingerprint = $4,
    cert_not_after   = $5,
    cert_issued_at   = now(),
    ordered_at       = NULL,
    updated_at       = now()
WHERE id = $1
RETURNING id, vm_id, domain, status, last_error, cert_object_key, key_object_key, cert_fingerprint, cert_not_after, cert_issued_at, ordered_at, created_at, updated_at
`

type UpdateCustomDomainCertParams struct {
	ID              pgtype.UUID
	CertObjectKey   string
	KeyObjectKey    string
	CertFingerprint string
	CertNotAfter    pgtype.Timestamptz
}

func (q *Queries) UpdateCustomDomainCert(ctx context.Context, arg UpdateCustomDomainCertParams) (VmCustomDomain, error) {
	row := q.db.QueryRow(ctx, updateCustomDomainCert,
		arg.ID,
		arg.CertObjectKey,
		arg.KeyObjectKey,
		arg.CertFingerprint,
		arg.CertNotAfter,
	)
	var i VmCustomDomain
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Domain,
		&i.Status,
		&i.LastError,
		&i.CertObjectKey,
		&i.KeyObjectKey,
		&i.CertFingerprint,
		&i.CertNotAfter,
		&i.CertIssuedAt,
		&i.OrderedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
