// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vm_network_targets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVMNetworkTarget = `-- name: CreateVMNetworkTarget :one
INSERT INTO vm_network_targets (vm_id, destination, kind, transport, ports, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vm_id, kind, destination, transport, ports, note, created_at, updated_at
`

type CreateVMNetworkTargetParams struct {
	VMID        pgtype.UUID
	Destination string
	Kind        string
	Transport   string
	Ports       string
	Note        string
}

func (q *Queries) CreateVMNetworkTarget(ctx context.Context, arg CreateVMNetworkTargetParams) (VmNetworkTarget, error) {
	row := q.db.QueryRow(ctx, createVMNetworkTarget,
		arg.VMID,
		arg.Destination,
		arg.Kind,
		arg.Transport,
		arg.Ports,
		arg.Note,
	)
	var i VmNetworkTarget
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Kind,
		&i.Destination,
		&i.Transport,
		&i.Ports,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVMNetworkTarget = `-- name: DeleteVMNetworkTarget :exec
DELETE FROM vm_network_targets
WHERE id = $1 AND vm_id = $2
`

type DeleteVMNetworkTargetParams struct {
	ID   pgtype.UUID
	VMID pgtype.UUID
}

// Scoped by vm_id as well as id: the caller has already proved it owns the VM,
// so pinning the delete to that VM means a target id from someone else's VM
// matches nothing rather than deleting their row.
func (q *Queries) DeleteVMNetworkTarget(ctx context.Context, arg DeleteVMNetworkTargetParams) error {
	_, err := q.db.Exec(ctx, deleteVMNetworkTarget, arg.ID, arg.VMID)
	return err
}

const listVMNetworkTargets = `-- name: ListVMNetworkTargets :many
SELECT id, vm_id, kind, destination, transport, ports, note, created_at, updated_at FROM vm_network_targets
WHERE vm_id = $1
ORDER BY kind, destination, transport, ports
`

func (q *Queries) ListVMNetworkTargets(ctx context.Context, vmID pgtype.UUID) ([]VmNetworkTarget, error) {
	rows, err := q.db.Query(ctx, listVMNetworkTargets, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VmNetworkTarget
	for rows.Next() {
		var i VmNetworkTarget
		if err := rows.Scan(
			&i.ID,
			&i.VMID,
			&i.Kind,
			&i.Destination,
			&i.Transport,
			&i.Ports,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMNetworkTargetsByClient = `-- name: ListVMNetworkTargetsByClient :many
SELECT v.ip AS vm_ip, v.vm_id AS host_vm_id, v.name AS vm_name,
       COALESCE(t.kind, '') AS kind,
       COALESCE(t.destination, '') AS destination,
       COALESCE(t.transport, '') AS transport,
       COALESCE(t.ports, '') AS ports,
       COALESCE(t.note, '') AS note
FROM vms v
LEFT JOIN vm_network_targets t ON t.vm_id = v.id
WHERE v.client_id = $1
  AND v.ip <> ''
  AND v.status <> 'gone'
ORDER BY v.ip, kind, destination, transport, ports
`

type ListVMNetworkTargetsByClientRow struct {
	VMIP        string
	HostVMID    string
	VMName      string
	Kind        string
	Destination string
	Transport   string
	Ports       string
	Note        string
}

// ListVMNetworkTargetsByClient is the input to the rule generator and the
// Corefile generator: every allowance on the host, carrying the address of the
// VM that owns it.
//
// One query rather than a VM list plus a lookup per VM, because both files are
// generated as a whole and a half-read fleet would compile to a ruleset that
// silently revokes whatever was missed.
//
// Rows without an address are skipped: a rule is scoped to a VM by its source
// IP, so a VM that has not been given one yet cannot be expressed. It is still
// covered -- by the default deny, which is what an unscopable allowance should
// fall back to. 'gone' VMs are excluded for the same reason in reverse: their
// address will be handed to some other guest, and a stale pass rule would let
// that guest out.
//
// The join is a LEFT JOIN, so a VM with no allowances at all still comes back --
// as one row with an empty destination. That VM is the one the generator most
// needs to know about: with nothing to allow it has no rule that depends on
// seeing a handshake, so it gets a blanket deny instead of the split floor, and
// a VM the query omitted would silently keep the syn on 80/443.
//
// COALESCE rather than nullable columns. The schema already writes ” for a
// field that does not apply to a row's kind (see 0010_vm_network_targets), so
// every consumer reads a string without checking a flag; letting the join
// introduce NULLs here would be a second way to spell "no value" that only this
// one query has.
func (q *Queries) ListVMNetworkTargetsByClient(ctx context.Context, clientID pgtype.UUID) ([]ListVMNetworkTargetsByClientRow, error) {
	rows, err := q.db.Query(ctx, listVMNetworkTargetsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVMNetworkTargetsByClientRow
	for rows.Next() {
		var i ListVMNetworkTargetsByClientRow
		if err := rows.Scan(
			&i.VMIP,
			&i.HostVMID,
			&i.VMName,
			&i.Kind,
			&i.Destination,
			&i.Transport,
			&i.Ports,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
