// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vm_network_targets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVMNetworkTarget = `-- name: CreateVMNetworkTarget :one
INSERT INTO vm_network_targets (vm_id, destination, kind, transport, ports, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, vm_id, kind, destination, transport, ports, note, created_at, updated_at
`

type CreateVMNetworkTargetParams struct {
	VMID        pgtype.UUID
	Destination string
	Kind        string
	Transport   string
	Ports       string
	Note        string
}

func (q *Queries) CreateVMNetworkTarget(ctx context.Context, arg CreateVMNetworkTargetParams) (VmNetworkTarget, error) {
	row := q.db.QueryRow(ctx, createVMNetworkTarget,
		arg.VMID,
		arg.Destination,
		arg.Kind,
		arg.Transport,
		arg.Ports,
		arg.Note,
	)
	var i VmNetworkTarget
	err := row.Scan(
		&i.ID,
		&i.VMID,
		&i.Kind,
		&i.Destination,
		&i.Transport,
		&i.Ports,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVMNetworkTarget = `-- name: DeleteVMNetworkTarget :exec
DELETE FROM vm_network_targets
WHERE id = $1 AND vm_id = $2
`

type DeleteVMNetworkTargetParams struct {
	ID   pgtype.UUID
	VMID pgtype.UUID
}

// Scoped by vm_id as well as id: the caller has already proved it owns the VM,
// so pinning the delete to that VM means a target id from someone else's VM
// matches nothing rather than deleting their row.
func (q *Queries) DeleteVMNetworkTarget(ctx context.Context, arg DeleteVMNetworkTargetParams) error {
	_, err := q.db.Exec(ctx, deleteVMNetworkTarget, arg.ID, arg.VMID)
	return err
}

const listVMNetworkTargets = `-- name: ListVMNetworkTargets :many
SELECT id, vm_id, kind, destination, transport, ports, note, created_at, updated_at FROM vm_network_targets
WHERE vm_id = $1
ORDER BY kind, destination, transport, ports
`

func (q *Queries) ListVMNetworkTargets(ctx context.Context, vmID pgtype.UUID) ([]VmNetworkTarget, error) {
	rows, err := q.db.Query(ctx, listVMNetworkTargets, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VmNetworkTarget
	for rows.Next() {
		var i VmNetworkTarget
		if err := rows.Scan(
			&i.ID,
			&i.VMID,
			&i.Kind,
			&i.Destination,
			&i.Transport,
			&i.Ports,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
