// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVMs = `-- name: CountVMs :one
SELECT count(*) FROM vms
`

func (q *Queries) CountVMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVMs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMsByClient = `-- name: CountVMsByClient :one
SELECT count(*) FROM vms
WHERE client_id = $1
`

func (q *Queries) CountVMsByClient(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsByClient, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMsByOwner = `-- name: CountVMsByOwner :one
SELECT count(*) FROM vms
WHERE created_by = $1
`

func (q *Queries) CountVMsByOwner(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsByOwner, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVM = `-- name: CreateVM :one
INSERT INTO vms (client_id, name, boot, cpus, memory_mib, disk_mib, spec, created_by, default_port, public_ports)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce
`

type CreateVMParams struct {
	ClientID    pgtype.UUID
	Name        string
	Boot        string
	CPUs        int32
	MemoryMiB   int32
	DiskMiB     int32
	Spec        []byte
	CreatedBy   pgtype.UUID
	DefaultPort int32
	PublicPorts []int32
}

func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (Vm, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.ClientID,
		arg.Name,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.DiskMiB,
		arg.Spec,
		arg.CreatedBy,
		arg.DefaultPort,
		arg.PublicPorts,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
		&i.DiskMiB,
		&i.DefaultPort,
		&i.PublicPorts,
		&i.RdpNonce,
	)
	return i, err
}

const deleteAdoptedVM = `-- name: DeleteAdoptedVM :exec
DELETE FROM vms
WHERE client_id = $1 AND vm_id = $2 AND id <> $3
`

type DeleteAdoptedVMParams struct {
	ClientID pgtype.UUID
	VMID     string
	ID       pgtype.UUID
}

func (q *Queries) DeleteAdoptedVM(ctx context.Context, arg DeleteAdoptedVMParams) error {
	_, err := q.db.Exec(ctx, deleteAdoptedVM, arg.ClientID, arg.VMID, arg.ID)
	return err
}

const deleteVM = `-- name: DeleteVM :exec
DELETE FROM vms
WHERE id = $1
`

func (q *Queries) DeleteVM(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVM, id)
	return err
}

const failAllPendingVMs = `-- name: FailAllPendingVMs :exec
UPDATE vms
SET status = 'failed', last_error = $1, updated_at = now()
WHERE status = 'pending'
`

func (q *Queries) FailAllPendingVMs(ctx context.Context, lastError string) error {
	_, err := q.db.Exec(ctx, failAllPendingVMs, lastError)
	return err
}

const failPendingVMsForClient = `-- name: FailPendingVMsForClient :exec
UPDATE vms
SET status = 'failed', last_error = $2, updated_at = now()
WHERE client_id = $1 AND status = 'pending'
`

type FailPendingVMsForClientParams struct {
	ClientID  pgtype.UUID
	LastError string
}

func (q *Queries) FailPendingVMsForClient(ctx context.Context, arg FailPendingVMsForClientParams) error {
	_, err := q.db.Exec(ctx, failPendingVMsForClient, arg.ClientID, arg.LastError)
	return err
}

const getVM = `-- name: GetVM :one
SELECT id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce FROM vms
WHERE id = $1
`

func (q *Queries) GetVM(ctx context.Context, id pgtype.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
		&i.DiskMiB,
		&i.DefaultPort,
		&i.PublicPorts,
		&i.RdpNonce,
	)
	return i, err
}

const getVMForOwner = `-- name: GetVMForOwner :one
SELECT id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce FROM vms
WHERE id = $1 AND created_by = $2
`

type GetVMForOwnerParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) GetVMForOwner(ctx context.Context, arg GetVMForOwnerParams) (Vm, error) {
	row := q.db.QueryRow(ctx, getVMForOwner, arg.ID, arg.CreatedBy)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
		&i.DiskMiB,
		&i.DefaultPort,
		&i.PublicPorts,
		&i.RdpNonce,
	)
	return i, err
}

const getVMForOwnerByHostname = `-- name: GetVMForOwnerByHostname :one
SELECT v.id
FROM vms v
JOIN clients a ON a.id = v.client_id
JOIN domains d ON d.id = a.domain_id
WHERE v.name = $1
  AND d.tld = $2
  AND v.status <> 'gone'
  AND ($3::boolean OR v.created_by = $4)
`

type GetVMForOwnerByHostnameParams struct {
	Name      string
	DomainTLD string
	IsAdmin   bool
	OwnerID   pgtype.UUID
}

func (q *Queries) GetVMForOwnerByHostname(ctx context.Context, arg GetVMForOwnerByHostnameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVMForOwnerByHostname,
		arg.Name,
		arg.DomainTLD,
		arg.IsAdmin,
		arg.OwnerID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listProxyHTTPRoutesByClient = `-- name: ListProxyHTTPRoutesByClient :many
SELECT v.name AS vm_name, v.ip AS vm_ip, v.vm_id AS host_vm_id,
       v.default_port, v.public_ports, d.tld AS domain_tld
FROM vms v
JOIN clients a ON a.id = v.client_id
JOIN domains d ON d.id = a.domain_id
WHERE v.client_id = $1
  AND v.ip <> ''
  AND v.status <> 'gone'
ORDER BY v.created_at, v.vm_id
`

type ListProxyHTTPRoutesByClientRow struct {
	VMName      string
	VMIP        string
	HostVMID    string
	DefaultPort int32
	PublicPorts []int32
	DomainTLD   string
}

func (q *Queries) ListProxyHTTPRoutesByClient(ctx context.Context, clientID pgtype.UUID) ([]ListProxyHTTPRoutesByClientRow, error) {
	rows, err := q.db.Query(ctx, listProxyHTTPRoutesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProxyHTTPRoutesByClientRow
	for rows.Next() {
		var i ListProxyHTTPRoutesByClientRow
		if err := rows.Scan(
			&i.VMName,
			&i.VMIP,
			&i.HostVMID,
			&i.DefaultPort,
			&i.PublicPorts,
			&i.DomainTLD,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyRDPUsersByClient = `-- name: ListProxyRDPUsersByClient :many
SELECT v.id AS vm_pk, v.ip AS vm_ip, v.vm_id AS host_vm_id, v.name AS vm_name, v.rdp_nonce
FROM vms v
WHERE v.client_id = $1
  AND v.ip <> ''
  AND v.status <> 'gone'
ORDER BY v.created_at, v.vm_id
`

type ListProxyRDPUsersByClientRow struct {
	VmPk     pgtype.UUID
	VMIP     string
	HostVMID string
	VMName   string
	RdpNonce string
}

func (q *Queries) ListProxyRDPUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]ListProxyRDPUsersByClientRow, error) {
	rows, err := q.db.Query(ctx, listProxyRDPUsersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProxyRDPUsersByClientRow
	for rows.Next() {
		var i ListProxyRDPUsersByClientRow
		if err := rows.Scan(
			&i.VmPk,
			&i.VMIP,
			&i.HostVMID,
			&i.VMName,
			&i.RdpNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxySSHUsersByClient = `-- name: ListProxySSHUsersByClient :many
SELECT v.ip AS vm_ip, v.vm_id AS host_vm_id, v.name AS vm_name, u.public_key
FROM vms v
JOIN users u ON u.id = v.created_by
WHERE v.client_id = $1
  AND v.ip <> ''
  AND v.status <> 'gone'
  AND u.public_key <> ''
ORDER BY v.created_at, v.vm_id
`

type ListProxySSHUsersByClientRow struct {
	VMIP      string
	HostVMID  string
	VMName    string
	PublicKey string
}

func (q *Queries) ListProxySSHUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]ListProxySSHUsersByClientRow, error) {
	rows, err := q.db.Query(ctx, listProxySSHUsersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProxySSHUsersByClientRow
	for rows.Next() {
		var i ListProxySSHUsersByClientRow
		if err := rows.Scan(
			&i.VMIP,
			&i.HostVMID,
			&i.VMName,
			&i.PublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMs = `-- name: ListVMs :many
SELECT id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce FROM vms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVMsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVMs(ctx context.Context, arg ListVMsParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
			&i.DiskMiB,
			&i.DefaultPort,
			&i.PublicPorts,
			&i.RdpNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByClient = `-- name: ListVMsByClient :many
SELECT id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce FROM vms
WHERE client_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVMsByClientParams struct {
	ClientID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListVMsByClient(ctx context.Context, arg ListVMsByClientParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMsByClient, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
			&i.DiskMiB,
			&i.DefaultPort,
			&i.PublicPorts,
			&i.RdpNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByOwner = `-- name: ListVMsByOwner :many
SELECT id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce FROM vms
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVMsByOwnerParams struct {
	CreatedBy pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListVMsByOwner(ctx context.Context, arg ListVMsByOwnerParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMsByOwner, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
			&i.DiskMiB,
			&i.DefaultPort,
			&i.PublicPorts,
			&i.RdpNonce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingVMsGone = `-- name: MarkMissingVMsGone :exec
UPDATE vms
SET status = 'gone', updated_at = now()
WHERE client_id = $1
  AND vm_id <> ''
  AND status IN ('running', 'stopped')
  AND NOT (vm_id = ANY($2::text[]))
`

type MarkMissingVMsGoneParams struct {
	ClientID pgtype.UUID
	VmIds    []string
}

func (q *Queries) MarkMissingVMsGone(ctx context.Context, arg MarkMissingVMsGoneParams) error {
	_, err := q.db.Exec(ctx, markMissingVMsGone, arg.ClientID, arg.VmIds)
	return err
}

const markVMFailed = `-- name: MarkVMFailed :exec
UPDATE vms
SET status = 'failed', last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkVMFailedParams struct {
	ID        pgtype.UUID
	LastError string
}

func (q *Queries) MarkVMFailed(ctx context.Context, arg MarkVMFailedParams) error {
	_, err := q.db.Exec(ctx, markVMFailed, arg.ID, arg.LastError)
	return err
}

const markVMRunning = `-- name: MarkVMRunning :exec
UPDATE vms
SET status     = 'running',
    vm_id      = $2,
    boot       = $3,
    cpus       = $4,
    memory_mib = $5,
    ip         = $6,
    last_error = '',
    started_at = now(),
    updated_at = now()
WHERE id = $1
`

type MarkVMRunningParams struct {
	ID        pgtype.UUID
	VMID      string
	Boot      string
	CPUs      int32
	MemoryMiB int32
	IP        string
}

func (q *Queries) MarkVMRunning(ctx context.Context, arg MarkVMRunningParams) error {
	_, err := q.db.Exec(ctx, markVMRunning,
		arg.ID,
		arg.VMID,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.IP,
	)
	return err
}

const rotateVMRDPNonceForOwner = `-- name: RotateVMRDPNonceForOwner :one
UPDATE vms
SET rdp_nonce  = gen_random_uuid()::text,
    updated_at = now()
WHERE id = $1 AND created_by = $2
RETURNING id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce
`

type RotateVMRDPNonceForOwnerParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) RotateVMRDPNonceForOwner(ctx context.Context, arg RotateVMRDPNonceForOwnerParams) (Vm, error) {
	row := q.db.QueryRow(ctx, rotateVMRDPNonceForOwner, arg.ID, arg.CreatedBy)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
		&i.DiskMiB,
		&i.DefaultPort,
		&i.PublicPorts,
		&i.RdpNonce,
	)
	return i, err
}

const setVMLastError = `-- name: SetVMLastError :exec
UPDATE vms
SET last_error = $2, updated_at = now()
WHERE id = $1
`

type SetVMLastErrorParams struct {
	ID        pgtype.UUID
	LastError string
}

func (q *Queries) SetVMLastError(ctx context.Context, arg SetVMLastErrorParams) error {
	_, err := q.db.Exec(ctx, setVMLastError, arg.ID, arg.LastError)
	return err
}

const setVMStatus = `-- name: SetVMStatus :exec
UPDATE vms
SET status = $2, last_error = '', reported_at = now(), updated_at = now()
WHERE id = $1
`

type SetVMStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetVMStatus(ctx context.Context, arg SetVMStatusParams) error {
	_, err := q.db.Exec(ctx, setVMStatus, arg.ID, arg.Status)
	return err
}

const sumActiveVMUsageByOwner = `-- name: SumActiveVMUsageByOwner :one
SELECT COALESCE(SUM(cpus), 0)::int AS cpus,
       COALESCE(SUM(memory_mib), 0)::int AS memory_mib,
       COALESCE(SUM(disk_mib), 0)::int AS disk_mib
FROM vms
WHERE created_by = $1
  AND status IN ('pending', 'running', 'stopped')
`

type SumActiveVMUsageByOwnerRow struct {
	CPUs      int32
	MemoryMiB int32
	DiskMiB   int32
}

func (q *Queries) SumActiveVMUsageByOwner(ctx context.Context, createdBy pgtype.UUID) (SumActiveVMUsageByOwnerRow, error) {
	row := q.db.QueryRow(ctx, sumActiveVMUsageByOwner, createdBy)
	var i SumActiveVMUsageByOwnerRow
	err := row.Scan(&i.CPUs, &i.MemoryMiB, &i.DiskMiB)
	return i, err
}

const updateVMPortsForOwner = `-- name: UpdateVMPortsForOwner :one
UPDATE vms
SET default_port = $3,
    public_ports = $4,
    updated_at   = now()
WHERE id = $1 AND created_by = $2
RETURNING id, client_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by, disk_mib, default_port, public_ports, rdp_nonce
`

type UpdateVMPortsForOwnerParams struct {
	ID          pgtype.UUID
	CreatedBy   pgtype.UUID
	DefaultPort int32
	PublicPorts []int32
}

func (q *Queries) UpdateVMPortsForOwner(ctx context.Context, arg UpdateVMPortsForOwnerParams) (Vm, error) {
	row := q.db.QueryRow(ctx, updateVMPortsForOwner,
		arg.ID,
		arg.CreatedBy,
		arg.DefaultPort,
		arg.PublicPorts,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
		&i.DiskMiB,
		&i.DefaultPort,
		&i.PublicPorts,
		&i.RdpNonce,
	)
	return i, err
}

const upsertVMFromInventory = `-- name: UpsertVMFromInventory :exec
INSERT INTO vms (client_id, vm_id, name, status, boot, cpus, memory_mib, ip, created_at, started_at, reported_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (client_id, vm_id) WHERE vm_id <> '' DO UPDATE
SET status      = EXCLUDED.status,
    boot        = EXCLUDED.boot,
    cpus        = EXCLUDED.cpus,
    memory_mib  = EXCLUDED.memory_mib,
    ip          = EXCLUDED.ip,
    started_at  = COALESCE(vms.started_at, EXCLUDED.started_at),
    reported_at = now(),
    updated_at  = now()
`

type UpsertVMFromInventoryParams struct {
	ClientID  pgtype.UUID
	VMID      string
	Name      string
	Status    string
	Boot      string
	CPUs      int32
	MemoryMiB int32
	IP        string
	CreatedAt pgtype.Timestamptz
	StartedAt pgtype.Timestamptz
}

func (q *Queries) UpsertVMFromInventory(ctx context.Context, arg UpsertVMFromInventoryParams) error {
	_, err := q.db.Exec(ctx, upsertVMFromInventory,
		arg.ClientID,
		arg.VMID,
		arg.Name,
		arg.Status,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.IP,
		arg.CreatedAt,
		arg.StartedAt,
	)
	return err
}
