// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVMs = `-- name: CountVMs :one
SELECT count(*) FROM vms
`

func (q *Queries) CountVMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countVMs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMsByAgent = `-- name: CountVMsByAgent :one
SELECT count(*) FROM vms
WHERE agent_id = $1
`

func (q *Queries) CountVMsByAgent(ctx context.Context, agentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsByAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMsByOwner = `-- name: CountVMsByOwner :one
SELECT count(*) FROM vms
WHERE created_by = $1
`

func (q *Queries) CountVMsByOwner(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVMsByOwner, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVM = `-- name: CreateVM :one
INSERT INTO vms (agent_id, name, boot, cpus, memory_mib, spec, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by
`

type CreateVMParams struct {
	AgentID   pgtype.UUID
	Name      string
	Boot      string
	CPUs      int32
	MemoryMiB int32
	Spec      []byte
	CreatedBy pgtype.UUID
}

// CreateVM records the intent before the job is pushed to the agent. The row id
// doubles as the job's correlation id, which is what lets the result frame find
// its way back to exactly this row.
func (q *Queries) CreateVM(ctx context.Context, arg CreateVMParams) (Vm, error) {
	row := q.db.QueryRow(ctx, createVM,
		arg.AgentID,
		arg.Name,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.Spec,
		arg.CreatedBy,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteAdoptedVM = `-- name: DeleteAdoptedVM :exec
DELETE FROM vms
WHERE agent_id = $1 AND vm_id = $2 AND id <> $3
`

type DeleteAdoptedVMParams struct {
	AgentID pgtype.UUID
	VMID    string
	ID      pgtype.UUID
}

// DeleteAdoptedVM resolves the one race between the two ways a row is born: an
// inventory report can land after the agent has written vm.json but before its
// result frame arrives, adopting a VM that already has a pending row waiting for
// it. The adopted duplicate is dropped so the pending row -- which holds the
// spec that was asked for -- is the one that survives.
func (q *Queries) DeleteAdoptedVM(ctx context.Context, arg DeleteAdoptedVMParams) error {
	_, err := q.db.Exec(ctx, deleteAdoptedVM, arg.AgentID, arg.VMID, arg.ID)
	return err
}

const deleteVM = `-- name: DeleteVM :exec
DELETE FROM vms
WHERE id = $1
`

func (q *Queries) DeleteVM(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVM, id)
	return err
}

const failAllPendingVMs = `-- name: FailAllPendingVMs :exec
UPDATE vms
SET status = 'failed', last_error = $1, updated_at = now()
WHERE status = 'pending'
`

// FailAllPendingVMs is the startup counterpart: in-flight jobs belonged to the
// previous process's sockets and cannot be resumed.
func (q *Queries) FailAllPendingVMs(ctx context.Context, lastError string) error {
	_, err := q.db.Exec(ctx, failAllPendingVMs, lastError)
	return err
}

const failPendingVMsForAgent = `-- name: FailPendingVMsForAgent :exec
UPDATE vms
SET status = 'failed', last_error = $2, updated_at = now()
WHERE agent_id = $1 AND status = 'pending'
`

type FailPendingVMsForAgentParams struct {
	AgentID   pgtype.UUID
	LastError string
}

// FailPendingVMsForAgent runs when an agent's socket drops and at startup: a
// pending row is waiting on a result frame that can no longer arrive, so it
// would otherwise sit there forever claiming to be in progress.
func (q *Queries) FailPendingVMsForAgent(ctx context.Context, arg FailPendingVMsForAgentParams) error {
	_, err := q.db.Exec(ctx, failPendingVMsForAgent, arg.AgentID, arg.LastError)
	return err
}

const getVM = `-- name: GetVM :one
SELECT id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by FROM vms
WHERE id = $1
`

func (q *Queries) GetVM(ctx context.Context, id pgtype.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getVMForOwner = `-- name: GetVMForOwner :one
SELECT id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by FROM vms
WHERE id = $1 AND created_by = $2
`

type GetVMForOwnerParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

// GetVMForOwner is the ownership check and the read in one statement. Doing it
// as two -- read, then compare created_by in Go -- is the same query written so
// that forgetting the second half silently leaks another user's VM.
func (q *Queries) GetVMForOwner(ctx context.Context, arg GetVMForOwnerParams) (Vm, error) {
	row := q.db.QueryRow(ctx, getVMForOwner, arg.ID, arg.CreatedBy)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.VMID,
		&i.Name,
		&i.Status,
		&i.Boot,
		&i.CPUs,
		&i.MemoryMiB,
		&i.IP,
		&i.Spec,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ReportedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listVMs = `-- name: ListVMs :many
SELECT id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by FROM vms
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVMsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListVMs(ctx context.Context, arg ListVMsParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByAgent = `-- name: ListVMsByAgent :many
SELECT id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by FROM vms
WHERE agent_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVMsByAgentParams struct {
	AgentID pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListVMsByAgent(ctx context.Context, arg ListVMsByAgentParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByOwner = `-- name: ListVMsByOwner :many
SELECT id, agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, spec, last_error, created_at, updated_at, started_at, reported_at, created_by FROM vms
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVMsByOwnerParams struct {
	CreatedBy pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListVMsByOwner(ctx context.Context, arg ListVMsByOwnerParams) ([]Vm, error) {
	rows, err := q.db.Query(ctx, listVMsByOwner, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vm
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.VMID,
			&i.Name,
			&i.Status,
			&i.Boot,
			&i.CPUs,
			&i.MemoryMiB,
			&i.IP,
			&i.Spec,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ReportedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingVMsGone = `-- name: MarkMissingVMsGone :exec
UPDATE vms
SET status = 'gone', updated_at = now()
WHERE agent_id = $1
  AND vm_id <> ''
  AND status IN ('running', 'stopped')
  AND NOT (vm_id = ANY($2::text[]))
`

type MarkMissingVMsGoneParams struct {
	AgentID pgtype.UUID
	VmIds   []string
}

// MarkMissingVMsGone settles the other half of an inventory report: a row the
// agent no longer lists has been removed on the host.
//
// Only rows the host had already assigned an id to are considered. A 'pending'
// row has no id yet and is waiting on its result frame, and a 'failed' one never
// got that far -- neither is missing, and neither should be touched here.
func (q *Queries) MarkMissingVMsGone(ctx context.Context, arg MarkMissingVMsGoneParams) error {
	_, err := q.db.Exec(ctx, markMissingVMsGone, arg.AgentID, arg.VmIds)
	return err
}

const markVMFailed = `-- name: MarkVMFailed :exec
UPDATE vms
SET status = 'failed', last_error = $2, updated_at = now()
WHERE id = $1
`

type MarkVMFailedParams struct {
	ID        pgtype.UUID
	LastError string
}

func (q *Queries) MarkVMFailed(ctx context.Context, arg MarkVMFailedParams) error {
	_, err := q.db.Exec(ctx, markVMFailed, arg.ID, arg.LastError)
	return err
}

const markVMRunning = `-- name: MarkVMRunning :exec
UPDATE vms
SET status     = 'running',
    vm_id      = $2,
    name       = $3,
    boot       = $4,
    cpus       = $5,
    memory_mib = $6,
    ip         = $7,
    last_error = '',
    started_at = now(),
    updated_at = now()
WHERE id = $1
`

type MarkVMRunningParams struct {
	ID        pgtype.UUID
	VMID      string
	Name      string
	Boot      string
	CPUs      int32
	MemoryMiB int32
	IP        string
}

// MarkVMRunning applies what the agent actually built: the id, name and address
// are allocated on the host, so they are only known once it answers.
func (q *Queries) MarkVMRunning(ctx context.Context, arg MarkVMRunningParams) error {
	_, err := q.db.Exec(ctx, markVMRunning,
		arg.ID,
		arg.VMID,
		arg.Name,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.IP,
	)
	return err
}

const setVMLastError = `-- name: SetVMLastError :exec
UPDATE vms
SET last_error = $2, updated_at = now()
WHERE id = $1
`

type SetVMLastErrorParams struct {
	ID        pgtype.UUID
	LastError string
}

// SetVMLastError records a failed action without changing the status. A stop
// that failed most likely leaves the VM running, so claiming otherwise would be
// worse than saying nothing.
func (q *Queries) SetVMLastError(ctx context.Context, arg SetVMLastErrorParams) error {
	_, err := q.db.Exec(ctx, setVMLastError, arg.ID, arg.LastError)
	return err
}

const setVMStatus = `-- name: SetVMStatus :exec
UPDATE vms
SET status = $2, last_error = '', reported_at = now(), updated_at = now()
WHERE id = $1
`

type SetVMStatusParams struct {
	ID     pgtype.UUID
	Status string
}

// SetVMStatus settles a start, stop or destroy as soon as the agent confirms it,
// rather than waiting up to a full inventory tick for the row to catch up.
//
// reported_at moves too. A result frame *is* the host vouching for this VM, at
// this moment, on the same socket an inventory report would use -- so treating
// it as older than it is would show a VM that was just confirmed as stale, which
// is both wrong and alarming. A host that dies immediately afterwards is still
// caught, by the ordinary staleness window.
func (q *Queries) SetVMStatus(ctx context.Context, arg SetVMStatusParams) error {
	_, err := q.db.Exec(ctx, setVMStatus, arg.ID, arg.Status)
	return err
}

const sumActiveVMUsageByOwner = `-- name: SumActiveVMUsageByOwner :one
SELECT COALESCE(SUM(cpus), 0)::int AS cpus,
       COALESCE(SUM(memory_mib), 0)::int AS memory_mib
FROM vms
WHERE created_by = $1
  AND status IN ('pending', 'running', 'stopped')
`

type SumActiveVMUsageByOwnerRow struct {
	CPUs      int32
	MemoryMiB int32
}

// SumActiveVMUsageByOwner totals what a user is currently holding, for the
// quota check on create.
//
// 'failed' and 'gone' are excluded: neither has anything running on a host, so
// counting them would let a run of failed creates permanently consume someone's
// allowance. 'pending' IS counted -- it is a create in flight, and leaving it
// out lets concurrent requests each see room that only one of them can have.
func (q *Queries) SumActiveVMUsageByOwner(ctx context.Context, createdBy pgtype.UUID) (SumActiveVMUsageByOwnerRow, error) {
	row := q.db.QueryRow(ctx, sumActiveVMUsageByOwner, createdBy)
	var i SumActiveVMUsageByOwnerRow
	err := row.Scan(&i.CPUs, &i.MemoryMiB)
	return i, err
}

const upsertVMFromInventory = `-- name: UpsertVMFromInventory :exec
INSERT INTO vms (agent_id, vm_id, name, status, boot, cpus, memory_mib, ip, created_at, started_at, reported_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (agent_id, vm_id) WHERE vm_id <> '' DO UPDATE
SET name        = EXCLUDED.name,
    status      = EXCLUDED.status,
    boot        = EXCLUDED.boot,
    cpus        = EXCLUDED.cpus,
    memory_mib  = EXCLUDED.memory_mib,
    ip          = EXCLUDED.ip,
    started_at  = COALESCE(vms.started_at, EXCLUDED.started_at),
    reported_at = now(),
    updated_at  = now()
`

type UpsertVMFromInventoryParams struct {
	AgentID   pgtype.UUID
	VMID      string
	Name      string
	Status    string
	Boot      string
	CPUs      int32
	MemoryMiB int32
	IP        string
	CreatedAt pgtype.Timestamptz
	StartedAt pgtype.Timestamptz
}

// UpsertVMFromInventory records what an agent reports it is actually running.
// This is how a VM created locally with `dagent vm create` gets adopted: the
// control plane learns about it the same way it learns about one it asked for.
//
// created_at comes from the host, not from now(): the VM's age is a fact about
// the guest, not about when this server first heard of it. started_at is kept if
// we already knew it, since the host does not report when a boot happened.
func (q *Queries) UpsertVMFromInventory(ctx context.Context, arg UpsertVMFromInventoryParams) error {
	_, err := q.db.Exec(ctx, upsertVMFromInventory,
		arg.AgentID,
		arg.VMID,
		arg.Name,
		arg.Status,
		arg.Boot,
		arg.CPUs,
		arg.MemoryMiB,
		arg.IP,
		arg.CreatedAt,
		arg.StartedAt,
	)
	return err
}
