FROM golang:1.26.5-trixie

RUN set -ex \
  && apt update \
  && apt install -y \
    git \
    curl \
    bash \
    unzip \
  && go install "github.com/air-verse/air@v1.67.1" \
  && go install "github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1" \
  && go install "github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc5" \
  && curl -fsSL https://bun.com/install | bash -s "bun-v1.4.0"

ENV PATH="/root/.bun/bin:${PATH}"

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
