package main

import (
  "context"
  "fmt"
  "log"
  "regexp"
  "strings"

  "github.com/google/uuid"
  "github.com/jackc/pgx/v5/pgtype"

  "control/internal/db"
  "control/internal/proto"
)

// proxy routes an inbound ssh session by which key authenticated it, so its user
// list is "who owns which VM" -- a fact that only exists in the control plane.
// It is compiled here for the same reason the Suricata ruleset is: one host holds
// one proxy for every guest on it, so the file is a property of the fleet rather
// than of any one VM, and there is exactly one implementation of what an entry
// means.
//
// The whole file is generated. The agent writes what it is given rather than
// merging, because a merge on the host would be a second opinion about the file
// in the one place that cannot be audited from here.
//
// Both routed blocks come from the control plane and from nowhere else. ssh is
// keyed by public key, so its entries say who may reach which guest. http is
// keyed by "<vm name>.<domain>", and neither half is the host's to know: the
// name is unique across the whole fleet, which no single machine can establish,
// and the domain belongs to the agent's row here.

// proxySSHListen is where proxy accepts guest ssh. Fixed rather than configurable
// for now: the port is the same on every host, and a per-host value would have to
// reach the user somehow before it is worth having.
const proxySSHListen = "0.0.0.0:22"

// proxyRemoteUser is the account inside the guest. Every image this fleet builds
// has the same one, and it is the user whose authorized_keys dagent writes at
// image build time -- so a different value here would point at an account that
// has no key in it.
const proxyRemoteUser = "ubuntu"

// proxyGuestSSHPort is sshd in the guest. Not the listen port above: proxy
// accepts on 22 and dials 22.
const proxyGuestSSHPort = 22

// proxyHTTPListen is where proxy accepts guest http, virtual-hosted by the
// Host header. Fixed for the same reason the ssh listener is.
//
// 80 is privileged, so proxy has to be able to bind it -- root, or
// CAP_NET_BIND_SERVICE on the unit. That is a property of the agent host, not of
// this file, and it is the thing that breaks if it is not true.
const proxyHTTPListen = "0.0.0.0:80"

// proxyConfigHeader says the file is not the operator's, because it looks
// exactly like the one that used to be.
const proxyConfigHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full whenever the set of VMs on this host changes, so
# a local edit survives only until the next change and then vanishes without
# warning.
#
# The ssh users below are derived from which user created which VM: a session is
# routed to a VM by the key it authenticated with.
#
# The http hosts below are each a VM's name under this host's domain: a request
# is routed to a VM by the Host header it carries.
`

// proxyStaticConfig is everything the control plane does not derive. It matches
// the defaults dagent would have written itself; it is repeated here because the
// server now owns the whole file, and a file with only an ssh block in it is not
// a proxy config.
const proxyStaticConfig = `
control_socket: /run/dpipe/control.sock
`

const proxyConfigFooter = `
dial_timeout: 5s
http_sniff_timeout: 5s
http_sniff_max_bytes: 65536
log_level: info
`

// proxyCookieSecretPath is where the agent writes the shared key and where proxy
// reads it. A path rather than the value inline: proxy.yaml is world-readable on
// the host, and the key is what tokens for every guest on it are signed with.
const proxyCookieSecretPath = "/etc/dpipe/keys/cookie_secret"

// proxyCookieTTL is how long the session cookie proxy sets after verifying a
// token is good for. Much longer than the token's five minutes on purpose: the
// token is the hand-off, this is the session it buys.
const proxyCookieTTL = "1h"

// generateProxyConfig compiles every reachable VM on one host into a proxy.yaml.
// Rows arrive in the order the queries fix, so an unchanged fleet compiles to a
// byte-identical file -- which is what lets the agent skip the restart.
func generateProxyConfig(auth proxyAuthConfig, ssh []db.ListProxySSHUsersByAgentRow, http []db.ListProxyHTTPRoutesByAgentRow) string {
  var b strings.Builder
  b.WriteString(proxyConfigHeader)
  b.WriteString(proxyStaticConfig)
  writeProxyAuth(&b, auth)
  writeProxyHTTP(&b, http)
  writeProxySSH(&b, ssh)
  b.WriteString(proxyConfigFooter)
  return b.String()
}

// writeProxyAuth emits the block that points proxy back at this server: where to
// send a browser that has no session cookie for a guest, and where to find the
// key the token it comes back with is signed with.
//
// Omitted entirely when no key is configured, rather than written with an empty
// secret path: a half-filled auth block would have proxy send users to a /login
// that cannot mint anything, which fails at the end of a redirect chain instead
// of not being offered at all. Without it proxy serves guests as it did before.
func writeProxyAuth(b *strings.Builder, auth proxyAuthConfig) {
  if auth.secret == "" {
    return
  }
  b.WriteString("\nauth:\n")
  fmt.Fprintf(b, "  control_url: %s\n", yamlString(auth.loginURL()))
  fmt.Fprintf(b, "  cookie_secret_file: %s\n", yamlString(proxyCookieSecretPath))
  fmt.Fprintf(b, "  cookie_ttl: %s\n", proxyCookieTTL)
  // false in dev: guests are plain http there, and a browser drops a Secure
  // cookie sent over http -- which reads as "login did nothing".
  fmt.Fprintf(b, "  cookie_secure: %t\n", auth.cookieSecure)
}

// writeProxyHTTP emits the virtual-host table: one entry per VM, keyed by the
// VM's name under the domain of the agent running it, carrying its address, the
// ports it publishes and the one a request goes to when nothing picks.
func writeProxyHTTP(b *strings.Builder, rows []db.ListProxyHTTPRoutesByAgentRow) {
  b.WriteString("\nhttp:\n")
  fmt.Fprintf(b, "  listen: %q\n", proxyHTTPListen)
  b.WriteString("  reuseport: true\n")

  type route struct {
    host string
    row  db.ListProxyHTTPRoutesByAgentRow
  }
  usable := make([]route, 0, len(rows))
  for _, r := range rows {
    host := r.VMName + "." + r.DomainTLD
    // Both halves are server-controlled -- a name the database constrains and a
    // domain validated when the operator entered it -- so this should never
    // reject anything. It is here because the key is the one part of the file
    // that is not quoted, and a hostname that is not a hostname would be a way
    // to write structure into the document.
    if !hostnamePattern.MatchString(host) {
      log.Printf("skipping the http route for vm %s: %q is not a usable hostname", r.HostVMID, host)
      continue
    }
    usable = append(usable, route{host: host, row: r})
  }

  // An empty table is spelled as one for the same reason the ssh list is: on a
  // host with no reachable VMs, "nothing is published" and "hosts was never
  // configured" must not look alike.
  if len(usable) == 0 {
    b.WriteString("  hosts: {}\n")
  } else {
    b.WriteString("  hosts:\n")
    for _, u := range usable {
      fmt.Fprintf(b, "    %s:\n", u.host)
      fmt.Fprintf(b, "      host: %s\n", yamlString(u.row.VMIP))
      // `unauthenticated_ports` on the wire, `public_ports` everywhere else in
      // here: the file is what an operator reads to answer "what can be reached
      // without signing in", and "public" understates that. Only the emitted key
      // is renamed -- the column, the API and the UI still say public_ports.
      if len(u.row.PublicPorts) == 0 {
        // Spelled, not omitted, for the same reason as the table above: a VM
        // that publishes nothing is a fact, and it should not read as a VM
        // whose ports were never configured.
        b.WriteString("      unauthenticated_ports: []\n")
      } else {
        b.WriteString("      unauthenticated_ports:\n")
        for _, p := range u.row.PublicPorts {
          fmt.Fprintf(b, "        - %d\n", p)
        }
      }
      fmt.Fprintf(b, "      default_port: %d\n", u.row.DefaultPort)
    }
  }

  // Empty: an unmatched Host header asks for a name this host does not publish,
  // and sending it to some arbitrary guest would be worse than a miss.
  b.WriteString(`  default: ""` + "\n")
}

// hostnamePattern is the shape of a DNS name: dotted lowercase labels, each
// starting and ending alphanumeric. Used to validate the domains an operator
// enters; a VM name is the stricter vmNamePattern.
var hostnamePattern = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$`)

func writeProxySSH(b *strings.Builder, rows []db.ListProxySSHUsersByAgentRow) {
  b.WriteString("\nssh:\n")
  fmt.Fprintf(b, "  listen: %q\n", proxySSHListen)
  b.WriteString("  reuseport: true\n")

  if len(rows) == 0 {
    // An empty list has to be spelled, not omitted: a missing `users` key would
    // read to proxy as "not configured" rather than "nobody may connect", and
    // the two should not look alike on a host whose VMs were all destroyed.
    b.WriteString("  users: []\n")
    return
  }

  b.WriteString("  users:\n")
  for _, r := range rows {
    fmt.Fprintf(b, "    # %s (%s)\n", yamlComment(r.VMName), yamlComment(r.HostVMID))
    fmt.Fprintf(b, "    - pubkey: %s\n", yamlString(r.PublicKey))
    fmt.Fprintf(b, "      target: %s\n", yamlString(fmt.Sprintf("%s:%d", r.VMIP, proxyGuestSSHPort)))
    fmt.Fprintf(b, "      remote_user: %s\n", yamlString(proxyRemoteUser))
  }
}

// yamlString emits a double-quoted YAML scalar. Quoted unconditionally rather
// than only when it looks necessary: a public key carries a user-supplied
// comment, and an unquoted scalar containing " #" silently truncates at that
// point -- which would leave a valid-looking key that is not the one on file.
func yamlString(s string) string {
  r := strings.NewReplacer(
    `\`, `\\`,
    `"`, `\"`,
    "\n", `\n`,
    "\r", `\r`,
    "\t", `\t`,
  )
  return `"` + r.Replace(s) + `"`
}

// yamlComment makes free text safe to sit after a '#'. Only newlines can end a
// comment, so that is all this has to remove -- but a name is a user-supplied
// string that ends up in a file a daemon parses, so it is removed rather than
// assumed absent.
func yamlComment(s string) string {
  out := strings.TrimSpace(strings.NewReplacer("\n", " ", "\r", " ").Replace(s))
  if out == "" {
    return "unnamed"
  }
  if len(out) > 120 {
    out = out[:120]
  }
  return out
}

// pushProxyConfig regenerates the host's proxy.yaml and sends it. Called after
// anything that changes which VMs are on the host or who owns them.
//
// Failures are logged rather than returned: the VM has already been recorded, and
// failing the caller would report that something did not happen when it did. An
// offline agent picks the config up on its next connect, which is why the connect
// path pushes one unconditionally.
func pushProxyConfig(ctx context.Context, q *db.Queries, hub *Hub, auth proxyAuthConfig, agentID pgtype.UUID) {
  id := uuid.UUID(agentID.Bytes).String()
  sshRows, err := q.ListProxySSHUsersByAgent(ctx, agentID)
  if err != nil {
    log.Printf("could not read the ssh routes for agent %s: %v", id, err)
    return
  }
  // A failure here is not survivable by pushing the ssh half alone: the file is
  // written whole, so that would publish an empty host table and take down every
  // http route on the host.
  httpRows, err := q.ListProxyHTTPRoutesByAgent(ctx, agentID)
  if err != nil {
    log.Printf("could not read the http routes for agent %s: %v", id, err)
    return
  }
  // The key rides with the config rather than being provisioned separately: the
  // file it lands in is named by the config, so a host that has one and not the
  // other has an auth block pointing at a key that is not there.
  env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
    Kind: proto.KindProxyConfig,
    Proxy: &proto.ProxyConfig{
      Config:           generateProxyConfig(auth, sshRows, httpRows),
      CookieSecret:     auth.secret,
      CookieSecretPath: proxyCookieSecretPath,
    },
  })
  if err != nil {
    log.Printf("could not build the proxy config job for agent %s: %v", id, err)
    return
  }
  // A send failure is expected whenever the host is down, and there is nothing
  // to retry: dagent is sent one as soon as it reconnects.
  if err := hub.Send(id, env); err != nil {
    log.Printf("could not deliver the proxy config to agent %s: %v", id, err)
  }
}
