package main

import (
  "context"
  "fmt"
  "log"
  "strings"

  "github.com/google/uuid"
  "github.com/jackc/pgx/v5/pgtype"

  "control/internal/db"
  "control/internal/proto"
)

// proxy routes an inbound ssh session by which key authenticated it, so its user
// list is "who owns which VM" -- a fact that only exists in the control plane.
// It is compiled here for the same reason the Suricata ruleset is: one host holds
// one proxy for every guest on it, so the file is a property of the fleet rather
// than of any one VM, and there is exactly one implementation of what an entry
// means.
//
// The whole file is generated, not just the ssh block. The agent writes what it
// is given rather than merging, because a merge on the host would be a second
// opinion about the file in the one place that cannot be audited from here.

// proxySSHListen is where proxy accepts guest ssh. Fixed rather than configurable
// for now: the port is the same on every host, and a per-host value would have to
// reach the user somehow before it is worth having.
const proxySSHListen = "0.0.0.0:2222"

// proxyRemoteUser is the account inside the guest. Every image this fleet builds
// has the same one, and it is the user whose authorized_keys dagent writes at
// image build time -- so a different value here would point at an account that
// has no key in it.
const proxyRemoteUser = "ubuntu"

// proxyGuestSSHPort is sshd in the guest. Not the listen port above: proxy
// accepts on 2222 and dials 22.
const proxyGuestSSHPort = 22

// proxyConfigHeader says the file is not the operator's, because it looks
// exactly like the one that used to be.
const proxyConfigHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full whenever the set of VMs on this host changes, so
# a local edit survives only until the next change and then vanishes without
# warning.
#
# The ssh users below are derived from which user created which VM: a session is
# routed to a VM by the key it authenticated with.
`

// proxyStaticConfig is everything the control plane does not derive. It matches
// the defaults dagent would have written itself; it is repeated here because the
// server now owns the whole file, and a file with only an ssh block in it is not
// a proxy config.
const proxyStaticConfig = `
control_socket: /run/dpipe/control.sock

http:
  listen: "0.0.0.0:8080"
  reuseport: true
  hosts: {}
  default: ""
`

const proxyConfigFooter = `
dial_timeout: 5s
http_sniff_timeout: 5s
http_sniff_max_bytes: 65536
log_level: info
`

// generateProxyConfig compiles every reachable VM on one host into a proxy.yaml.
// Rows arrive in the order the query fixes, so an unchanged fleet compiles to a
// byte-identical file -- which is what lets the agent skip the restart.
func generateProxyConfig(rows []db.ListProxySSHUsersByAgentRow) string {
  var b strings.Builder
  b.WriteString(proxyConfigHeader)
  b.WriteString(proxyStaticConfig)

  b.WriteString("\nssh:\n")
  fmt.Fprintf(&b, "  listen: %q\n", proxySSHListen)
  b.WriteString("  reuseport: true\n")

  if len(rows) == 0 {
    // An empty list has to be spelled, not omitted: a missing `users` key would
    // read to proxy as "not configured" rather than "nobody may connect", and
    // the two should not look alike on a host whose VMs were all destroyed.
    b.WriteString("  users: []\n")
    b.WriteString(proxyConfigFooter)
    return b.String()
  }

  b.WriteString("  users:\n")
  for _, r := range rows {
    fmt.Fprintf(&b, "    # %s (%s)\n", yamlComment(r.VMName), yamlComment(r.HostVMID))
    fmt.Fprintf(&b, "    - pubkey: %s\n", yamlString(r.PublicKey))
    fmt.Fprintf(&b, "      target: %s\n", yamlString(fmt.Sprintf("%s:%d", r.VMIP, proxyGuestSSHPort)))
    fmt.Fprintf(&b, "      remote_user: %s\n", yamlString(proxyRemoteUser))
  }

  b.WriteString(proxyConfigFooter)
  return b.String()
}

// yamlString emits a double-quoted YAML scalar. Quoted unconditionally rather
// than only when it looks necessary: a public key carries a user-supplied
// comment, and an unquoted scalar containing " #" silently truncates at that
// point -- which would leave a valid-looking key that is not the one on file.
func yamlString(s string) string {
  r := strings.NewReplacer(
    `\`, `\\`,
    `"`, `\"`,
    "\n", `\n`,
    "\r", `\r`,
    "\t", `\t`,
  )
  return `"` + r.Replace(s) + `"`
}

// yamlComment makes free text safe to sit after a '#'. Only newlines can end a
// comment, so that is all this has to remove -- but a name is a user-supplied
// string that ends up in a file a daemon parses, so it is removed rather than
// assumed absent.
func yamlComment(s string) string {
  out := strings.TrimSpace(strings.NewReplacer("\n", " ", "\r", " ").Replace(s))
  if out == "" {
    return "unnamed"
  }
  if len(out) > 120 {
    out = out[:120]
  }
  return out
}

// pushProxyConfig regenerates the host's proxy.yaml and sends it. Called after
// anything that changes which VMs are on the host or who owns them.
//
// Failures are logged rather than returned: the VM has already been recorded, and
// failing the caller would report that something did not happen when it did. An
// offline agent picks the config up on its next connect, which is why the connect
// path pushes one unconditionally.
func pushProxyConfig(ctx context.Context, q *db.Queries, hub *Hub, agentID pgtype.UUID) {
  id := uuid.UUID(agentID.Bytes).String()
  rows, err := q.ListProxySSHUsersByAgent(ctx, agentID)
  if err != nil {
    log.Printf("could not read the vms for agent %s: %v", id, err)
    return
  }
  env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
    Kind:  proto.KindProxyConfig,
    Proxy: &proto.ProxyConfig{Config: generateProxyConfig(rows)},
  })
  if err != nil {
    log.Printf("could not build the proxy config job for agent %s: %v", id, err)
    return
  }
  // A send failure is expected whenever the host is down, and there is nothing
  // to retry: dagent is sent one as soon as it reconnects.
  if err := hub.Send(id, env); err != nil {
    log.Printf("could not deliver the proxy config to agent %s: %v", id, err)
  }
}
