package main

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"html"
	"log"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"control/internal/db"
	"control/internal/proto"
)

const proxySSHListen = "0.0.0.0:22"

const proxyRemoteUser = "ubuntu"

const proxyGuestSSHPort = 22

const proxyRDPListen = "0.0.0.0:3389"

const proxyGuestRDPPort = 3389

const proxyDesktopLabel = "desk"

const proxyHTTPListen = "0.0.0.0:80"

const proxyHTTPSListen = "0.0.0.0:443"

const proxyConfigHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full whenever the set of VMs on this host changes, so
# a local edit survives only until the next change and then vanishes without
# warning.
#
# The ssh users below are derived from which user created which VM: a session is
# routed to a VM by the key it authenticated with and the vm_name it asked for as
# the ssh login name, so "ssh amazing-jepsen@<host>" reaches the VM of that name
# if the key owns it.
#
# The http hosts below are each a VM's name under this host's domain: a request
# is routed to a VM by the Host header it carries.
`

const proxyStaticConfig = `
control_socket: /run/dpipe/control.sock
`

const proxyConfigFooter = `
dial_timeout: 5s
http_sniff_timeout: 5s
http_sniff_max_bytes: 65536
log_level: info
`

const proxyConsoleLabel = "shell"

const proxySiteLabel = "www"

const proxySiteListen = "127.0.0.1:8079"

const proxySitePath = "/etc/dclient/dproxy-site.html"

//go:embed site/index.html
var proxySiteTemplate string

const proxySiteControlPlaceholder = "{{CONTROL_URL}}"

func proxySitePage(controlURL string) string {
	url := strings.TrimRight(strings.TrimSpace(controlURL), "/")
	return strings.ReplaceAll(proxySiteTemplate, proxySiteControlPlaceholder, html.EscapeString(url))
}

const proxyACMEChallengeTarget = "127.0.0.1:8078"

const proxyCookieSecretPath = "/etc/dpipe/keys/cookie_secret"

const proxyCookieTTL = "1h"

type proxyHost struct {
	tld string
	tls bool
}

func generateProxyConfig(auth proxyAuthConfig, host proxyHost, ssh []db.ListProxySSHUsersByClientRow, http []db.ListProxyHTTPRoutesByClientRow, custom []db.ListCustomDomainRoutesByClientRow, rdp []db.ListProxyRDPUsersByClientRow) string {
	// A fleet with no wildcard can still hold a certificate for a custom
	// domain, and that domain is only reachable if the https ingress is up.
	tls := host.tls || len(custom) > 0
	auth.cookieSecure = auth.cookieSecure || tls

	var b strings.Builder
	b.WriteString(proxyConfigHeader)
	b.WriteString(proxyStaticConfig)
	writeProxyAuth(&b, auth)
	writeProxyConsole(&b, auth)
	writeProxyHTTP(&b, http, custom)
	writeProxyACME(&b)
	writeProxyHTTPS(&b, tls)
	writeProxySite(&b, host.tld)
	writeProxySSH(&b, ssh)
	writeProxyRDP(&b, auth, rdp)
	b.WriteString(proxyConfigFooter)
	return b.String()
}

func clientProxyHost(ctx context.Context, q *db.Queries, clientID pgtype.UUID) (proxyHost, error) {
	domain, err := q.GetClientDomain(ctx, clientID)
	if errors.Is(err, pgx.ErrNoRows) {
		return proxyHost{}, nil
	}
	if err != nil {
		return proxyHost{}, err
	}
	return proxyHost{tld: domain.TLD, tls: domain.TlsEnabled && domain.CertObjectKey != ""}, nil
}

func writeProxyAuth(b *strings.Builder, auth proxyAuthConfig) {
	if auth.secret == "" {
		return
	}
	b.WriteString("\nauth:\n")
	fmt.Fprintf(b, "  control_url: %s\n", yamlString(auth.loginURL()))
	fmt.Fprintf(b, "  cookie_secret_file: %s\n", yamlString(proxyCookieSecretPath))
	fmt.Fprintf(b, "  cookie_ttl: %s\n", proxyCookieTTL)
	fmt.Fprintf(b, "  cookie_secure: %t\n", auth.cookieSecure)
	fmt.Fprintf(b, "  cookie_samesite: %s\n", auth.cookieSameSite())
}

func writeProxyConsole(b *strings.Builder, auth proxyAuthConfig) {
	if auth.secret == "" {
		return
	}
	b.WriteString("\nconsole:\n")
	fmt.Fprintf(b, "  label: %s\n", yamlString(proxyConsoleLabel))
	fmt.Fprintf(b, "  remote_user: %s\n", yamlString(proxyRemoteUser))

	b.WriteString("\ndesktop:\n")
	fmt.Fprintf(b, "  label: %s\n", yamlString(proxyDesktopLabel))
	fmt.Fprintf(b, "  remote_user: %s\n", yamlString(rdpGuestUser))
	fmt.Fprintf(b, "  remote_password: %s\n", yamlString(rdpGuestPass))
}

type proxyRoute struct {
	host        string
	ip          string
	defaultPort int32
	publicPorts []int32
}

func writeProxyHTTP(b *strings.Builder, rows []db.ListProxyHTTPRoutesByClientRow, custom []db.ListCustomDomainRoutesByClientRow) {
	b.WriteString("\nhttp:\n")
	fmt.Fprintf(b, "  listen: %q\n", proxyHTTPListen)
	b.WriteString("  reuseport: true\n")

	usable := make([]proxyRoute, 0, len(rows)+len(custom))
	for _, r := range rows {
		host := r.VMName + "." + r.DomainTLD
		if !hostnamePattern.MatchString(host) {
			log.Printf("skipping the http route for vm %s: %q is not a usable hostname", r.HostVMID, host)
			continue
		}
		usable = append(usable, proxyRoute{
			host: host, ip: r.VMIP, defaultPort: r.DefaultPort, publicPorts: r.PublicPorts,
		})
	}
	for _, r := range custom {
		if !hostnamePattern.MatchString(r.Domain) {
			log.Printf("skipping the custom domain route for vm %s: %q is not a usable hostname", r.VMName, r.Domain)
			continue
		}
		usable = append(usable, proxyRoute{
			host: r.Domain, ip: r.VMIP, defaultPort: r.DefaultPort, publicPorts: r.PublicPorts,
		})
	}

	if len(usable) == 0 {
		b.WriteString("  hosts: {}\n")
	} else {
		b.WriteString("  hosts:\n")
		for _, u := range usable {
			fmt.Fprintf(b, "    %s:\n", u.host)
			fmt.Fprintf(b, "      host: %s\n", yamlString(u.ip))
			if len(u.publicPorts) == 0 {
				b.WriteString("      unauthenticated_ports: []\n")
			} else {
				b.WriteString("      unauthenticated_ports:\n")
				for _, p := range u.publicPorts {
					fmt.Fprintf(b, "        - %d\n", p)
				}
			}
			fmt.Fprintf(b, "      default_port: %d\n", u.defaultPort)
		}
	}

	b.WriteString(`  default: ""` + "\n")
}

// writeProxyACME publishes the one path that must answer before a custom
// domain has a certificate: dclient holds a listener there for the length of
// an order and nothing else in the fleet listens on it.
func writeProxyACME(b *strings.Builder) {
	b.WriteString("\nacme:\n")
	fmt.Fprintf(b, "  challenge_target: %s\n", yamlString(proxyACMEChallengeTarget))
}

func writeProxyHTTPS(b *strings.Builder, tls bool) {
	if !tls {
		return
	}
	b.WriteString("\nhttps:\n")
	fmt.Fprintf(b, "  listen: %q\n", proxyHTTPSListen)
	b.WriteString("  reuseport: true\n")
}

func writeProxySite(b *strings.Builder, tld string) {
	if tld == "" {
		return
	}
	host := proxySiteLabel + "." + tld
	if !hostnamePattern.MatchString(host) {
		log.Printf("skipping the site host: %q is not a usable hostname", host)
		return
	}
	b.WriteString("\nsite:\n")
	fmt.Fprintf(b, "  listen: %s\n", yamlString(proxySiteListen))
	fmt.Fprintf(b, "  html_file: %s\n", yamlString(proxySitePath))
	b.WriteString("  hosts:\n")
	fmt.Fprintf(b, "    - %s\n", yamlString(host))
}

var hostnamePattern = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$`)

func writeProxySSH(b *strings.Builder, rows []db.ListProxySSHUsersByClientRow) {
	if len(rows) == 0 {
		return
	}

	b.WriteString("\nssh:\n")
	fmt.Fprintf(b, "  listen: %q\n", proxySSHListen)
	b.WriteString("  reuseport: true\n")
	b.WriteString("  users:\n")
	for _, r := range rows {
		fmt.Fprintf(b, "    # %s\n", yamlComment(r.HostVMID))
		fmt.Fprintf(b, "    - pubkey: %s\n", yamlString(r.PublicKey))
		fmt.Fprintf(b, "      vm_name: %s\n", yamlString(r.VMName))
		fmt.Fprintf(b, "      target: %s\n", yamlString(fmt.Sprintf("%s:%d", r.VMIP, proxyGuestSSHPort)))
		fmt.Fprintf(b, "      remote_user: %s\n", yamlString(proxyRemoteUser))
	}
}

// writeProxyRDP emits the native remote-desktop policy: one entry per VM, keyed
// by the login name the client authenticates with. Only the NT hash is shipped,
// so the file on the host holds no password a person could reuse elsewhere.
//
// Without an auth secret there is nothing to derive a credential from, so the
// ingress is omitted entirely and the port stays closed — the same gate the
// console uses.
func writeProxyRDP(b *strings.Builder, auth proxyAuthConfig, rows []db.ListProxyRDPUsersByClientRow) {
	if auth.secret == "" || len(rows) == 0 {
		return
	}

	b.WriteString("\nrdp:\n")
	fmt.Fprintf(b, "  listen: %q\n", proxyRDPListen)
	b.WriteString("  reuseport: true\n")
	b.WriteString("  users:\n")
	for _, r := range rows {
		vmID := uuid.UUID(r.VmPk.Bytes).String()
		fmt.Fprintf(b, "    # %s\n", yamlComment(r.HostVMID))
		fmt.Fprintf(b, "    - vm_name: %s\n", yamlString(r.VMName))
		fmt.Fprintf(b, "      nt_hash: %s\n", yamlString(rdpNTHash(rdpPassword(auth.secret, vmID, r.RdpNonce))))
		fmt.Fprintf(b, "      target: %s\n", yamlString(fmt.Sprintf("%s:%d", r.VMIP, proxyGuestRDPPort)))
		fmt.Fprintf(b, "      remote_user: %s\n", yamlString(rdpGuestUser))
		fmt.Fprintf(b, "      remote_password: %s\n", yamlString(rdpGuestPass))
	}
}

func yamlString(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

func yamlComment(s string) string {
	out := strings.TrimSpace(strings.NewReplacer("\n", " ", "\r", " ").Replace(s))
	if out == "" {
		return "unnamed"
	}
	if len(out) > 120 {
		out = out[:120]
	}
	return out
}

func pushProxyConfig(ctx context.Context, q *db.Queries, hub *Hub, auth proxyAuthConfig, clientID pgtype.UUID) {
	id := uuid.UUID(clientID.Bytes).String()
	sshRows, err := q.ListProxySSHUsersByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the ssh routes for client %s: %v", id, err)
		return
	}
	httpRows, err := q.ListProxyHTTPRoutesByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the http routes for client %s: %v", id, err)
		return
	}
	customRows, err := q.ListCustomDomainRoutesByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the custom domains for client %s: %v", id, err)
		return
	}
	rdpRows, err := q.ListProxyRDPUsersByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the rdp routes for client %s: %v", id, err)
		return
	}
	host, err := clientProxyHost(ctx, q, clientID)
	if err != nil {
		log.Printf("could not read the domain of client %s, writing its proxy config without tls: %v", id, err)
	}
	env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
		Kind: proto.KindProxyConfig,
		Proxy: &proto.ProxyConfig{
			Config:           generateProxyConfig(auth, host, sshRows, httpRows, customRows, rdpRows),
			CookieSecret:     auth.secret,
			CookieSecretPath: proxyCookieSecretPath,
			SiteHTML: proxySitePage(auth.controlURL),
			SitePath: proxySitePath,
		},
	})
	if err != nil {
		log.Printf("could not build the proxy config job for client %s: %v", id, err)
		return
	}
	if err := hub.Send(id, env); err != nil {
		log.Printf("could not deliver the proxy config to client %s: %v", id, err)
	}
}
