package main

import (
  "context"
  "fmt"
  "log"
  "strings"

  "github.com/google/uuid"
  "github.com/jackc/pgx/v5/pgtype"

  "control/internal/db"
  "control/internal/proto"
)

// The allowed destinations a user records against a VM are compiled here, not
// on the host. A host holds one Suricata for every guest on it, so the file is
// a property of the fleet rather than of any one VM -- and generating it in one
// place means there is exactly one implementation of "what does this allowance
// mean", which is the part that has to be right.
//
// Scoping is by source address. Every pass rule names the VM's IP in its
// header, so an allowance granted to one guest cannot be used by the guest next
// to it; the denies below stay written against $HOME_NET, which is the whole
// pool, so a VM the control plane has never heard of is still covered.

// Sid ranges. The denies are fixed so they can be recognised in a log line
// across hosts and regenerations; the passes start above them and are numbered
// in the order they are emitted, which the query fixes.
const (
  suricataDenySidBase = 1000010
  suricataPassSidBase = 1000100
)

// suricataDenyRules is the floor every generated file ends with: nothing leaves
// a VM unless a pass rule above matched it.
//
// Only the VM-to-outside direction of a flow reaches the queues -- return
// traffic is accepted by conntrack and Suricata never sees it -- so every
// verdict here is made on a to-server packet and a drop ends the flow.
//
// There is deliberately no blanket `drop ip`: a TCP SYN carries no destination
// name, so dropping it would kill the connection before the ClientHello that
// proves where it was going ever arrives. The deny is split instead -- ports at
// the SYN, names at the handshake -- and the pass rules win where they overlap,
// because Suricata evaluates pass before drop regardless of sid order.
const suricataDenyRules = `# --- default deny ---------------------------------------------------------
# $HOME_NET is the VM pool, so these judge guest traffic only; the host's own is
# never queued. They are written against the whole pool rather than per VM so
# that a guest the control plane does not know about is denied too.

# Everything that is not tcp. Safe to judge per packet: a udp or icmp packet is
# self-describing, so there is no handshake to preserve. A pass dns rule above
# still gets its query out, since pass is evaluated first.
drop ip $HOME_NET any -> any any (msg:"dagent: deny non-tcp"; ip_proto:!tcp; sid:1000010; rev:1;)

# tcp to anything but the web ports, judged at the syn.
drop tcp $HOME_NET any -> any ![80,443] (msg:"dagent: deny tcp to a non-web port"; sid:1000011; rev:1;)

# On the web ports the destination is only knowable once the request is parsed,
# so these fire on the clienthello or the request line -- one packet in, before
# any payload has left the host.
drop tls $HOME_NET any -> any any (msg:"dagent: deny tls to another host"; sid:1000012; rev:1;)
drop http $HOME_NET any -> any any (msg:"dagent: deny http to another host"; sid:1000013; rev:1;)

# A tunnel on 80 or 443 that is neither http nor tls would otherwise match no
# rule at all and pass by default. app-layer-protocol:failed is detection having
# run and come up with nothing, not detection still pending, so this does not
# catch the handshake.
drop tcp $HOME_NET any -> any [80,443] (msg:"dagent: deny non-web traffic on a web port"; app-layer-protocol:failed; sid:1000014; rev:1;)
`

const suricataRulesHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full every time the allowed destinations of any VM on
# this host change, so a local edit survives only until the next change and then
# vanishes without warning. Record destinations against the VM in the control
# plane instead.
#
# Default deny: the rules at the bottom drop everything, and each pass rule
# above them is scoped to one VM by the source address in its header.
`

// generateSuricataRules compiles every allowance on one host into a local.rules
// for Suricata 8. Rows are expected in the order the query returns them, which
// groups them by VM address -- the output is therefore deterministic for a given
// database state, so an unchanged policy compiles to a byte-identical file.
func generateSuricataRules(rows []db.ListVMNetworkTargetsByAgentRow) string {
  var b strings.Builder
  b.WriteString(suricataRulesHeader)

  sid := suricataPassSidBase
  lastVM := ""
  for _, r := range rows {
    if r.VMIP != lastVM {
      lastVM = r.VMIP
      fmt.Fprintf(&b, "\n# --- allowed for %s (%s) at %s ---\n",
        ruleText(r.VMName), ruleText(r.HostVMID), r.VMIP)
    }
    for _, rule := range targetRules(r, &sid) {
      b.WriteString(rule)
      b.WriteByte('\n')
    }
  }

  b.WriteString("\n")
  b.WriteString(suricataDenyRules)
  return b.String()
}

// targetRules turns one allowance into the rules that express it, consuming a
// sid per rule. A domain needs three -- the lookup, and then each of the two
// protocols that carry a hostname -- because there is no single buffer that
// covers all of them.
func targetRules(r db.ListVMNetworkTargetsByAgentRow, sid *int) []string {
  msg := ruleMsg(r)
  next := func() int { s := *sid; *sid++; return s }

  if r.Kind == "domain" {
    // dotprefix prepends a "." to the buffer, so `content:".example.com";
    // endswith` matches example.com and any subdomain of it but not
    // notexample.com -- which a bare endswith would let through.
    //
    // No nocase on http.host: that buffer is already normalised to lowercase,
    // and Suricata 8 rejects the rule outright rather than warning. The other
    // two are not normalised, so they need it.
    dot := "." + r.Destination
    return []string{
      fmt.Sprintf(`pass dns %s any -> any any (msg:"%s (dns)"; dns.query; dotprefix; content:"%s"; nocase; endswith; sid:%d; rev:1;)`,
        r.VMIP, msg, dot, next()),
      fmt.Sprintf(`pass tls %s any -> any any (msg:"%s (tls)"; tls.sni; dotprefix; content:"%s"; nocase; endswith; sid:%d; rev:1;)`,
        r.VMIP, msg, dot, next()),
      fmt.Sprintf(`pass http %s any -> any any (msg:"%s (http)"; http.host; dotprefix; content:"%s"; endswith; sid:%d; rev:1;)`,
        r.VMIP, msg, dot, next()),
    }
  }

  ports := r.Ports
  switch {
  case ports == "":
    ports = "any"
  case strings.Contains(ports, ","):
    // A list is only a list to Suricata inside brackets; bare `80,443` in a
    // header is a parse error, and a parse error takes the whole file down --
    // every other VM's policy with it.
    ports = "[" + ports + "]"
  }
  // Ports are a transport concept, so `ip` -- which is how "either transport"
  // is spelled in a rule header -- can only be used when no port was asked for.
  // With one, the same allowance has to be written once per transport.
  protos := []string{r.Transport}
  if r.Transport == "any" {
    if ports == "any" {
      protos = []string{"ip"}
    } else {
      protos = []string{"tcp", "udp"}
    }
  }

  rules := make([]string, 0, len(protos))
  for _, p := range protos {
    rules = append(rules, fmt.Sprintf(`pass %s %s any -> %s %s (msg:"%s"; sid:%d; rev:1;)`,
      p, r.VMIP, r.Destination, ports, msg, next()))
  }
  return rules
}

// ruleMsg is what shows up in the alert log. The note is included because an
// allowance nobody can explain is one nobody can safely prune later, and this is
// where an operator reading logs will meet it.
func ruleMsg(r db.ListVMNetworkTargetsByAgentRow) string {
  msg := fmt.Sprintf("dagent: allow %s from %s", ruleText(r.Destination), ruleText(r.VMName))
  if r.Note != "" {
    msg += " -- " + ruleText(r.Note)
  }
  return msg
}

// ruleText makes a free-text field safe to sit inside a rule option. A quote
// ends the msg early and a semicolon ends the option, either of which turns one
// bad note into a ruleset Suricata refuses to load -- and with it every other
// VM's policy on the host.
var ruleTextReplacer = strings.NewReplacer(
  `"`, "'", ";", ",", `\`, "/", "\n", " ", "\r", " ",
)

func ruleText(s string) string {
  out := strings.TrimSpace(ruleTextReplacer.Replace(s))
  if out == "" {
    return "unnamed"
  }
  if len(out) > 120 {
    out = out[:120]
  }
  return out
}

// pushSuricataRules regenerates the host's ruleset and sends it. Called after
// anything that changes what a VM on that host is allowed to reach.
//
// Failures are logged rather than returned to the caller: the destination has
// already been recorded, and failing the request would tell the user their
// change did not happen when it did. An offline agent picks the ruleset up when
// it reconnects, since dagent asks for one on connect.
func pushSuricataRules(ctx context.Context, q *db.Queries, hub *Hub, agentID pgtype.UUID) {
  id := uuid.UUID(agentID.Bytes).String()
  rows, err := q.ListVMNetworkTargetsByAgent(ctx, agentID)
  if err != nil {
    log.Printf("could not read the allowed destinations for agent %s: %v", id, err)
    return
  }
  env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
    Kind:     proto.KindSuricataRules,
    Suricata: &proto.SuricataRules{Rules: generateSuricataRules(rows)},
  })
  if err != nil {
    log.Printf("could not build the suricata rules job for agent %s: %v", id, err)
    return
  }
  // A send failure is expected whenever the host is down, and there is nothing
  // to retry: dagent asks for the ruleset itself as soon as it reconnects.
  if err := hub.Send(id, env); err != nil {
    log.Printf("could not deliver the suricata ruleset to agent %s: %v", id, err)
  }
}
