package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"control/internal/db"
	"control/internal/proto"
)

// The allowed destinations a user records against a VM are compiled here, not
// on the host. A host holds one Suricata for every guest on it, so the file is
// a property of the fleet rather than of any one VM -- and generating it in one
// place means there is exactly one implementation of "what does this allowance
// mean", which is the part that has to be right.
//
// Scoping is by source address. Every pass rule names the VM's IP in its
// header, so an allowance granted to one guest cannot be used by the guest next
// to it; the denies below stay written against $HOME_NET, which is the whole
// pool, so a VM the control plane has never heard of is still covered.

// Sid ranges. The denies are fixed so they can be recognised in a log line
// across hosts and regenerations; the passes start above them and are numbered
// in the order they are emitted, which the query fixes.
const (
	suricataDenySidBase = 1000010
	suricataPassSidBase = 1000100
)

// suricataDenyRules is the floor every generated file ends with: nothing leaves
// a VM unless a pass rule above matched it.
//
// Only the VM-to-outside direction of a flow reaches the queues -- return
// traffic is accepted by conntrack and Suricata never sees it -- so every
// verdict here is made on a to-server packet and a drop ends the flow.
//
// There is deliberately no blanket `drop ip`: a TCP SYN carries no destination
// name, so dropping it would kill the connection before the ClientHello that
// proves where it was going ever arrives. The deny is split instead -- ports at
// the SYN, names at the handshake -- and the pass rules win where they overlap,
// because Suricata evaluates pass before drop regardless of sid order.
//
// The cost of that split is the one hole this policy knowingly leaves: a
// handshake to any address on 80 or 443 completes, and its empty ACKs and FIN
// are never matched by anything. No payload can cross it -- the first packet
// carrying one is classified and dropped by the rules below unless it names an
// allowed host -- so what is left is a port scan and a very slow covert channel.
// Closing it needs the resolver to write each answer into an nftables set, which
// is a per-flow write this design deliberately does not make. A VM that has no
// name-based allowance gets a blanket deny instead and does not have the hole;
// see vmDenyRule.
const suricataDenyRules = `# --- default deny ---------------------------------------------------------
# $HOME_NET is the VM pool, so these judge guest traffic only; the host's own is
# never queued. They are written against the whole pool rather than per VM so
# that a guest the control plane does not know about is denied too.

# Everything that is not tcp. Safe to judge per packet: a udp or icmp packet is
# self-describing, so there is no handshake to preserve. A pass rule above for an
# address still gets its udp out, since pass is evaluated first.
#
# This is also what denies dns, which no guest should be sending here at all: the
# resolver is on the gateway and the input chain is what admits traffic to it, so
# a query arriving in the forward chain is one aimed at some other server.
drop ip $HOME_NET any -> any any (msg:"dclient: deny non-tcp"; ip_proto:!tcp; sid:1000010; rev:1;)

# tcp to anything but the web ports, judged at the syn.
drop tcp $HOME_NET any -> any ![80,443] (msg:"dclient: deny tcp to a non-web port"; sid:1000011; rev:1;)

# On the web ports the destination is only knowable once the request is parsed,
# so these fire on the clienthello or the request line -- one packet in, before
# any payload has left the host.
drop tls $HOME_NET any -> any any (msg:"dclient: deny tls to another host"; sid:1000012; rev:1;)
drop http $HOME_NET any -> any any (msg:"dclient: deny http to another host"; sid:1000013; rev:1;)

# Anything on 80 or 443 that is not http or tls. A positive allowlist, not a
# negative one: the two rules above only judge what detection identified as web
# traffic, so ssh, smb, quic-over-tcp and the three dozen other protocols
# suricata can name would otherwise match no rule at all and pass by default.
#
# dsize:>0 is what keeps this off the handshake. alproto is not known until there
# is payload to classify, and !http is true of an unclassified packet as well as
# of a classified-as-something-else one -- so without it this would drop the syn
# of every legitimate request. The flow:to_server says the same thing about
# direction that the queue already guarantees, and is cheap insurance if the
# other half is ever queued.
drop tcp $HOME_NET any -> any [80,443] (msg:"dclient: deny a non-web protocol on a web port"; flow:to_server; dsize:>0; app-layer-protocol:!http; app-layer-protocol:!tls; sid:1000014; rev:2;)
`

const suricataRulesHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full every time the allowed destinations of any VM on
# this host change, so a local edit survives only until the next change and then
# vanishes without warning. Record destinations against the VM in the control
# plane instead.
#
# Default deny: the rules at the bottom drop everything, and each pass rule
# above them is scoped to one VM by the source address in its header.
#
# A VM with no allowance that depends on reading a hostname also gets a blanket
# deny of its own, next to its pass rules. The floor at the bottom cannot be one
# of those -- it has to let a syn through on the web ports, or no rule matching a
# hostname would ever get to see one.
`

// generateSuricataRules compiles every allowance on one host into a local.rules
// for Suricata 8. Rows are expected in the order the query returns them, which
// groups them by VM address -- the output is therefore deterministic for a given
// database state, so an unchanged policy compiles to a byte-identical file.
func generateSuricataRules(rows []db.ListVMNetworkTargetsByClientRow) string {
	var b strings.Builder
	b.WriteString(suricataRulesHeader)

	sid := suricataPassSidBase
	for _, vm := range groupByVM(rows) {
		what := "allowed for"
		if len(vm.targets) == 0 {
			what = "nothing allowed for"
		}
		fmt.Fprintf(&b, "\n# --- %s %s (%s) at %s ---\n",
			what, ruleText(vm.name), ruleText(vm.hostID), vm.ip)

		for _, r := range vm.targets {
			for _, rule := range targetRules(r, &sid) {
				b.WriteString(rule)
				b.WriteByte('\n')
			}
		}
		if !vm.needsHandshake {
			b.WriteString(vmDenyRule(vm, &sid))
			b.WriteByte('\n')
		}
	}

	b.WriteString("\n")
	b.WriteString(suricataDenyRules)
	return b.String()
}

// vmTargets is one VM's rows, grouped out of the flat result the query returns.
type vmTargets struct {
	ip, name, hostID string
	targets          []db.ListVMNetworkTargetsByClientRow

	// needsHandshake is set when this VM has an allowance that can only be judged
	// once the handshake is done -- which is to say a domain that compiles to a
	// tls or http pass rule. It decides whether the VM gets the blanket deny
	// below, so it is the difference between a guest that can open a tcp
	// connection to any address on 80 and one that cannot.
	needsHandshake bool
}

// groupByVM collapses the query's one-row-per-allowance into one entry per VM,
// relying on the ORDER BY rather than a map so the output stays deterministic.
//
// A VM with no allowances arrives as a single row with an empty destination --
// the LEFT JOIN's placeholder -- and becomes an entry with no targets, which is
// exactly the case the blanket deny exists for.
func groupByVM(rows []db.ListVMNetworkTargetsByClientRow) []vmTargets {
	var out []vmTargets
	for _, r := range rows {
		if len(out) == 0 || out[len(out)-1].ip != r.VMIP {
			out = append(out, vmTargets{ip: r.VMIP, name: r.VMName, hostID: r.HostVMID})
		}
		g := &out[len(out)-1]
		if r.Destination == "" {
			continue
		}
		g.targets = append(g.targets, r)
		if r.Kind == "domain" {
			if tls, http := domainPorts(r.Ports); tls || http {
				g.needsHandshake = true
			}
		}
	}
	return out
}

// vmDenyRule is the blanket deny for a VM that has no name-based allowance.
//
// The split floor exists only to keep the handshake alive for rules that match
// on a hostname. A VM with none of those -- no domains at all, or only
// lookup-only ones -- has nothing to gain from it, so it is denied at the syn
// like every other port: no completed handshake to an arbitrary address, no
// unmatched ACKs, nothing.
//
// Its own pass rules still work. They name an address in the header and pass
// beats drop whatever the sid order, which is the same reason the floor below
// does not revoke them either.
func vmDenyRule(vm vmTargets, sid *int) string {
	s := *sid
	*sid++
	return fmt.Sprintf(`drop ip %s any -> any any (msg:"dclient: deny egress from %s (no name-based allowances)"; sid:%d; rev:1;)`,
		vm.ip, ruleText(vm.name), s)
}

// domainPortsNone is the ports value that means "let this name resolve and let
// nothing leave". The resolver still answers it; no pass rule is written.
//
// It is what makes an allowance like ssh-to-github.com expressible. ssh carries
// no destination name for a rule to check, so that access has to be granted by
// address as an 'ip' row -- but the guest still has to be able to resolve the
// name, and the resolver only answers what a domain row lists.
const domainPortsNone = "none"

// domainPorts reads a domain row's ports field as the two rules it can compile
// to. Empty means both, which is what every row written before the field existed
// means; 'none' matches neither, which is the lookup-only case.
//
// Only 80 and 443 are recognised, and the API rejects anything else: the ports
// suricata looks for http and tls on come from suricata.yaml, which is generated
// per host and pushed on connect, so a domain on some other port would compile to
// a rule that never matches.
func domainPorts(ports string) (tls, http bool) {
	if ports == "" {
		return true, true
	}
	for _, p := range strings.Split(ports, ",") {
		switch p {
		case "443":
			tls = true
		case "80":
			http = true
		}
	}
	return tls, http
}

// targetRules turns one allowance into the rules that express it, consuming a
// sid per rule.
//
// A domain needs one rule per protocol that carries a hostname, because there is
// no single buffer that covers both. There is deliberately no `pass dns`: guest
// dns is answered by the resolver on the gateway and never reaches the forward
// chain at all, so a dns pass rule here would only re-open talking dns to an
// arbitrary server, using an allowed name as the password.
func targetRules(r db.ListVMNetworkTargetsByClientRow, sid *int) []string {
	msg := ruleMsg(r)
	next := func() int { s := *sid; *sid++; return s }

	if r.Kind == "domain" {
		// dotprefix prepends a "." to the buffer, so `content:".example.com";
		// endswith` matches example.com and any subdomain of it but not
		// notexample.com -- which a bare endswith would let through.
		//
		// No nocase on http.host: that buffer is already normalised to lowercase,
		// and Suricata 8 rejects the rule outright rather than warning. tls.sni is
		// not normalised, so it needs it.
		dot := "." + r.Destination
		wantTLS, wantHTTP := domainPorts(r.Ports)
		var rules []string
		if wantTLS {
			rules = append(rules, fmt.Sprintf(`pass tls %s any -> any 443 (msg:"%s (tls)"; tls.sni; dotprefix; content:"%s"; nocase; endswith; sid:%d; rev:1;)`,
				r.VMIP, msg, dot, next()))
		}
		if wantHTTP {
			rules = append(rules, fmt.Sprintf(`pass http %s any -> any 80 (msg:"%s (http)"; http.host; dotprefix; content:"%s"; endswith; sid:%d; rev:1;)`,
				r.VMIP, msg, dot, next()))
		}
		return rules
	}

	// icmp has no ports -- its type and code sit where a port would be, and a rule
	// header cannot address them -- so this is the one transport that takes the
	// header's port slot as `any` and means it. Allowed on its own so that "this
	// guest may ping that host" does not have to be spelled `ip`, which would open
	// every tcp and udp port to it as well.
	if r.Transport == "icmp" {
		return []string{fmt.Sprintf(`pass icmp %s any -> %s any (msg:"%s"; sid:%d; rev:1;)`,
			r.VMIP, r.Destination, msg, next())}
	}

	ports := r.Ports
	switch {
	case ports == "":
		ports = "any"
	case strings.Contains(ports, ","):
		// A list is only a list to Suricata inside brackets; bare `80,443` in a
		// header is a parse error, and a parse error takes the whole file down --
		// every other VM's policy with it.
		ports = "[" + ports + "]"
	}
	// Ports are a transport concept, so `ip` -- which is how "either transport"
	// is spelled in a rule header -- can only be used when no port was asked for.
	// With one, the same allowance has to be written once per transport.
	protos := []string{r.Transport}
	if r.Transport == "any" {
		if ports == "any" {
			protos = []string{"ip"}
		} else {
			protos = []string{"tcp", "udp"}
		}
	}

	rules := make([]string, 0, len(protos))
	for _, p := range protos {
		rules = append(rules, fmt.Sprintf(`pass %s %s any -> %s %s (msg:"%s"; sid:%d; rev:1;)`,
			p, r.VMIP, r.Destination, ports, msg, next()))
	}
	return rules
}

// ruleMsg is what shows up in the alert log. The note is included because an
// allowance nobody can explain is one nobody can safely prune later, and this is
// where an operator reading logs will meet it.
func ruleMsg(r db.ListVMNetworkTargetsByClientRow) string {
	msg := fmt.Sprintf("dclient: allow %s from %s", ruleText(r.Destination), ruleText(r.VMName))
	if r.Note != "" {
		msg += " -- " + ruleText(r.Note)
	}
	return msg
}

// ruleText makes a free-text field safe to sit inside a rule option. A quote
// ends the msg early and a semicolon ends the option, either of which turns one
// bad note into a ruleset Suricata refuses to load -- and with it every other
// VM's policy on the host.
var ruleTextReplacer = strings.NewReplacer(
	`"`, "'", ";", ",", `\`, "/", "\n", " ", "\r", " ",
)

func ruleText(s string) string {
	out := strings.TrimSpace(ruleTextReplacer.Replace(s))
	if out == "" {
		return "unnamed"
	}
	if len(out) > 120 {
		out = out[:120]
	}
	return out
}

// pushSuricataRules regenerates the host's ruleset and sends it. Called after
// anything that changes what a VM on that host is allowed to reach.
//
// Failures are logged rather than returned to the caller: the destination has
// already been recorded, and failing the request would tell the user their
// change did not happen when it did. An offline client picks the ruleset up when
// it reconnects, since dclient asks for one on connect.
func pushSuricataRules(ctx context.Context, q *db.Queries, hub *Hub, clientID pgtype.UUID) {
	id := uuid.UUID(clientID.Bytes).String()
	rows, err := q.ListVMNetworkTargetsByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the allowed destinations for client %s: %v", id, err)
		return
	}
	env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
		Kind:     proto.KindSuricataRules,
		Suricata: &proto.SuricataRules{Rules: generateSuricataRules(rows)},
	})
	if err != nil {
		log.Printf("could not build the suricata rules job for client %s: %v", id, err)
		return
	}
	// A send failure is expected whenever the host is down, and there is nothing
	// to retry: dclient asks for the ruleset itself as soon as it reconnects.
	if err := hub.Send(id, env); err != nil {
		log.Printf("could not deliver the suricata ruleset to client %s: %v", id, err)
	}
}
