package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"

	"control/internal/db"
	"control/internal/proto"
)

const (
	suricataDenySidBase = 1000010
	suricataPassSidBase = 1000100
)

const suricataDenyRules = `# --- default deny ---------------------------------------------------------
# $HOME_NET is the VM pool, so these judge guest traffic only; the host's own is
# never queued. They are written against the whole pool rather than per VM so
# that a guest the control plane does not know about is denied too.

# Everything that is not tcp. Safe to judge per packet: a udp or icmp packet is
# self-describing, so there is no handshake to preserve. A pass rule above for an
# address still gets its udp out, since pass is evaluated first.
#
# This is also what denies dns, which no guest should be sending here at all: the
# resolver is on the gateway and the input chain is what admits traffic to it, so
# a query arriving in the forward chain is one aimed at some other server.
drop ip $HOME_NET any -> any any (msg:"dclient: deny non-tcp"; ip_proto:!tcp; sid:1000010; rev:1;)

# tcp to anything but the web ports, judged at the syn.
drop tcp $HOME_NET any -> any ![80,443] (msg:"dclient: deny tcp to a non-web port"; sid:1000011; rev:1;)

# On the web ports the destination is only knowable once the request is parsed,
# so these fire on the clienthello or the request line -- one packet in, before
# any payload has left the host.
#
# ssl_state is what makes the tls one wait for that parse instead of firing the
# moment detection decides a flow is tls. A modern clienthello is bigger than one
# segment -- openssl 3.5 offers a post-quantum key share and lands around 1600
# bytes against a 1460 byte mss -- so it arrives in two packets, and tls.sni does
# not exist until both have been reassembled. Without the state check this drop
# takes the first of those two packets, the pass rule never gets a name to match,
# the clienthello is never completed, and an allowed host hangs until the client
# gives up. ssl_state:client_hello is set by the parser, which runs before
# detection on the packet that completes the record -- so the pass rule and this
# rule are evaluated together on that packet, and pass wins.
#
# The cost is a flow whose clienthello never parses at all: detection calls it
# tls from the record header, no state is ever reached, and neither this rule nor
# the protocol allowlist below matches it. That is a narrow covert channel to any
# address on 443, and it is the same one the split floor already leaves open by
# letting the handshake complete. Closing it properly is the resolver-writes-an-
# nftables-set design, not another rule.
drop tls $HOME_NET any -> any any (msg:"dclient: deny tls to another host"; flow:to_server; ssl_state:client_hello; sid:1000012; rev:2;)
drop http $HOME_NET any -> any any (msg:"dclient: deny http to another host"; sid:1000013; rev:1;)

# Anything on 80 or 443 that is not http or tls. A positive allowlist, not a
# negative one: the two rules above only judge what detection identified as web
# traffic, so ssh, smb, quic-over-tcp and the three dozen other protocols
# suricata can name would otherwise match no rule at all and pass by default.
#
# dsize:>0 is what keeps this off the handshake. alproto is not known until there
# is payload to classify, and !http is true of an unclassified packet as well as
# of a classified-as-something-else one -- so without it this would drop the syn
# of every legitimate request. The flow:to_server says the same thing about
# direction that the queue already guarantees, and is cheap insurance if the
# other half is ever queued.
drop tcp $HOME_NET any -> any [80,443] (msg:"dclient: deny a non-web protocol on a web port"; flow:to_server; dsize:>0; app-layer-protocol:!http; app-layer-protocol:!tls; sid:1000014; rev:2;)
`

const suricataRulesHeader = `# Generated by the control server. Do not edit.
#
# This file is replaced in full every time the allowed destinations of any VM on
# this host change, so a local edit survives only until the next change and then
# vanishes without warning. Record destinations against the VM in the control
# plane instead.
#
# Default deny: the rules at the bottom drop everything, and each pass rule
# above them is scoped to one VM by the source address in its header.
#
# A VM with no allowance that depends on reading a hostname also gets a blanket
# deny of its own, next to its pass rules. The floor at the bottom cannot be one
# of those -- it has to let a syn through on the web ports, or no rule matching a
# hostname would ever get to see one.
`

func generateSuricataRules(rows []db.ListVMNetworkTargetsByClientRow) string {
	var b strings.Builder
	b.WriteString(suricataRulesHeader)

	sid := suricataPassSidBase
	for _, vm := range groupByVM(rows) {
		what := "allowed for"
		switch {
		case vm.allowAll:
			what = "everything allowed for"
		case len(vm.targets) == 0:
			what = "nothing allowed for"
		}
		fmt.Fprintf(&b, "\n# --- %s %s (%s) at %s ---\n",
			what, ruleText(vm.name), ruleText(vm.hostID), vm.ip)

		for _, r := range vm.targets {
			for _, rule := range targetRules(r, &sid) {
				b.WriteString(rule)
				b.WriteByte('\n')
			}
		}
		if !vm.needsHandshake && !vm.allowAll {
			b.WriteString(vmDenyRule(vm, &sid))
			b.WriteByte('\n')
		}
	}

	b.WriteString("\n")
	b.WriteString(suricataDenyRules)
	return b.String()
}

type vmTargets struct {
	ip, name, hostID string
	targets          []db.ListVMNetworkTargetsByClientRow

	needsHandshake bool

	allowAll bool
}

// The whole address space allowed on every transport: the pass rule it compiles
// to matches everything, so the guest is off the allowlist entirely and the
// resolver has to answer for every name too.
const targetEverywhere = "0.0.0.0/0"

func isEverywhere(r db.ListVMNetworkTargetsByClientRow) bool {
	return r.Kind == "ip" && r.Destination == targetEverywhere &&
		r.Transport == "any" && r.Ports == ""
}

func groupByVM(rows []db.ListVMNetworkTargetsByClientRow) []vmTargets {
	var out []vmTargets
	for _, r := range rows {
		if len(out) == 0 || out[len(out)-1].ip != r.VMIP {
			out = append(out, vmTargets{ip: r.VMIP, name: r.VMName, hostID: r.HostVMID})
		}
		g := &out[len(out)-1]
		if r.Destination == "" {
			continue
		}
		g.targets = append(g.targets, r)
		if isEverywhere(r) {
			g.allowAll = true
		}
		if r.Kind == "domain" {
			if tls, http := domainPorts(r.Ports); tls || http {
				g.needsHandshake = true
			}
		}
	}
	return out
}

func vmDenyRule(vm vmTargets, sid *int) string {
	s := *sid
	*sid++
	return fmt.Sprintf(`drop ip %s any -> any any (msg:"dclient: deny egress from %s (no name-based allowances)"; sid:%d; rev:1;)`,
		vm.ip, ruleText(vm.name), s)
}

const domainPortsNone = "none"

func domainPorts(ports string) (tls, http bool) {
	if ports == "" {
		return true, true
	}
	for _, p := range strings.Split(ports, ",") {
		switch p {
		case "443":
			tls = true
		case "80":
			http = true
		}
	}
	return tls, http
}

func targetRules(r db.ListVMNetworkTargetsByClientRow, sid *int) []string {
	msg := ruleMsg(r)
	next := func() int { s := *sid; *sid++; return s }

	if r.Kind == "domain" {
		dot := "." + r.Destination
		wantTLS, wantHTTP := domainPorts(r.Ports)
		var rules []string
		if wantTLS {
			rules = append(rules, fmt.Sprintf(`pass tls %s any -> any 443 (msg:"%s (tls)"; tls.sni; dotprefix; content:"%s"; nocase; endswith; sid:%d; rev:1;)`,
				r.VMIP, msg, dot, next()))
		}
		if wantHTTP {
			rules = append(rules, fmt.Sprintf(`pass http %s any -> any 80 (msg:"%s (http)"; http.host; dotprefix; content:"%s"; endswith; sid:%d; rev:1;)`,
				r.VMIP, msg, dot, next()))
		}
		return rules
	}

	if r.Transport == "icmp" {
		return []string{fmt.Sprintf(`pass icmp %s any -> %s any (msg:"%s"; sid:%d; rev:1;)`,
			r.VMIP, r.Destination, msg, next())}
	}

	ports := r.Ports
	switch {
	case ports == "":
		ports = "any"
	case strings.Contains(ports, ","):
		ports = "[" + ports + "]"
	}
	protos := []string{r.Transport}
	if r.Transport == "any" {
		if ports == "any" {
			protos = []string{"ip"}
		} else {
			protos = []string{"tcp", "udp"}
		}
	}

	rules := make([]string, 0, len(protos))
	for _, p := range protos {
		rules = append(rules, fmt.Sprintf(`pass %s %s any -> %s %s (msg:"%s"; sid:%d; rev:1;)`,
			p, r.VMIP, r.Destination, ports, msg, next()))
	}
	return rules
}

func ruleMsg(r db.ListVMNetworkTargetsByClientRow) string {
	msg := fmt.Sprintf("dclient: allow %s from %s", ruleText(r.Destination), ruleText(r.VMName))
	if r.Note != "" {
		msg += " -- " + ruleText(r.Note)
	}
	return msg
}

var ruleTextReplacer = strings.NewReplacer(
	`"`, "'", ";", ",", `\`, "/", "\n", " ", "\r", " ",
)

func ruleText(s string) string {
	out := strings.TrimSpace(ruleTextReplacer.Replace(s))
	if out == "" {
		return "unnamed"
	}
	if len(out) > 120 {
		out = out[:120]
	}
	return out
}

func pushSuricataRules(ctx context.Context, q *db.Queries, hub *Hub, clientID pgtype.UUID) {
	id := uuid.UUID(clientID.Bytes).String()
	rows, err := q.ListVMNetworkTargetsByClient(ctx, clientID)
	if err != nil {
		log.Printf("could not read the allowed destinations for client %s: %v", id, err)
		return
	}
	env, err := proto.NewEnvelope(proto.TypeJob, "", proto.Job{
		Kind:     proto.KindSuricataRules,
		Suricata: &proto.SuricataRules{Rules: generateSuricataRules(rows)},
	})
	if err != nil {
		log.Printf("could not build the suricata rules job for client %s: %v", id, err)
		return
	}
	if err := hub.Send(id, env); err != nil {
		log.Printf("could not deliver the suricata ruleset to client %s: %v", id, err)
	}
}
